components/mediation-admin/org.wso2.carbon.connector.core/pom.xml, components/mediation-admin/org.wso2.carbon.endpoint/pom.xml, components/mediation-admin/org.wso2.carbon.localentry/pom.xml, components/mediation-admin/org.wso2.carbon.mediation.library/pom.xml, components/mediation-admin/org.wso2.carbon.mediation.templates.service/pom.xml, components/mediation-admin/org.wso2.carbon.mediation.templates/pom.xml, components/mediation-admin/org.wso2.carbon.mediator.service/pom.xml, components/mediation-admin/org.wso2.carbon.message.processor/pom.xml, components/mediation-admin/org.wso2.carbon.message.store/pom.xml, components/mediation-admin/org.wso2.carbon.priority.executors/pom.xml, components/mediation-admin/org.wso2.carbon.proxyadmin.common/pom.xml, components/mediation-admin/org.wso2.carbon.proxyadmin/pom.xml, components/mediation-admin/org.wso2.carbon.rest.api/pom.xml, components/mediation-admin/org.wso2.carbon.sequences/pom.xml, components/mediation-config-admin/org.wso2.carbon.mediation.configadmin/pom.xml, pom.xml
Adding changes done for removing static version references and defining variables in parent pom level
=> Release 4.3.0

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.dbreport.ui/src/main/java/org/wso2/carbon/mediator/dbreport/DBReportMediatorClient.java
=> Added the null check for the JNDI config

components/mediation-ntask/src/main/java/org/wso2/carbon/mediation/ntask/NTaskTaskManager.java, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/org/wso2/carbon/message/processor/ui/i18n/Resources.properties, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/manageMessageForwardingProcessor.jsp
=> New msmp coordination support

components/mediation-ntask/src/main/java/org/wso2/carbon/mediation/ntask/MultiMemberTaskLocationResolver.java
Task location resolver was added.
=> multi-member task location resolver was added.

components/mediation-ui/org.wso2.carbon.message.store.ui/pom.xml, components/mediation-ui/org.wso2.carbon.message.store.ui/src/main/java/org/wso2/carbon/message/store/ui/MessageStoreAdminServiceClient.java, components/mediation-ui/org.wso2.carbon.message.store.ui/src/main/resources/org/wso2/carbon/message/store/ui/i18n/Resources.properties, components/mediation-ui/org.wso2.carbon.message.store.ui/src/main/resources/web/message_store/index.jsp, components/mediation-ui/org.wso2.carbon.message.store.ui/src/main/resources/web/message_store/jdbcMessageStore.jsp, components/mediation-ui/org.wso2.carbon.message.store.ui/src/main/resources/web/message_store/js/messageStore-util.js, components/mediation-ui/org.wso2.carbon.message.store.ui/src/main/resources/web/message_store/sourceView.jsp, components/mediation-ui/org.wso2.carbon.message.store.ui/src/main/resources/web/message_store/updatePages/jdbcMessageStoreUpdate.jsp, components/mediation-ui/org.wso2.carbon.message.store.ui/src/main/resources/web/message_store/viewMessageStore.jsp
This is the UI implementation related to JDBC Message Store which will be available on WSO2 ESB 4.9.0
=> JDBC Message Store UI

components/mediation-admin/org.wso2.carbon.mediation.library/src/main/java/org/wso2/carbon/mediation/library/service/MediationLibraryAdminService.java, components/mediation-admin/org.wso2.carbon.task/src/main/java/org/wso2/carbon/task/CarbonTaskManagementService.java, service-stubs/mediation-admin/org.wso2.carbon.task.stub/src/main/resources/TaskAdmin.wsdl
Reverts wso2/carbon-mediation#149
=> Revert "Changing task admin services to return boolean value"

components/mediation-ui/org.wso2.carbon.message.store.ui/src/main/resources/org/wso2/carbon/message/store/ui/i18n/Resources.properties, components/mediation-ui/org.wso2.carbon.message.store.ui/src/main/resources/web/message_store/jdbcMessageStore.jsp
This is to fix validation of some fields in JDBC Store, while saving data
=> Adding error messages and validation checks for other required fields

components/mediation-ui/org.wso2.carbon.message.store.ui/src/main/resources/web/message_store/jdbcMessageStore.jsp
Data base connection details checking even wso2 carbon DB is selected. Validation changed only for inline connection.
=> ESBJAVA-3742: JDBC message store creating issue fixed.

components/mediators/bam/org.wso2.carbon.mediator.bam/src/main/java/org/wso2/carbon/mediator/bam/BamMediator.java, components/mediators/bam/org.wso2.carbon.mediator.bam/src/main/java/org/wso2/carbon/mediator/bam/xml/BamMediatorFactory.java
BAM mediator builds content only if required.
=> BAM mediator patch

components/mediation-ui/org.wso2.carbon.proxyadmin.ui/src/main/resources/web/proxyservices/designToData.jsp, components/mediation-ui/org.wso2.carbon.proxyadmin.ui/src/main/resources/web/proxyservices/index.jsp
=> Changed parameter key and value split logic to support comma separate values

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpListener.java
Reverts wso2/carbon-mediation#264
=> Revert "Fix ESBJAVA-3841"

components/mediation-ui/org.wso2.carbon.message.store.ui/src/main/resources/web/message_store/viewMessageStore.jsp
https://wso2.org/jira/browse/ESBJAVA-3912
=> Fixing the UI issue related to JDBC Store

components/mediation-ui/org.wso2.carbon.rest.api.ui/src/main/resources/web/api/manageAPI.jsp
Fixed issue of not loading last saved API to design view, when saved through source view.
=> API Management - UI fixes

components/application-mgt/org.wso2.carbon.application.mgt.synapse.ui/src/main/resources/web/synapse-apps/index.jsp
Fix related to https://wso2.org/jira/browse/ESBJAVA-2287
=> Adding the fix to avoid dead page

components/mediation-ui/org.wso2.carbon.message.store.ui/src/main/resources/org/wso2/carbon/message/store/ui/i18n/Resources.properties, components/mediation-ui/org.wso2.carbon.message.store.ui/src/main/resources/web/message_store/jdbcMessageStore.jsp
Rather using default table name, make the table name compulsory field. So users must give a table name to be used
=> Make table name compulsory

components/mediation-ui/org.wso2.carbon.rest.api.ui/src/main/java/org/wso2/carbon/rest/api/ui/util/ApiEditorHelper.java
Reverts wso2/carbon-mediation#314
=> Revert "Fix ESBJAVA-3956" due to compilation error

components/mediation-ui/org.wso2.carbon.proxyadmin.ui/src/main/resources/web/proxyservices/index.jsp
Issue reference https://wso2.org/jira/browse/ESBJAVA-3152
=> Fix for the issue ESBJAVA-3152

components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/WSO2Registry.java
This will fix test case failures of script mediator.
=> ESBJAVA-3225 Fixes corrected to handle media type not null scenarios

components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/inboundcommon.js
Added js validation for the interval field to determine whether the interval field contains a number
=> Fix added to validate the interval field, ESBJAVA-3972

components/mediation-admin/org.wso2.carbon.endpoint/src/main/java/org/wso2/carbon/endpoint/service/EndpointAdmin.java
Public Jira reference  https://wso2.org/jira/browse/ESBJAVA-2370
=> Fix for the ESBJAVA-2370

components/mediation-monitor/mediation-statistics/org.wso2.carbon.mediation.statistics/src/main/java/org/wso2/carbon/mediation/statistics/persistence/PersistingStatisticsObserver.java
Fix for https://wso2.org/jira/browse/ESBJAVA-3364
=> https://wso2.org/jira/browse/ESBJAVA-3364

components/mediation-ui/org.wso2.carbon.proxyadmin.ui/src/main/resources/web/proxy/editCAppartifact.jsp, components/mediation-ui/org.wso2.carbon.proxyadmin.ui/src/main/resources/web/proxy/identifyCAppArtifact.jsp
These pages added temporarily to support changes from PR https://github.com/wso2/carbon-deployment/pull/104.
=> Two JSP pages added to support the change in carbon-deployment changes

components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/org/wso2/carbon/message/processor/ui/i18n/Resources.properties, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/manageMessageForwardingProcessor.jsp
fix in https://github.com/wso2/carbon-mediation/pull/168 moved to master branch
=> ESBJAVA-3757 fix moved to master branch

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/kafka/KAFKAProcessor.java
Issue happen because Kafka task is not undeployed correctly
=> Esbjava 4038

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/kafka/AbstractKafkaMessageListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/kafka/KAFKAConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/kafka/KAFKAMessageListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/kafka/KAFKAPollingConsumer.java
+Added default to default consumer timeout to 3000ms as if not inbound endpoint will infintely wait till for new message to arrive and at that time we can't update or undeploy it kafka endpoint
+added ability to consume from multiple topics
=> Esbjava 4044

components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/editInbound.jsp, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/inboundcommon.js, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/newInbound1.jsp
Low level parameters in Kafka configuration are not validated
=> "Fixing kafka required parameters in UI are not validated"

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/kafka/KAFKAMessageListener.java
Fixing Kafka inbound endpoint is running,server shutdown throws Interrupted Exception
=> ESBJAVA-4170

components/application-mgt/org.wso2.carbon.application.mgt.synapse/src/main/java/org/wso2/carbon/application/mgt/synapse/internal/SynapseConfigAdmin.java
Fixing Mouse click on cApp link which is deployed with HTTP Endpoint OR Template Endpoint giving an exception
=> ESBJAVA-4135

components/mediation-initializer/org.wso2.carbon.mediation.initializer/src/main/java/org/wso2/carbon/mediation/initializer/handler/CarbonTenantInfoConfigurator.java, components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/src/main/java/org/wso2/carbon/mediation/transport/handlers/PassThroughNHttpGetProcessor.java, components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/WSO2Registry.java
This issue has been reported through several jira tickets
https://wso2.org/jira/browse/ESBJAVA-3832
https://wso2.org/jira/browse/ESBJAVA-4142
=> Fixing the empty stack exception occurred at several message flows

pom.xml
to compatible with identity 5.0.2
=> carbon-commons, deployment and identity versions updated 

components/mediation-monitor/message-flow-tracer/org.wso2.carbon.message.flow.tracer.ui/src/main/resources/web/messageflow-tracer/index.jsp
=> Flow tracer changes-1

components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/APIData.java, components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/service/RestApiAdmin.java, components/mediation-monitor/message-flow-tracer/org.wso2.carbon.message.flow.tracer.ui/src/main/resources/web/messageflow-tracer/messageflowdetails.jsp, components/mediation-monitor/message-flow-tracer/org.wso2.carbon.message.flow.tracer/src/main/java/org/wso2/carbon/message/flow/tracer/services/MessageFlowTracerAdminService.java, components/mediation-ui/org.wso2.carbon.rest.api.ui/src/main/java/org/wso2/carbon/rest/api/ui/client/RestApiAdminClient.java, components/mediation-ui/org.wso2.carbon.rest.api.ui/src/main/resources/org/wso2/carbon/rest/api/ui/i18n/Resources.properties, components/mediation-ui/org.wso2.carbon.rest.api.ui/src/main/resources/web/api/index.jsp, components/mediation-ui/org.wso2.carbon.rest.api.ui/src/main/resources/web/api/trace-ajaxprocessor.jsp, service-stubs/mediation-admin/org.wso2.carbon.rest.api.stub/src/main/resources/RestApiAdmin.wsdl
Improve message flow tracer component by using JSON message passing
Provide UI functionality to enable tracing via management console UI
=> Flow tracer ui changes & API tracing state change via UI

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpServerWorker.java, components/mediation-admin/org.wso2.carbon.inbound/src/main/java/org/wso2/carbon/inbound/CarbonInboundManagementService.java, components/mediation-admin/org.wso2.carbon.inbound/src/main/java/org/wso2/carbon/inbound/InboundEndpointDTO.java, components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/service/RestApiAdmin.java, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/java/org/wso2/carbon/inbound/ui/internal/InboundDescription.java, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/java/org/wso2/carbon/inbound/ui/internal/InboundManagementClient.java, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/WSDL/InboundAdmin.wsdl, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/inboundcommon.js, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/index.jsp, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/trace-ajaxprocessor.jsp, service-stubs/mediation-admin/org.wso2.carbon.inbound.stub/src/main/resources/InboundAdmin.wsdl
Adding UI support for changing state of Inbound EP tracing.
Modify Inbound EP index page UI
=> Change UI for tracing enabling

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/publish/Publisher.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/util/MediationDataPublisherConstants.java
Remove Trace-event related configs
=> DAS publisher remove trace-events

pom.xml
remove snaphots and update synapse to 2.1.7-wso2v1
=> Release preparation

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/publish/Publisher.java
Using GZIP compression and DatatypeConverter base-64 encoding
Move host-name inside compressed payload
=> Change compression when publishing

components/carbon-mediation-startup/org.wso2.carbon.mediation.startup/pom.xml, components/carbon-mediation-startup/org.wso2.carbon.mediation.startup/src/main/java/org/wso2/carbon/mediation/startup/StartupAdminService.java, components/carbon-mediation-startup/org.wso2.carbon.mediation.startup/src/main/java/org/wso2/carbon/mediation/startup/StartupJobMetaDataProviderService.java, components/carbon-mediation-startup/org.wso2.carbon.mediation.startup/src/main/java/org/wso2/carbon/mediation/startup/StartupTaskDeployer.java, components/carbon-mediation-startup/org.wso2.carbon.mediation.startup/src/main/java/org/wso2/carbon/mediation/startup/StartupUtils.java, components/carbon-mediation-startup/org.wso2.carbon.mediation.startup/src/main/java/org/wso2/carbon/mediation/startup/internal/StartupAdminServiceComponent.java, components/carbon-mediation-startup/org.wso2.carbon.mediation.startup/src/main/java/org/wso2/carbon/mediation/startup/util/ConfigHolder.java, components/carbon-mediation-startup/pom.xml, features/mediation-initializer-features/org.wso2.carbon.mediation.initializer.server.feature/pom.xml, pom.xml
Moving the startup component in https://svn.wso2.org/repos/wso2/carbon/platform/trunk/components/startup/ to carbon mediation
=> Moving startup component inside carbon mediation

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/internal/MediationStatisticsComponent.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/publish/ConfigurationPublisher.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/services/MediationConfigReporterThread.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/util/MediationDataPublisherConstants.java
=> JSON structure generation for DAS - 2

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher.ui/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/ui/DASMessageFlowPublisherAdminClient.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher.ui/src/main/resources/web/dasmessageflowpub/configure_publisher.jsp, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher.ui/src/main/resources/web/dasmessageflowpub/publisher_list.jsp, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/conf/PublisherConfig.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/conf/PublisherProfile.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/conf/PublisherProfileManager.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/conf/RegistryPersistenceManager.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/internal/MediationStatisticsComponent.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/observer/DASMediationFlowObserver.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/publish/ConfigurationPublisher.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/publish/StatisticsPublisher.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/services/DASMessageFlowPublisherAdmin.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/services/MediationConfigReporterThread.java, service-stubs/mediation-monitor/org.wso2.carbon.das.messageflow.data.publisher.stub/src/main/resources/DASMessageFlowPublisherAdmin.wsdl
* Change class names in meaningful manner
* Update FE and Service-Stub accordingly
* Introduce Publisher Profile and Publisher Profile Manager
* Admin service now using RegistryPersistenceManager indirectly
* Configuration in-memory persistence for publishing to DAS servers joining after ESB startup time
=> Refactor statistics publisher for DAS

components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/java/org/wso2/carbon/inbound/ui/internal/InboundManagementClient.java
Update CApp Inbount Endpoint which contains registry references
=> Fix ESBJAVA-4579

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/publish/StatisticsPublisher.java
Need to register classes with numbering, which should match same order numbering from analytic server side. Else will see ArrayOutOfBound Exceptions from Analytic Server side.
=> Registering classes for kryo with numbering

features/synapse-features/org.apache.synapse.transport.nhttp.feature/pom.xml, pom.xml
Fixing the https://wso2.org/jira/browse/ESBJAVA-4060 issue with httpclient upgrade
=> httpclient version upgrade to 4.3.2

components/mediation-ui/org.wso2.carbon.task.ui/src/main/resources/web/task/classload-ajaxprocessor.jsp, components/mediation-ui/org.wso2.carbon.task.ui/src/main/resources/web/task/classreload-ajaxprocessor.jsp, components/mediation-ui/org.wso2.carbon.task.ui/src/main/resources/web/task/edittask.jsp, components/mediation-ui/org.wso2.carbon.task.ui/src/main/resources/web/task/taskcommon.js
UI related fix for : https://github.com/wso2/wso2-synapse/pull/559 along with few other UI fixes for scheduled task UI
=> Enable registry based scheduled tasks to get saved

components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/java/org/wso2/carbon/inbound/ui/internal/InboundClientConstants.java, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/config/inbound.properties, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/editInbound.jsp, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/newInbound.jsp, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/newInbound1.jsp, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/saveInbound.jsp, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/updateInbound.jsp
This consists of how WSO2 MB inbound can be configured ESB. Implementation is handled with in UI level.
=> WSO2 MB inbound implementation

components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/resources/web/sequences/design_sequence.jsp
=> Hiding dynamic-sequence name from UI

components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/ScheduledForwardingProcessorView.jsp, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/ScheduledProcessorActionHandler.jsp, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/deleteAll.jsp, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/deleteFirstMessage.jsp, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/deleteMessage.jsp, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/deleteMessageProcessorHandler.jsp, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/index.jsp, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/resendAll.jsp, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/resendFirstMessage.jsp, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/resendMessage.jsp, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/viewEnvelope.jsp
Reverts wso2/carbon-mediation#641
=> Revert "Security fixes message processor"

components/mediators/bam/org.wso2.carbon.mediator.bam/src/main/java/org/wso2/carbon/mediator/bam/Stream.java
Public JIRA: https://wso2.org/jira/browse/ESBJAVA-4755
=> Changing auth ports in stream for BAM mediator

components/mediation-initializer/org.wso2.carbon.mediation.initializer/src/main/java/org/wso2/carbon/mediation/initializer/multitenancy/TenantServiceBusInitializer.java
Copy super-tenant's event publishers to tenant when tenant is initializing
=> Make tenant-initializer to copy event-publishers and event-streams

components/mediation-initializer/org.wso2.carbon.mediation.initializer/src/main/java/org/wso2/carbon/mediation/initializer/multitenancy/TenantServiceBusInitializer.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/observer/DASMediationFlowObserver.java
Reverting PR: https://github.com/wso2/carbon-mediation/pull/688
=> Make all publishing via super tenant

components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/config/inbound.properties
Added the transport.jms.ConnectionFactoryJNDIName to the wso2 MB inbound ui as a mandatory property. This will solve the issue reported at https://wso2.org/jira/browse/ESBJAVA-4839
=> Fixing ESBJAVA-4839

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.payloadfactory.ui/src/main/java/org/wso2/carbon/mediator/payloadfactory/PayloadFactoryMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.payloadfactory.ui/src/main/resources/org/wso2/carbon/mediator/payloadfactory/ui/i18n/JSResources.properties, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.payloadfactory.ui/src/main/resources/org/wso2/carbon/mediator/payloadfactory/ui/i18n/Resources.properties, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.payloadfactory.ui/src/main/resources/web/payloadfactory-mediator/edit-mediator.jsp, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.payloadfactory.ui/src/main/resources/web/payloadfactory-mediator/js/mediator-util.js, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.payloadfactory.ui/src/main/resources/web/payloadfactory-mediator/update-mediator.jsp
introducing 'literal' attribute for payload factory mediator
=> UI fixes for ESBJAVA-4895, 'literal' attribute

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/HandshakeHandlerBuilderUtil.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketChannelInitializer.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketConfiguration.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/PipelineHandlerBuilderUtil.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/management/WebsocketEndpointManager.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/pipelinehandlers/SamplePipelineHandler.java
Add HandshakeHandler and DispatchToCustomSequence functionality to websocket inbound endpoints.
=> Adding "HandshakeHandler" and "DispatchToCustomSequence" functionality

components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/SecureVaultLookupHandlerImpl.java
Public Jira - (https://wso2.org/jira/browse/ESBJAVA-4980)
=> [ESBJAVA-4980] Fix for secure vault lookup error on cache expiry

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQConnectionFactory.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQUtils.java
Fixes the issue reported at https://wso2.org/jira/browse/ESBJAVA-4979
=> ESBJAVA-4979 support multiple rabbitmq hosts

pom.xml
This Pull request was sent to get a release.
=> Remove unwanted space

components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/CarbonDestinationDataProvider.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/SecureVaultConstants.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/util/SecureVaultUtil.java, components/mediation-initializer/org.wso2.carbon.mediation.initializer/src/main/java/org/wso2/carbon/mediation/initializer/ServiceBusInitializer.java, components/mediation-initializer/org.wso2.carbon.mediation.initializer/src/main/java/org/wso2/carbon/mediation/initializer/multitenancy/TenantServiceBusInitializer.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.payloadfactory.ui/src/main/java/org/wso2/carbon/mediator/payloadfactory/PayloadFactoryMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.payloadfactory.ui/src/main/resources/org/wso2/carbon/mediator/payloadfactory/ui/i18n/JSResources.properties, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.payloadfactory.ui/src/main/resources/org/wso2/carbon/mediator/payloadfactory/ui/i18n/Resources.properties, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.payloadfactory.ui/src/main/resources/web/payloadfactory-mediator/edit-mediator.jsp, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.payloadfactory.ui/src/main/resources/web/payloadfactory-mediator/js/mediator-util.js, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.payloadfactory.ui/src/main/resources/web/payloadfactory-mediator/update-mediator.jsp
This contains the reverting of deepCheck attribute from carbon-mediation and Path resolution changes required for the EI 6.0.0 to resolve https://github.com/wso2/product-ei/issues/128
=> Reverting deepCheck for UI in https://wso2.org/jira/browse/ESBJAVA-5008

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQConnectionConsumer.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQInjectHandler.java
rabbitmq.queue.durable parameter not set issue fixed and transaction support added to RabbitMQ inbound endpoint.
Public JIRA - https://wso2.org/jira/browse/ESBJAVA-5050, https://wso2.org/jira/browse/ESBJAVA-5059
=> Fix ESBJAVA-5050, ESBJAVA5059

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/mapper/MappingResource.java
This fix the issue https://github.com/wso2/product-ei/issues/413 by
adding new line characters between function lines.
=> Allow single line comments in datamapper custom functions

components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/MediationSecurityAdminService.java, components/mediation-ui/org.wso2.carbon.mediation.security.ui/src/main/resources/web/mediation_secure_vault/properties-ajaxprocessor.jsp
This contains the fix for UI issue https://github.com/wso2/product-ei/issues/403. It is required with the change done in carbon-kernel with https://github.com/wso2/carbon-kernel/commit/42a19f8d029ee872c98790635a0be093c78c49b2.
Also corrected file paths and documentation details in error message according to latest releases.
=> Fix UI issue in EI, when adding passwords to secure vault

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQConnectionConsumer.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQInjectHandler.java
This fixes the issue of throwing a NPE when consuming data using RabbitMq inboundEP and also fixes the issue of not publishing stats for RabbitMq inboundEP
ESB Jira - https://wso2.org/jira/browse/ESBJAVA-5070
ESB Analytics Jira - https://wso2.org/jira/browse/ANLYESB-203
=> Fix stat publishing issue of RabbitMq inboundEP

pom.xml
=> Update synapse.version, carbon.kernel.version

features/synapse-features/org.apache.synapse.transport.vfs.feature/pom.xml, pom.xml
This upgrade fixes https://wso2.org/jira/browse/ESBJAVA-5087
=> Update jsch version to 0.1.54.wso2v1

components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediator.java
This PR fixes the issue of removing brackets around a single element Json
response when response caching is enabled.
Fixes: https://wso2.org/jira/browse/APIMANAGER-5805
Fixes: https://github.com/wso2/product-ei/issues/691
=> Fix APIMANAGER-5805

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/mapper/MappingHandler.java
This fixes the issue of JS script engine used in DataMapper not getting released when an exception thrown at expression evaluation
https://github.com/wso2/product-ei/issues/650
=> Fix issue of not releasing the JS script engine

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/mapper/MappingResource.java
Related public JIRA : https://wso2.org/jira/browse/ESBJAVA-5200
=> ESBJAVA-5200:Replace special characters in jsFunction name

components/mediation-admin/org.wso2.carbon.localentry/src/main/java/org/wso2/carbon/localentry/service/LocalEntryAdmin.java
Fix https://wso2.org/jira/browse/ESBJAVA-5170
=> [ESBJAVA-5170] Fix NPE in local entry admin service

components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/java/org/wso2/carbon/inbound/ui/internal/InboundManagementClient.java
Fixes https://github.com/wso2/product-ei/issues/805
=> [EI-805] Fix Set Inbound Endpoint port parameter from registry reference

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/pom.xml
Corrects the Export-Package name to " org.wso2.carbon.das.messageflow.data.publisher.* "
=> Corrects the Export-Package name to the actual package name

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.enrich.ui/src/main/resources/web/enrich-mediator/edit-mediator.jsp
Clean up Enrich Mediator by removing redundant combination of source and target type
https://wso2.org/jira/browse/ESBJAVA-3688
=> ESBJAVA-3688 - Clean up Enrich Mediator

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.enrich.ui/src/main/resources/web/enrich-mediator/edit-mediator.jsp
Reverts wso2/carbon-mediation#839 due to following test failures:
org.wso2.carbon.esb.mediator.test.enrich.EnrichIntegrationReplaceEnvelopeWithPropertyTestCase.setEnvironment
org.wso2.carbon.esb.mediator.test.enrich.EnrichIntegrationReplaceEnvelopTestCase.setEnvironment
org.wso2.carbon.esb.mediator.test.enrich.EnrichIntegrationReplaceEnvelopeTestCase.setEnvironment
=> Revert "ESBJAVA-3688 - Clean up Enrich Mediator"

components/mediation-ui/org.wso2.carbon.mediation.security.ui/src/main/resources/web/mediation_secure_vault/js/properties.js, components/mediation-ui/org.wso2.carbon.mediation.security.ui/src/main/resources/web/mediation_secure_vault/properties-ajaxprocessor.jsp, components/mediation-ui/org.wso2.carbon.proxyadmin.ui/src/main/resources/web/proxy/editCAppartifact.jsp, components/mediation-ui/org.wso2.carbon.proxyadmin.ui/src/main/resources/web/proxy/identifyCAppArtifact.jsp, components/mediation-ui/org.wso2.carbon.proxyadmin.ui/src/main/resources/web/proxyservices/index.jsp
There were several UI issues when creating custom proxies and using Secure vault password management. This PR has UI fixes for those issues.
=> UI improvements in EI Management console

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.script.ui/src/main/resources/web/script-mediator/edit-mediator.jsp
Fix https://github.com/wso2/product-ei/issues/908
=> Add language attribute for NashornJs in drop down

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.enrich.ui/src/main/java/org/wso2/carbon/mediator/enrich/ui/EnrichMediator.java
This fix was done as an UI improvement for the fix https://github.com/wso2/wso2-synapse/pull/794
=> Fix for clone attribute default behaviour

components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/java/org/wso2/carbon/endpoint/ui/endpoints/failover/FailoverEndpoint.java, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/java/org/wso2/carbon/endpoint/ui/endpoints/loadbalance/LoadBalanceEndpoint.java, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/org/wso2/carbon/endpoint/ui/i18n/Resources.properties, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/failoverEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/loadBalanceEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/updatePages/failoverEndpoint-update.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/updatePages/loadBalanceEndpoint-update.jsp
Reverts wso2/carbon-mediation#855
=> Revert "[EI-909] Add "buildMessage" attribute to management console"

features/synapse-features/org.apache.synapse.wso2.feature/pom.xml, pom.xml
Fixes https://github.com/wso2/product-ei/issues/854
=> EI-854: Upgrade Jayway jsonpath version

features/synapse-features/org.apache.synapse.wso2.feature/pom.xml, pom.xml
Reverts wso2/carbon-mediation#865
=> Revert "EI-854: Upgrade Jayway jsonpath version"

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSInjectHandler.java
Read JMSType for content-type only if "transport.jms.ContentTypeProperty" or "transport.jms.ContentType" is not specified.
Refer - https://wso2.org/jira/browse/ESBJAVA-5230
=> Fix ESBJAVA-5230

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/hl7/util/HL7MessageUtils.java
Start tenant flow and set the tenant domain to carbon context to avoid NullPoinerException at HL7 inbound.
Fixed: https://wso2.org/jira/browse/IDENTITY-5363 …
=> IDENTITY-5363: Start tenant flow to avoid Nullpointer at hl7 inbound

pom.xml
> Update synapse version to 2.1.7-wso2v26
=> Update synapse version to 2.1.7-wso2v26

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.conditionalrouter.ui/src/main/java/org/wso2/carbon/mediator/conditionalrouter/ConditionalRouterMediator.java
=> Remove unused imports

components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/SAPTransportSender.java
Fix compilation failure at SAPTransportSender …
=> Fix compilation failure at SAPTransportSender

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.store.ui/src/main/java/org/wso2/carbon/mediator/store/MessageStoreMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.store.ui/src/main/resources/org/wso2/carbon/mediator/store/ui/i18n/Resources.properties, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.store.ui/src/main/resources/web/store-mediator/edit-mediator.jsp, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.store.ui/src/main/resources/web/store-mediator/js/mediator-util.js, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.store.ui/src/main/resources/web/store-mediator/update-mediator.jsp
The UI for the feature of dynamically routing messages to messages stores. Basically the functionality for adding path expression from which the store name is derived from the message context, is given. 
https://redmine.wso2.com/issues/6630
=> Add support to accept expression in the Store Mediator

pom.xml
update the synpase version to latest released version
> Link(s) to product documentation that addresses the changes of this PR. …
=> update synapse version

components/mediation-admin/org.wso2.carbon.mediation.library/src/main/java/org/wso2/carbon/mediation/library/service/LibraryInfo.java
Remove duplicate methods which have no usages in carbon-mediation and product-ei.
=> Remove duplicate and unused methods

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQConnectionConsumer.java
Fix the issue of QoS not setting at the RabbitMQ consumer's channel when it is defined as a parameter in RabbitMQ inbound endpoint.
Fixed: wso2/product-ei#1342 …
=> EI_1342:Set prefetch count for RabbitMQ consumer channel

components/mediators/oauth/org.wso2.carbon.identity.oauth.mediator/src/main/java/org/wso2/carbon/identity/oauth/mediator/OAuthMediator.java
There is no need to validate empty tokens. https://github.com/wso2/carbon-mediation/issues/914
> Link(s) to product …
=> Improve OAuth2 token validation

components/mediators/oauth/org.wso2.carbon.identity.oauth.mediator/src/main/java/org/wso2/carbon/identity/oauth/mediator/OAuthMediator.java
=> Removing invaliad charactor

components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediator.java
This will fix the class cast exception due reported in https://github.com/wso2/product-ei/issues/1441
Fixing Class cast exception originated in Cache mediator. …
=> Fix Claascast exception in cache mediator

components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/bapi/util/RFCMetaDataParser.java
Support for tables in import parameter list.
=> Support for tables in import parameter list.

components/mediation-monitor/message-relay/org.wso2.carbon.relay/src/main/java/org/wso2/carbon/relay/ExpandingMessageFormatter.java, components/mediation-monitor/message-relay/org.wso2.carbon.relay/src/main/java/org/wso2/carbon/relay/StreamingOnRequestDataSource.java
> Resolves issue #905 
> Let ExpandingMessageFormatter can use StreamingOnRequestDataSource's inputstream not cachedData.
> StreamingOnRequestDataSource class's isConsumed method return lastUse.
So.. the original source's logic is..
if datasource is lastUsed.. then
set datasource to lastUse
end if
==> if true then set true.. 
I added else clause...
if datasource is lastUsed.. then
blah blah...
else
set datasource to lastUse
end if
=> resolve issue #905

components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/CipherInitializer.java, components/mediation-config-admin/org.wso2.carbon.mediation.configadmin/src/main/java/org/wso2/carbon/mediation/configadmin/util/XMLPrettyPrinter.java
=> [WIP] Fix for XML processing and OAEP 

pom.xml
> Update Synapse version dependancy to v2.1.7-wso2v34
=> Update Synapse version to v2.1.7-wso2v34

components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/config/inbound.properties
This PR removes transport.jms.SessionTransacted parameter from management console inbound EP edit page
Issue - https://github.com/wso2/product-ei/issues/1612 …
=> Remove transport.jms.SessionTransacted parameter from management console inbound EP edit page

components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/config/inbound.properties
Add cachelevel none(0) to JMS inbound Endpoint edit page in management console
Issue - https://github.com/wso2/product-ei/issues/1640
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
=> Add cachelevel none(0) to JMS inbound EP edit page

components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/config/inbound.properties
Add  java.naming.security.principal and java.naming.security.credentials parameter to JMS Inbound Endpoint edit page in Management console
Issue - https://wso2.org/jira/browse/ESBJAVA-4952
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
=> Add java.naming.security parameters to JMS IE editpage

components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CachableResponse.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheManager.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediator.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediatorFactory.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediatorSerializer.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CachingConstants.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/MediatorCacheInvalidator.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/MediatorCacheInvalidatorMBean.java
> Improve PR #843 based on comments
> Fix certain issues in the previous PR
> #843 
> #890
> java 8 | Ubuntu 17.10
=> Improve PR #843 based on comments

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.rule.ui/src/main/resources/web/rule-mediator/js/mediator-util.js, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.rule.ui/src/main/resources/web/rule-mediator/rulesript_editor-ajaxprocessor.jsp, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.throttle.ui/src/main/resources/web/throttle-mediator/js/mediator-util.js, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.throttle.ui/src/main/resources/web/throttling/trottle-policy-editor_ajaxprocessor.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/ajaxprocessors/errorCodeEditor-ajaxprocessor.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/js/endpoint-util.js, components/mediation-ui/org.wso2.carbon.mediation.templates.ui/src/main/resources/web/templates/js/ns-editor.js, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/js/ns-editor.js
> Fixes: https://github.com/wso2/product-ei/issues/1784
> Replace dialog div which is given by showPopupDialog method to fix issues in inlinepolicy editor, rule policy editor and errorcode editor.
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
> ‎JDK 8u121
=> Fix wso2/product-ei/issues/1784

components/application-deployers/org.wso2.carbon.application.deployer.synapse/src/main/java/org/wso2/carbon/application/deployer/synapse/SynapseAppDeployer.java
> Resolves https://github.com/wso2/product-ei/issues/1737
> The un-deployment of the artifacts in a cApp should be in a order.
> Artifacts in a cApp are deployed in a dependency order. The reverse of the same order is used for undeployment.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), …
=> Undeploy cApp in reverse dependency order: EI-1737

components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CachableResponse.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediator.java
Reverts wso2/carbon-mediation#961
=> Revert "Resolve wso2/product-ei#943"

components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/resources/web/sequences/source_sequence.jsp
Previsouly this was leading to the page of sequences
> Fix https://github.com/wso2/product-ei/issues/1813 
An UI fix
=> Fix https://github.com/wso2/product-ei/issues/1813

pom.xml
Update commons and synapse versions for EI Update 20 release
=> Update commons and synapse versions

components/mediation-ui/org.wso2.carbon.rest.api.ui/src/main/java/org/wso2/carbon/rest/api/ui/client/RestApiAdminClient.java
Enable CApp image and warning popup at API search.
Fixed https://github.com/wso2/product-ei/issues/1513
=> Fix product-ei#1513

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConnectionFactory.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketTransportSender.java
Add support to create and use web-socket API with secured endpoint.
Fix https://github.com/wso2/carbon-transports/issues/433
=> Fix https://github.com/wso2/carbon-transports/issues/433

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java
fix for https://github.com/wso2/carbon-mediation/issues/977 …
=> fix for https://github.com/wso2/carbon-mediation/issues/977

components/mediation-admin/org.wso2.carbon.endpoint/src/main/java/org/wso2/carbon/endpoint/service/EndpointAdmin.java, service-stubs/mediation-admin/org.wso2.carbon.endpoint.stub/src/main/resources/EndpointAdmin.wsdl
> Added the endpoint add/delete methods for tenant levels
=> Add Endpoint add/delete methods for tenant levels

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/pom.xml, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/pom.xml, features/mediator-features/datamapper-mediator/org.wso2.carbon.mediator.datamapper.engine.feature/pom.xml, features/synapse-features/org.apache.synapse.wso2.feature/pom.xml, pom.xml
fixes #946
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Upgrade some third party dependencies.

components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/docs/userguide.html, components/mediation-ui/org.wso2.carbon.message.store.ui/src/main/resources/web/message_store/docs/userguide.html
Current help page is redirected to an older ESB version.Updated it to refer to EI instead.
Public Fix: #1864
Curent 'help' page of Message Processor/Store are redirected to an old ESB page.Need to update the redirection to EI latest instead.
Updated the link to point to EI611 page.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=>  Fix userguide url for Message Processor/Store

pom.xml
This is to upgrade wso2-synapse version to 2.1.7-wso2v42 …
=> Upgrade wso2 synpase version to 2.1.7-wso2v42

components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/java/org/wso2/carbon/sequences/ui/util/XMLPrettyPrinter.java
Fix XXE vulnerability of DocumentBuilderFactory at XMLPrettyPrinter.
> Link(s) to product documentation that addresses the …
=> Fix XXE vulnerability

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/common/InboundRunner.java
> To Fix the NPE which occurs when clustering is disabled.
> Resolves wso2/product-ei#1923
> Added a null check
=> Fix NPE in Kafka inbound

components/mediation-cg/org.wso2.carbon.cloud.gateway/pom.xml, components/mediators/entitlement/org.wso2.carbon.identity.entitlement.mediator/pom.xml, components/mediators/oauth/org.wso2.carbon.identity.oauth.mediator/pom.xml, features/mediation-cg-features/org.wso2.carbon.cloud.gateway.server.feature/pom.xml, features/mediator-features/entitlement-mediator-feature/org.wso2.carbon.identity.entitlement.mediator.feature/pom.xml, features/mediator-features/oauth-mediator-feature/org.wso2.carbon.identity.oauth.mediator.feature/pom.xml, pom.xml
This is to upgrade kernel version, synapse version..etc. …
=> Upgrade versions in carbon-mediation

components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediator.java
The jenkins build is failing with following error. This PR is to fix it
[INFO] [ERROR] Exit code: 1 - /home/jenkins/workspace/platform-builds/carbon-mediation/components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediator.java:407: error: unmappable character for encoding ANSI_X3.4-1968
> Brief description of the new …
=> Fix java doc issue

components/mediation-ui/org.wso2.carbon.message.store.ui/src/main/resources/web/message_store/resequenceMessageStore.jsp
This PR disables password autocomplete in resequence message store …
=> Disable password autocomplete in resequence message store

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/pom.xml, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/pom.xml, features/mediator-features/datamapper-mediator/org.wso2.carbon.mediator.datamapper.engine.feature/pom.xml, features/synapse-features/org.apache.synapse.wso2.feature/pom.xml, pom.xml
This PR reverts some changes done related to Jackson in the following PR.
Reverts https://github.com/wso2/carbon-mediation/pull/947
Due to incompatible multiple jackson versions, carbon-data is having some issues.
=> Change Jackson versions

pom.xml
=> Synapse version upgrade

pom.xml
=> Update vfs commons version

pom.xml
Upgrade wso2-synapse version to 2.1.7-wso2v52 for weekly release.
> Link(s) to product documentation that addresses the changes …
=> Upgrade synapse version to 2.1.7-wso2v52

pom.xml
Change guave version to 18.0.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …
=> Change guava version

components/mediation-admin/org.wso2.carbon.mediation.templates/src/main/java/org/wso2/carbon/mediation/templates/services/TemplateEditorAdmin.java
> This PR prevents saving the template configuration in the file system when we enable statistics for the template which is deployed from the CAPP.
> Fix for: https://github.com/wso2/product-ei/issues/2081 …
=> Prevent saving the template artifact to file system

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/DataMapperMediator.java
Support xml to csv conversion with data-mapper for special characters such as `"&amp;"`, `"&lt;"`, etc.
Fix wso2/product-ei#2129 …
=> Fix product-ei#2129

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.store.ui/src/main/java/org/wso2/carbon/mediator/store/MessageStoreMediator.java
> Make hasBraces and removeBraces methods private
=> Make method-specific methods private

components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/index.jsp, components/mediation-ui/org.wso2.carbon.mediation.templates.ui/src/main/resources/web/templates/list_templates.jsp, components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/resources/web/sequences/list_sequences.jsp
This adds the secure attribute to SSL cookie in https context
> Link(s) to product documentation that addresses the changes of …
=> Set secure attribute in Encrypted Session Cookie

components/carbon-mediation-startup/org.wso2.carbon.mediation.startup/src/main/java/org/wso2/carbon/mediation/startup/util/ConfigHolder.java, components/mediation-admin/org.wso2.carbon.endpoint/src/main/java/org/wso2/carbon/endpoint/EndpointServiceComponent.java, components/mediation-admin/org.wso2.carbon.localentry/src/main/java/org/wso2/carbon/localentry/LocalEntryAdminServiceComponent.java, components/mediation-admin/org.wso2.carbon.mediation.library/src/main/java/org/wso2/carbon/mediation/library/MediationLibraryServiceComponent.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/SynapseSecurityerviceComponent.java, components/mediation-admin/org.wso2.carbon.mediation.templates/src/main/java/org/wso2/carbon/mediation/templates/internal/TemplateEditorServiceComponent.java, components/mediation-admin/org.wso2.carbon.message.processor/src/main/java/org/wso2/carbon/message/processor/MessageProcessorServiceComponent.java, components/mediation-admin/org.wso2.carbon.message.store/src/main/java/org/wso2/carbon/message/store/MessageStoreAdminServiceComponent.java, components/mediation-admin/org.wso2.carbon.priority.executors/src/main/java/org/wso2/carbon/priority/executors/PriorityServiceComponent.java, components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/APIServiceComponent.java, components/mediation-admin/org.wso2.carbon.sequences/src/main/java/org/wso2/carbon/sequences/internal/SequenceEditorServiceComponent.java, components/mediation-initializer/org.wso2.carbon.mediation.light.initializer/src/main/java/org/wso2/carbon/mediation/initializer/ServiceBusInitializer.java, components/mediation-initializer/org.wso2.carbon.mediation.light.initializer/src/main/java/org/wso2/carbon/mediation/initializer/configurations/ConfigurationManager.java, components/mediation-ntask/src/main/java/org/wso2/carbon/mediation/ntask/internal/NtaskService.java
=> Lightweight

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/pom.xml, components/mediation-cg/org.wso2.carbon.cloud.gateway.common/pom.xml, components/mediation-cg/org.wso2.carbon.cloud.gateway/pom.xml, components/mediation-connector/org.wso2.carbon.mediation.connector.as4/pom.xml, components/mediation-initializer/org.wso2.carbon.mediation.dependency.mgt/pom.xml, components/mediation-initializer/org.wso2.carbon.mediation.initializer/pom.xml, components/mediators/cache/org.wso2.carbon.mediator.cache/pom.xml, components/mediators/publishEvent/org.wso2.carbon.mediator.publishevent/pom.xml, features/mediation-cg-features/org.wso2.carbon.cloud.gateway.mediation.initializer.feature/pom.xml, features/mediation-cg-features/org.wso2.carbon.cloud.gateway.proxyadmin.ui.feature/pom.xml, pom.xml
=> Jacoco plugin integration

pom.xml
This is to upgrade
damnhandy-uri-template/2.1.6.wso2v1
joda-time/2.9.4.wso2v1
> Link to the PR for changes to the training …
=> Upgrade joda-time and uri-template versions

pom.xml
> Fix jacoco compatibility issue in jenkins
=> Jacoco Plugin Version Upgrade

pom.xml
Upgrade kernel version and synapse snapshot
=> Upgrade kernel version and synapse snapshot

pom.xml
=> Update http client version

pom.xml
> Upgrade analytics commons version
=> Upgrade analytics commons version

components/mediation-initializer/org.wso2.carbon.mediation.light.initializer/pom.xml, features/mediation-initializer-features/org.wso2.carbon.mediation.light.initializer.server.feature/pom.xml
=> Fix versions in light mediation

pom.xml
Upgrade osgi handy url template bundle. As handly url template is a osgi bundle we can directly use it. …
=> Upgrade osgi handy url template bundle

components/mediation-initializer/org.wso2.carbon.mediation.light.initializer/src/main/java/org/wso2/carbon/mediation/initializer/ServiceBusInitializer.java, features/mediation-initializer-features/org.wso2.carbon.mediation.light.initializer.server.feature/pom.xml
> Add mediation registry bundle and fix default configuration path
=> Add mediation registry bundle

features/synapse-features/org.apache.synapse.wso2.feature/pom.xml
Upgrade osgi handy url template bundle. As handly url template is a osgi bundle we can directly use it. …
=> Ugrade osgi handy url template bundle

features/synapse-features/org.apache.synapse.wso2.feature/pom.xml, pom.xml
Upgrading handy url template version …
=> Upgrading handy url template version

pom.xml
Update codec version to 1.1o to fix test failures
=> Update codec version to fix test failures

components/application-deployers/org.wso2.carbon.application.deployer.synapse/src/main/java/org/wso2/carbon/application/deployer/synapse/FileRegistryResourceDeployer.java
> Refactor FileRegistryDeployer adding functionality to deploy registry arrtifacts
=> Refactor FileRegistryDeployer

components/mediation-ui/org.wso2.carbon.proxyadmin.ui/src/main/resources/web/proxyservices/testConnection-ajaxprocessor.jsp, components/mediation-ui/org.wso2.carbon.task.ui/src/main/resources/web/task/savetask-ajaxprocessor.jsp
> Add encoding to variables used in JSP pages.
> Protect against XSS
> Add necessary encodings
=> Fix XSS vulnerability

components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/services/ConnectorService.java
=> Fix connectors in microesb

pom.xml
Update commons versions for the release.
=> Update commons versions

features/mediator-features/datamapper-mediator/org.wso2.carbon.mediator.datamapper.engine.feature/pom.xml, features/synapse-features/org.apache.synapse.wso2.feature/pom.xml, features/thirdpartylib-features/org.wso2.carbon.jackson.feature/pom.xml, features/thirdpartylib-features/pom.xml, pom.xml
Add feature to bundle jackson and other third-party libraries.
=> Add feature to bundle jackson

components/mediation-initializer/org.wso2.carbon.mediation.light.initializer/src/main/java/org/wso2/carbon/mediation/initializer/ServiceBusConstants.java, components/mediation-initializer/org.wso2.carbon.mediation.light.initializer/src/main/java/org/wso2/carbon/mediation/initializer/ServiceBusInitializer.java, components/mediation-initializer/org.wso2.carbon.mediation.light.initializer/src/main/java/org/wso2/carbon/mediation/initializer/utils/SynapseArtifactInitUtils.java
To disable connector enabling at startup set "esb.connector.startup.init.disable" to true
=> Add connector support for micro-integration profile

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/internal/MediationStatisticsComponent.java
=> Remove Registry dependency

features/mediation-ui-features/org.wso2.carbon.mediation.ui.feature/pom.xml
> Remove artifact deployment UI
=> Remove artifact deployment UI

components/mediation-initializer/org.wso2.carbon.mediation.light.initializer/src/main/java/org/wso2/carbon/mediation/initializer/utils/SynapseArtifactInitUtils.java
This is to validate the files inside the connector in the microIntegrator profile
> Link to the PR for changes to the training …
=> Validate the files inside the connector

components/business-adaptors/hl7/org.wso2.carbon.business.messaging.hl7.store/src/main/java/org/wso2/carbon/business/messaging/hl7/store/JDBCStore.java, components/business-adaptors/hl7/org.wso2.carbon.business.messaging.hl7.store/src/main/java/org/wso2/carbon/business/messaging/hl7/store/jpa/JPAStore.java, components/mediation-admin/org.wso2.carbon.message.store/src/main/java/org/wso2/carbon/message/store/service/MessageStoreAdminService.java, components/mediation-ui/org.wso2.carbon.message.store.ui/src/main/java/org/wso2/carbon/message/store/ui/utils/MessageStoreData.java
This will enable message store configuration parameters fetched from the registry.
> Please find the documentation for this in following [link](https://docs.google.com/document/d/1Q0NG-hYP9JeJpd-mrsxCaIwXf6ZVrj00d0WRV95lAuw/edit?usp=sharing)
> Link to the PR for changes to the …
=> [EI-2191]Fix message store parameters fetching from the registry

components/mediation-initializer/org.wso2.carbon.mediation.light.initializer/src/main/java/org/wso2/carbon/mediation/initializer/ServiceBusInitializer.java
=> Fix tenant id

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/securewebsocket/InboundSecureWebsocketListener.java
=> Secured websocket port offest fix

components/mediation-initializer/org.wso2.carbon.mediation.light.initializer/src/main/java/org/wso2/carbon/mediation/initializer/ServiceBusInitializer.java
=> Fix initialize task service

components/mediation-initializer/org.wso2.carbon.mediation.light.initializer/src/main/java/org/wso2/carbon/mediation/initializer/CarbonSynapseController.java, components/mediation-initializer/org.wso2.carbon.mediation.light.initializer/src/main/java/org/wso2/carbon/mediation/initializer/ServiceBusInitializer.java
=> Remove unwanted logs in Micro integrator

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/management/WebsocketEndpointManager.java
Since shutdownStatusCode is an optional param, checking it by default throws number format exception.
Fix https://github.com/wso2/product-apim/issues/3452
> Brief description of the new feature or bug fix as it will …
=> Fix shutdownStatusCode of WebSocket Inbound Endpoint work as optional parameter.

components/application-deployers/org.wso2.carbon.application.deployer.synapse/src/main/java/org/wso2/carbon/application/deployer/synapse/SynapseAppDeployer.java
=> Fix https://github.com/wso2/product-ei/issues/2288

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/hl7/util/HL7Configuration.java
Fix security issue of not closing the InputStream instance at loadProperties method.
> Link(s) to product documentation that …
=> Fix security issue

components/business-adaptors/hl7/org.wso2.carbon.business.messaging.hl7.store/src/main/java/org/wso2/carbon/business/messaging/hl7/store/JDBCStore.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/config/WorkerPoolConfiguration.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/configuration/NettyThreadPoolConfiguration.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/management/WebsocketEndpointManager.java
Fixed issues at closing sql statement and avoid object reference comparison at string inequality.
> Link(s) to product …
=> Fix security issues

components/mediation-ui/org.wso2.carbon.mediation.security.ui/src/main/java/org/wso2/carbon/mediation/security/vault/ui/PropertiesServiceClient.java, components/mediation-ui/org.wso2.carbon.mediation.security.ui/src/main/resources/web/mediation_secure_vault/js/properties.js
Enable configuring secure vault password length used via management console.
Fixed https://github.com/wso2/product-ei/issues/2396 …
=> Fix product-ei#2396

pom.xml
Update synapse dependency versions for release
=> Update synapse dependency versions

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.kerberos.ui/src/main/java/org/wso2/carbon/mediator/kerberos/KerberosMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.kerberos.ui/src/main/resources/org/wso2/carbon/mediator/kerberos/ui/i18n/Resources.properties, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.kerberos.ui/src/main/resources/web/kerberos-mediator/edit-mediator.jsp, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.kerberos.ui/src/main/resources/web/kerberos-mediator/js/mediator-util.js, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.kerberos.ui/src/main/resources/web/kerberos-mediator/update-mediator.jsp, components/mediators/kerberos/org.wso2.carbon.mediator.kerberos/src/main/java/org/wso2/carbon/mediator/kerberos/KerberosConstants.java, components/mediators/kerberos/org.wso2.carbon.mediator.kerberos/src/main/java/org/wso2/carbon/mediator/kerberos/KerberosMediator.java, components/mediators/kerberos/org.wso2.carbon.mediator.kerberos/src/main/java/org/wso2/carbon/mediator/kerberos/config/xml/KerberosMediatorFactory.java, components/mediators/kerberos/org.wso2.carbon.mediator.kerberos/src/main/java/org/wso2/carbon/mediator/kerberos/config/xml/KerberosMediatorSerializer.java
To read the following kerberos configuration file path from registry.
krb5Config
loginConfig
keytabPath 
Add an another option to read the file path as registry entry. …
=> Added to read the path of kerberos config file as registry entry

components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/SecureVaultConstants.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/SecureVaultLookupHandlerImpl.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/SecurityServiceHolder.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/SynapseSecurityerviceComponent.java, components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/ESBRegistry.java, components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/ESBRegistryConstants.java, components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/MicroIntegratorRegistry.java, components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/WSO2Registry.java, pom.xml
> Secure vault implementation does not support the micro integrator profile of the enterprise integrator and micro integrator registry does not support handling properties
> Support micro integrator in secure vault implementation and add enable the micro integrator registry to handle properties
> Properties can be added to the micro integrator registry by adding a file with the format, <_parent_dir_>.properties …
=> Add secure vault support for micro integrator profile

pom.xml
=> Upgrade kernel, synapse and commons versions

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.entitlement.ui/src/main/java/org/wso2/carbon/mediator/entitlement/EntitlementMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.entitlement.ui/src/main/resources/org/wso2/carbon/mediator/entitlement/ui/i18n/Resources.properties, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.entitlement.ui/src/main/resources/web/entitlement-mediator/edit-mediator.jsp, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.entitlement.ui/src/main/resources/web/entitlement-mediator/js/mediator-util.js, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.entitlement.ui/src/main/resources/web/entitlement-mediator/update-mediator.jsp, components/mediators/entitlement/org.wso2.carbon.identity.entitlement.mediator/src/main/java/org/wso2/carbon/identity/entitlement/mediator/EntitlementConstants.java, components/mediators/entitlement/org.wso2.carbon.identity.entitlement.mediator/src/main/java/org/wso2/carbon/identity/entitlement/mediator/EntitlementMediator.java, components/mediators/entitlement/org.wso2.carbon.identity.entitlement.mediator/src/main/java/org/wso2/carbon/identity/entitlement/mediator/config/xml/EntitlementMediatorFactory.java, components/mediators/entitlement/org.wso2.carbon.identity.entitlement.mediator/src/main/java/org/wso2/carbon/identity/entitlement/mediator/config/xml/EntitlementMediatorSerializer.java
This PR adds support for dynamic entitlement server configs through registry.
Issue - wso2/product-ei#2423  …
=>  Fix wso2/product-ei#2423 

components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/MicroIntegratorRegistry.java
> Fix file not found exception when searching for properties
```
[2018-09-14 12:12:17,068] [micro-integrator]  INFO - DependencyTracker Local entry : gov:datamapper/SimpleXMLtoXML_inputSchema.json was added to the Synapse configuration successfully
[2018-09-14 12:12:17,069] [micro-integrator] ERROR - MicroIntegratorRegistry Error in loading properties
java.io.FileNotFoundException: /Users/milindaperera/WSO2/Integration/RnD/GIT/product-ei/distribution/target/wso2ei-6.4.0-SNAPSHOT/wso2/micro-integrator/registry/governance/datamapper/SimpleXMLtoXML_inputSchema.json.properties (No such file or directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at …
```
=> Fix file not found exception when searching for properties

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/file/FileInjectHandler.java
> Resolves: wso2/product-ei#2737
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …
=> Fix for product-ei/issues/2737

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/file/FileInjectHandler.java
> Fixing the format issue
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Fixing the format issue

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/file/FileInjectHandler.java
> Changed the exception throwing in the finally. …
=> Logging the error

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/file/FileInjectHandler.java
> A null check is added
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Adding null check

components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/CarbonDestinationDataProvider.java, components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/SAPConstants.java
If we manually encrypt the password and if we gave it an alias and then encrypted value has been added to cipher-text.properties with that alias. If then change the password in the SAP client configuration file to that encrypted value, Couldn't connect to the SAP.
Related to: https://github.com/wso2/carbon-mediation/issues/1100
By initializing the secret resolver, resolve the encrypted value by checking the secret alias.
> Brief description of the new feature or bug fix …
=> Adding feature to support encrypted password in sap client conf file

components/mediation-admin/org.wso2.carbon.endpoint/pom.xml, components/mediation-admin/org.wso2.carbon.endpoint/src/main/java/org/wso2/carbon/endpoint/service/EndpointAdmin.java, components/mediation-admin/org.wso2.carbon.endpoint/src/main/java/org/wso2/carbon/endpoint/service/EndpointSynchronizeRequest.java
When endpoint is switched off from the manager node and if we access switched off endpoints via worker, still endpoints are responsive which is not the expected way.
The reason is that when we switched off the endpoint in Manager node, workers are not getting update about that state change.
Resolves wso2/product-ei#2797
Workers should get updated about that state change when endpoint is switched off.
Fix is when the Admin service is triggered to switch on/off the Endpoint(EndpoinAdmin) in the Manager node, now a cluster message(implemented a new message EndpointSynchronizeRequest) is dispatched to worker nodes after the switching on/off action is taken and once the worker nodes receive this message each node perform switching on/off function for the particular endpoint.
> Summary of user …
=> Add switch off endpoint propagation message#2797

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/file/FilePollingConsumer.java, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/config/inbound.properties, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/saveInbound.jsp, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/updateInbound-ajaxprocessor.jsp
> Fix wso2/product-ei#2809
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Fix for product-ei/issues/2809

pom.xml
Update dependency version of Synapse to fix build failure.
=> Update dependency version of Synapse

components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/config/inbound.properties, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/saveInbound.jsp, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/updateInbound-ajaxprocessor.jsp
> Fix issue : https://github.com/wso2/product-ei/issues/2836
=> Add 'db_url' parameter to JMS inbound endpoint UI

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.payloadfactory.ui/src/main/java/org/wso2/carbon/mediator/payloadfactory/PayloadFactoryMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.payloadfactory.ui/src/main/resources/org/wso2/carbon/mediator/payloadfactory/ui/i18n/JSResources.properties, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.payloadfactory.ui/src/main/resources/org/wso2/carbon/mediator/payloadfactory/ui/i18n/Resources.properties, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.payloadfactory.ui/src/main/resources/web/payloadfactory-mediator/edit-mediator.jsp, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.payloadfactory.ui/src/main/resources/web/payloadfactory-mediator/update-mediator.jsp
This add escapeXmlChars attribute to payload factory UI
Issue - wso2/product-ei#2810
=> Fix [EI] Add escapeXmlChars attribute to payload factory UI

components/mediation-ui/org.wso2.carbon.rest.api.ui/src/main/java/org/wso2/carbon/rest/api/ui/client/RestApiAdminClient.java
Fixes the issue in esb 5.0.0 API search (tracing and statistics shown as disabled when using the search function to locate an API).
=> Fix product-ei#2899

components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/pom.xml, pom.xml
The synapse version update to 2.1.7-wso2v84. It has some improvements for JSON support.
> Link(s) to product documentation that …
=> Update synapse version to 2.1.7-wso2v84

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/file/FilePollingConsumer.java
Handle issue with moving to SFTP after process and parse FileSystemOptions to VFSUtils in File Inbound.
Provide fix for : https://wso2.org/jira/browse/ESBJAVA-5317
Alter synapse VFSUtils to accept FileSystemOptions in certain methods
Also find the FileSystemOptions based on MoveAfterFailure path while doing so
* Construct a file inbound with FileURI with a SFTP location secured by a private-key & passphrase
* Construct a file inbound with FileURI a local file and MoveAfterFailure with a SFTP location secured by a private-key & passphrase
WSO2 EI - File Inbound Endpoint support SFTP with a private key and passphrase & also when MoveAfterFailure is SFTP
https://docs.wso2.com/display/EI630/File+Inbound+Protocol
When FileURI is local and MoveAfterProcess is remote
```
<inboundEndpoint …
```
=> Fix ESBJAVA-5317 - Handle issue with moving to SFTP after process and parse FileSystemOptions to VFSUtils in File Inbound

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.aggregate.ui/pom.xml, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.aggregate.ui/src/main/java/org/wso2/carbon/mediator/aggregate/AggregateMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.aggregate.ui/src/main/resources/web/aggregate-mediator/update-mediator.jsp, components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/java/org/wso2/carbon/sequences/ui/util/ns/SynapseJsonPathFactory.java
> Introduce functionality to aggregate JSON messages using a json-path expression
> We should be able to aggregate JSON messages using a JSON-path expression.
> Introduce JsonPath evaluation
> https://docs.wso2.com/display/EI640/Aggregate+Mediator
=> Add native JSON support for Aggregate mediator

pom.xml
Change synapse dependency version from 2.1.7-wso2v85 to 2.1.7-wso2v86 
> Link(s) to product documentation that addresses the …
=> Bump synapse version to 2.1.7-wso2v86

components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediator.java
Fixes the issue reported in https://github.com/wso2/product-apim/issues/4269
=> Fixing NPE in cache mediator when response has no content

components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/ESBRegistryConstants.java, components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/MicroIntegratorRegistry.java
=> Fix file path issue observed in DOS

components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/ESBRegistryConstants.java, components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/MicroIntegratorRegistry.java
Resolves https://github.com/wso2/product-ei/issues/3223
> Link(s) to product documentation that addresses the changes of this …
=> Correct registry resource URI to be a valid URI

components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/ESBRegistryConstants.java, components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/MicroIntegratorRegistry.java
Fix file separator in getPropertyFileURI which appends the properties file to resource URL.
> Link(s) to product documentation …
=> Fix file separator in getPropertyFileURI

features/synapse-features/org.apache.synapse.wso2.feature/pom.xml, pom.xml
This dependency was introduce in https://github.com/wso2/wso2-synapse/pull/1201/files
=> Pack commons-text dependency/

components/mediators/fastXSLT/org.wso2.carbon.mediator.fastXSLT/src/main/java/org/wso2/carbon/mediator/fastXSLT/FastXSLTMediator.java
builldMessage() --> buildMessage()
Related to /wso2/wso2-synapse/pull/1264
Fix the typo which is alreadu fixed in wso2-synapse
> …
=> Fix typo in Relayutils buildMessage

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/file/FileInjectHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/hl7/core/HL7Processor.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpServerWorker.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSInjectHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/kafka/KAFKAInjectHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/mqtt/MqttInjectHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQInjectHandler.java
Fix for https://github.com/wso2/product-ei/issues/2808
Ported fix of https://github.com/wso2-support/carbon-mediation/pull/196/files
=> Add isInbound property to all Inbound Endpoints

components/mediation-admin/org.wso2.carbon.mediation.library/pom.xml, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/MediationSecurityAdminService.java, pom.xml
>  import javax.activation to mediation.library through orbit bundle
>  remove sun.misc.BASE64Encoder in MediationSecurityAdminService
=> Add fixes to run with jdk11

components/business-adaptors/hl7/org.wso2.carbon.business.messaging.hl7.samples/pom.xml, components/event-sink/org.wso2.carbon.event.sink/pom.xml, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/pom.xml, components/mediation-admin/org.wso2.carbon.mediation.library/pom.xml, components/mediation-admin/org.wso2.carbon.proxyadmin.common/pom.xml, components/mediation-admin/org.wso2.carbon.proxyadmin/pom.xml, features/synapse-features/org.apache.synapse.wso2.feature/pom.xml, pom.xml
> To do the following:
1. Exclude log4j-over-slf4j
2. Bundle commons-text
3. Add javax.activation dependency …
=> Exclude log4j-over-slf4j, bundle commons-text and add javax.activation

components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediator.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediatorFactory.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediatorSerializer.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CachingConstants.java
This adds the cache mediator representation that is needed for supporting previous cache mediator implementation from EI Tooling.
Resolves https://github.com/wso2/product-ei/issues/3341
> Brief description of the new …
=> Fix product-ei#3341

components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/resources/web/sequences/js/registry-browser.js
Fix for [wso2/product-ei/issues/2693](https://github.com/wso2/product-ei/issues/2693#issue-361807583)
=> Fixing Governance Registry button not working after pressing "escape" button

pom.xml
Issue :- https://github.com/wso2/product-ei/issues/2061
=> Upgrade json-smart version to remove duplicate jars

pom.xml
=> Downgrade json-smart dependency

features/mediator-features/entitlement-mediator-feature/org.wso2.carbon.identity.entitlement.mediator.feature/pom.xml
This has been removed accidentally in https://github.com/wso2/carbon-mediation/pull/1151/files#diff-e5305edfec81f75295895c0e4894eb20L76
=> Add entitlement proxy

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConnectionFactory.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConstants.java
This PR fixes the issue https://github.com/wso2/product-apim/issues/4310
=> Use default websocket port in case port have not been defined in URL

components/mediators/entitlement/org.wso2.carbon.identity.entitlement.mediator/pom.xml, features/mediator-features/entitlement-mediator-feature/org.wso2.carbon.identity.entitlement.mediator.feature/pom.xml, pom.xml
Reverts wso2/carbon-mediation#1151
=> Revert "Move identity entitlement stub dependency to carbon commons"

features/mediator-features/entitlement-mediator-feature/org.wso2.carbon.identity.entitlement.mediator.feature/pom.xml, pom.xml
=> Upgrade gson version

components/mediation-ui/org.wso2.carbon.task.ui/src/main/resources/web/task/index.jsp
When you deploy an inbound endpoint and if there is no scheduled tasks are deployed, if you click on the Scheduled Tasks link (Home | > Manage | > Service Bus | > Scheduled Tasks) in the Mgt console panel, You will get an alert saying "null".
This fixes https://github.com/wso2/product-ei/issues/3429
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature …
=> Fix EI-3429: EI Scheduled Tasks UI gives null

pom.xml
Reverts wso2/carbon-mediation#1173
=> Revert "Bump carbon.kernel.version from 4.4.37 to 4.4.38"

components/mediation-ui/org.wso2.carbon.mediation.security.ui/src/main/resources/web/mediation_secure_vault/properties-ajaxprocessor.jsp
This PR contains the public fixes for some of the issues that have been identified in previous releases.
=> Public fixes for patches

features/thirdpartylib-features/org.wso2.carbon.jackson.feature/pom.xml, pom.xml
=> Bump dependency versions

components/mediation-monitor/message-relay/org.wso2.carbon.relay.mediators.builder/src/main/java/org/wso2/carbon/relay/mediators/builder/xml/BuilderMediatorFactory.java, components/mediation-monitor/message-relay/org.wso2.carbon.relay.mediators.builder/src/main/java/org/wso2/carbon/relay/mediators/builder/xml/BuilderMediatorSerializer.java, components/mediators/bam/org.wso2.carbon.mediator.bam/src/main/java/org/wso2/carbon/mediator/bam/xml/BamMediatorFactory.java, components/mediators/bam/org.wso2.carbon.mediator.bam/src/main/java/org/wso2/carbon/mediator/bam/xml/BamMediatorSerializer.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediatorFactory.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediatorSerializer.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/config/xml/DataMapperMediatorFactory.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/config/xml/DataMapperMediatorSerializer.java, components/mediators/entitlement/org.wso2.carbon.identity.entitlement.mediator/src/main/java/org/wso2/carbon/identity/entitlement/mediator/config/xml/EntitlementMediatorFactory.java, components/mediators/entitlement/org.wso2.carbon.identity.entitlement.mediator/src/main/java/org/wso2/carbon/identity/entitlement/mediator/config/xml/EntitlementMediatorSerializer.java, components/mediators/event/org.wso2.carbon.mediator.event/src/main/java/org/wso2/carbon/mediator/event/xml/EventMediatorFactory.java, components/mediators/event/org.wso2.carbon.mediator.event/src/main/java/org/wso2/carbon/mediator/event/xml/EventMediatorSerializer.java, components/mediators/fastXSLT/org.wso2.carbon.mediator.fastXSLT/src/main/java/org/wso2/carbon/mediator/fastXSLT/config/xml/FastXSLTMediatorFactory.java, components/mediators/fastXSLT/org.wso2.carbon.mediator.fastXSLT/src/main/java/org/wso2/carbon/mediator/fastXSLT/config/xml/FastXSLTMediatorSerializer.java, components/mediators/oauth/org.wso2.carbon.identity.oauth.mediator/src/main/java/org/wso2/carbon/identity/oauth/mediator/config/xml/OAuthMediatorFactory.java, components/mediators/oauth/org.wso2.carbon.identity.oauth.mediator/src/main/java/org/wso2/carbon/identity/oauth/mediator/config/xml/OAuthMediatorSerializer.java, components/mediators/publishEvent/org.wso2.carbon.mediator.publishevent/src/main/java/org/wso2/carbon/mediator/publishevent/PublishEventMediatorFactory.java, components/mediators/publishEvent/org.wso2.carbon.mediator.publishevent/src/main/java/org/wso2/carbon/mediator/publishevent/PublishEventMediatorSerializer.java, components/mediators/router/org.wso2.carbon.mediator.router.impl/src/main/java/org/wso2/carbon/mediators/router/impl/config/xml/RouterMediatorFactory.java, components/mediators/router/org.wso2.carbon.mediator.router.impl/src/main/java/org/wso2/carbon/mediators/router/impl/config/xml/RouterMediatorSerializer.java, components/mediators/smooks/org.wso2.carbon.mediator.smooks/src/main/java/org/wso2/carbon/mediator/transform/xml/SmooksMediatorFactory.java, components/mediators/smooks/org.wso2.carbon.mediator.smooks/src/main/java/org/wso2/carbon/mediator/transform/xml/SmooksMediatorSerializer.java
> Fixes the issue where it was not allowed to add comments inside a mediator in synapse
=> Fix inability to add comments inside mediators in synapse

components/business-adaptors/hl7/org.wso2.carbon.business.messaging.hl7.store/pom.xml, components/mediation-initializer/org.wso2.carbon.mediation.dependency.mgt/pom.xml, pom.xml
> To update eclipse.osgi version
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …
=> Changing openjpa version

pom.xml
Related to wso2/product-ei#2398.
Change rampart version to v28 to maintain uniform version
> Link(s) to product documentation …
=> downgrade rampart version

components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediatorFactory.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CachingConstants.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/digest/HttpRequestHashGenerator.java
Resolves /wso2/product-ei/issues/3627
"activityid" is a new header introduced which has a dynamic value for each request, hence this needs to be excluded in the hashing for the cache mediator to work
> Brief …
=> Exclude activityid header from cache mediator hashing method

pom.xml
=> upgrade synapse dependency

components/org.wso2.carbon.integrator.core/src/main/java/org/wso2/carbon/integrator/core/handler/IntegratorStatefulHandler.java
Fix: [wso2/product-ei#3619](https://github.com/wso2/product-ei/issues/3619)
=> Fix setting messageType to null at IntegratorStatfulHandler

components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/SAPTransportSender.java, components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/bapi/util/RFCMetaDataParser.java
This is to provide support to pass the parameter WAIT with a value when the BAPI_TRANSACTION_COMMIT commit is called.
Fixes https://github.com/wso2/product-ei/issues/3674 …
=> Fix EI-3674: BAPI_TRANSACTION_COMMIT with WAIT parameter

components/mediation-admin/org.wso2.carbon.message.processor/src/main/java/org/wso2/carbon/message/processor/service/MessageProcessorAdminService.java, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/java/org/wso2/carbon/message/processor/ui/MessageProcessorAdminServiceClient.java, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/manageMessage.jsp, service-stubs/mediation-admin/org.wso2.carbon.message.processor.stub/src/main/resources/MessageProcessorAdminService.wsdl
- Changed e.browseMessage() to e.getMessage()
- Changed popMessage() and popAndRedirect() to return boolean for better Assertion during testing
Fixes issue :  https://github.com/wso2/product-ei/issues/3670
=> Fix for manageMessage.jsp exception error

components/mediation-initializer/org.wso2.carbon.mediation.light.initializer/src/main/java/org/wso2/carbon/mediation/initializer/ServiceBusInitializer.java
Fixing the compliation issue due to missing import …
=> Fix import

pom.xml
=> Update json schema validator all version

.gitignore, components/business-adaptors/sap/pom.xml, components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/CarbonDestinationDataProvider.java, components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/SAPEndpoint.java, components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/SAPTransportSender.java, components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/bapi/util/RFCMetaDataParser.java, features/business-adaptors/org.wso2.carbon.sap.feature/pom.xml, pom.xml
Following are the improvements done to the SAP adaptor.
1. Modification of the SAP component to be built with the profile 'jenkins'. The component will not be built when the generic profile is built.
2. Modification of the SAP feature to pack the component with the ${carbon.mediation} version only when the profile 'jenkins' is run. For all the other times, it will pack the component version defined by the property, 'org.wso2.carbon.transports.sap.import.version' in the root pom.xml
3. Porting of fixes done for released version.
4. Code refactoring.
Resolves: https://github.com/wso2/product-ei/issues/870
=> WSO2 Adaptor for SAP improvements

pom.xml
=> Upgrading synapse version

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/mapper/XSLTMappingResource.java
> Enforce secure xml processing
=> datamapper-mediator: fix improper restriction of XXE

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/input/readers/XMLInputReader.java
When using the datamapper mediator with XML data, the "contract" must fit with what is defined in the input schema of the datamapper configuration. If the XML from the message context has XML tags that are not specified in the schema, the following warning will be shown :
```[2019-04-16 16:17:41,945] []  WARN - XMLInputReader Element name not found : montest```
An then, the following exception will be thrown :
```
[2019-04-16 16:17:41,946] [] ERROR - DataMapperMediator DataMapper mediator : mapping failed
Input type is incorrect or Invalid element found in the message payload : montest
at org.wso2.carbon.mediator.datamapper.engine.input.readers.XMLInputReader.xmlTraverse(XMLInputReader.java:174)
at org.wso2.carbon.mediator.datamapper.engine.input.readers.XMLInputReader.xmlTraverse(XMLInput …
```
=> Allow extensible data contracts as input in the datamapper mediator

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/Constants.java
As this is conflicting with axis 2 server port
=> Change Internal API default Port

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.prometheus.publisher/src/main/java/org/wso2/carbon/prometheus/publisher/service/MetricResource.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.prometheus.publisher/src/main/java/org/wso2/carbon/prometheus/publisher/util/PrometheusPublisherConstants.java
Fixes https://github.com/wso2/micro-integrator/issues/147
We can pass the system property **enablePrometheusApi** as
--DenablePrometheusApi to enable prometheus backend.
=> Facilitate enabling Prometheus stats with a system property

components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/resources/web/sequences/design_sequence.jsp, components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/resources/web/sequences/source_sequence.jsp
Resolves https://github.com/wso2/product-ei/issues/3844
In a recent PR wso2/carbon-mediation#1146, a parameter called "seqEditor" is checked to create the respective EditorUIClientFactory (Sequence or Template). When calling other jsp pages, this parameter is not properly passed, hence when switching back this parameter is lost.
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or …
=> Fix template and sequence UI issue in management console

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.prometheus.publisher/src/main/java/org/wso2/carbon/prometheus/publisher/service/MetricResource.java
Since this is internally checked
https://github.com/wso2/carbon-mediation/pull/1235
> Link(s) to product documentation that …
=> Remove checking system property in  Prometheus API

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/java/internal/http/api/DispatcherTestCase.java
doen with https://github.com/wso2/carbon-mediation/pull/1235
> Link(s) to product documentation that addresses the changes of …
=> Add system property to enable Internal API

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/management/HTTPEndpointManager.java
=> Check whether Internal API list is not empty

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/EndpointListenerLoader.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/management/HTTPEndpointManager.java
=> Set port offset while initializing the port itself

pom.xml
=> Upgrade synapse

components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/sourceView.jsp
Fix for https://github.com/wso2/product-ei/issues/3899
=> add endpoint name for key field  in save in registry form

components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/MicroIntegratorRegistry.java
Resolves https://github.com/wso2/micro-integrator/issues/175
Since micro-integrator registry is different from WSO2 registry, it does not have all the metadata related to the registry files. In Script mediator, it requires a [DataHandler](https://github.com/wso2/wso2-synapse/blob/master/modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediator.java#L494) which in turn requires [media type](https://github.com/wso2/carbon-mediation/blob/master/components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/WSO2Registry.java#L704) of the uploaded registry file. As a temporary fix, we need to map all the file extensions with Content-Type so that we can retrieve the media-type in runtime by looking at the file extension. …
=> Add file Extension to mediaType mapping in MI Registry

components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/ESBRegistryConstants.java, components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/MicroIntegratorRegistry.java
In a earlier [PR](https://github.com/wso2/carbon-mediation/pull/1247), when comparing strings "==" was used instead of ".equals()"
> Brief description of the new feature or bug fix as it will appear in the release …
=> Refactor string assertion in Micro Integrator Registry

pom.xml
=> Upgrade OAuth dependency

components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/resources/web/sequences/design_sequence.jsp, components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/resources/web/sequences/source_sequence.jsp
Reverts wso2/carbon-mediation#1237
=> Revert "Fix template and sequence UI issue in management console"

components/application-mgt/org.wso2.carbon.application.mgt.synapse.ui/pom.xml, components/application-mgt/org.wso2.carbon.application.mgt.synapse.ui/src/main/resources/org/wso2/carbon/application/mgt/synapse/ui/i18n/Resources.properties, components/application-mgt/org.wso2.carbon.application.mgt.synapse.ui/src/main/resources/web/synapse-apps/index.jsp, components/application-mgt/org.wso2.carbon.application.mgt.synapse/src/main/java/org/wso2/carbon/application/mgt/synapse/SynapseApplicationAdmin.java, components/application-mgt/org.wso2.carbon.application.mgt.synapse/src/main/java/org/wso2/carbon/application/mgt/synapse/SynapseApplicationMetadata.java, components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/java/org/wso2/carbon/sequences/ui/util/SequenceEditorHelper.java, components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/resources/web/sequences/design_sequence.jsp, components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/resources/web/sequences/local_registry-ajaxprocessor.jsp, components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/resources/web/sequences/registry_sequence.jsp, components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/resources/web/sequences/save_sequence.jsp, components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/resources/web/sequences/save_sequence_as.jsp, components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/resources/web/sequences/source_sequence.jsp, components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/resources/web/sequences/stat_tracing-ajaxprocessor.jsp, service-stubs/application-mgt/org.wso2.carbon.application.mgt.synapse.stub/src/main/resources/SynapseApplicationAdmin.wsdl
Reverts wso2/carbon-mediation#1146
=> Revert "List Templates in CAPP"

components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/MicroIntegratorRegistry.java
Resolves https://github.com/wso2/product-ei/issues/4007
Datamapper files should be read as "plain/text". This PR fixes a regression issue which comes from a [previous fix](https://github.com/wso2/micro-integrator/pull/177) done to MicroIntegratorRegistry.
> Summary of …
=> Remove invalid media-type of datamapper from Registry initiation

components/mediation-admin/org.wso2.carbon.endpoint/src/main/java/org/wso2/carbon/endpoint/service/EndpointAdmin.java
Check existing Entry when adding a new Endpoint.
Fixes: https://github.com/wso2/product-apim/issues/4501
=>  Add check to the entry when adding an Endpoint. 

components/mediation-admin/org.wso2.carbon.localentry/src/main/java/org/wso2/carbon/localentry/service/LocalEntryAdmin.java, service-stubs/mediation-admin/org.wso2.carbon.localentry.stub/src/main/resources/LocalEntry.wsdl
> Add methods to the LocalEntryAdmin service for tenant specific scenarios while calling the admin service with the super tenant credentials
=> Add tenant wise implementation for LocalEntryAdmin service

components/mediation-ui/org.wso2.carbon.rest.api.ui/src/main/java/org/wso2/carbon/rest/api/ui/client/RestApiAdminClient.java
Fixes: https://github.com/wso2/product-ei/issues/4058
=> Fix wso2/product-ei/issues/4058

components/business-adaptors/pom.xml
This is omitted since we need sap resources to build this. 
If you need to build the component, place the sab jars (  sapidoc3.jar and sapjco3.jar ) in sap/lib directory and build making the following changes in pom.xml.
```
<profiles>
<profile>
<id>default</id>
<activation>
<activeByDefault>true</activeByDefault>
</activation>
<properties>
<packaging.type>bundle</packaging.type>
</properties>
<build>
<plugins>
<plugin>
<artifactId>maven-antrun-plugin</artifactId>
<executions>
<execution>
<goals>
<goal>run</goal>
</goals>
<phase>compile</phase>
<configuration>
<tasks>
<taskdef resource="net/sf/antcontrib/antcontrib.properties" classpathref="maven.plugin.classpath" />
<echo message="SAPJCo available" />
<echo message="Building SAP Adapter" />
<mkdir dir="${basedir}/target" />
<mkdir …
```
=> Skip building sap component in the default profile

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/InternalAPIDispatcher.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/java/internal/http/api/DispatcherTestCase.java, pom.xml
Map the query parameters to message context properties in the [InternalApiDispatcher](https://github.com/wso2/carbon-mediation/blob/master/components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/InternalAPIDispatcher.java) using the method in [RESTUtils](https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/rest/RESTUtils.java#L100)
The user can easily use the message context properties to get the query parameters
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste …
=>  Assign message properties for query params in internal inbound endpoints

components/business-adaptors/hl7/org.wso2.carbon.business.messaging.hl7.store/pom.xml, pom.xml
=> Update Dependency version

components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/CarbonDestinationDataProvider.java, pom.xml
- Change the org.wso2.securevault version to 1.1.2
- Resolve the secrets usingMiscellaneousUtil.resolve() method.
- Depends on secure-vault jar update.
=> Add secure vault changes.

components/transport-netty-axis2-bridge/pom.xml, components/transport-netty-axis2-bridge/src/main/java/org/wso2/transports/http/bridge/BridgeConstants.java, components/transport-netty-axis2-bridge/src/main/java/org/wso2/transports/http/bridge/internal/NettyAxis2BridgeComponent.java, components/transport-netty-axis2-bridge/src/main/java/org/wso2/transports/http/bridge/listener/Axis2HttpTransportListener.java, components/transport-netty-axis2-bridge/src/main/java/org/wso2/transports/http/bridge/listener/ConnectorListenerToAxisBridge.java, components/transport-netty-axis2-bridge/src/main/java/org/wso2/transports/http/bridge/listener/HttpRequestWorker.java, components/transport-netty-axis2-bridge/src/main/java/org/wso2/transports/http/bridge/listener/RequestUtils.java, components/transport-netty-axis2-bridge/src/main/java/org/wso2/transports/http/bridge/sender/AxisToClientConnectorBridge.java, components/transport-netty-axis2-bridge/src/main/java/org/wso2/transports/http/bridge/sender/HttpResponseWorker.java, components/transport-netty-axis2-bridge/src/main/java/org/wso2/transports/http/bridge/sender/ResponseListener.java, components/transport-netty-axis2-bridge/src/main/java/org/wso2/transports/http/bridge/util/DeferredMessageBuilder.java, components/transport-netty-axis2-bridge/src/main/java/org/wso2/transports/http/bridge/util/MessageUtils.java
Get axis2 message formatters to format the message.
Change packaging of netty axis2 bridge to bundle.
Clean up code.
=> Netty axis2 bridge improvements

components/mediation-initializer/org.wso2.carbon.mediation.initializer/src/main/java/org/wso2/carbon/mediation/initializer/ServiceBusInitializer.java, pom.xml
=> Fix felix build failure for JDK 11

features/synapse-features/org.apache.synapse.wso2.feature/pom.xml, pom.xml
commons-text is packed from kernel.
=> Remove packing commons-text from mediation

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.enrich.ui/src/main/java/org/wso2/carbon/mediator/enrich/ui/EnrichMediatorUtil.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.enrich.ui/src/main/java/org/wso2/carbon/mediator/enrich/ui/EnrichUIConstants.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.enrich.ui/src/main/resources/web/enrich-mediator/update-mediator.jsp
>Refactor changes introduced in wso2/carbon-mediation/pull/1239 …
=> Refactor changes for Enrich mediator UI

components/mediation-ui/org.wso2.carbon.rest.api.ui/pom.xml, components/mediation-ui/org.wso2.carbon.rest.api.ui/src/test/java/org/wso2/carbon/rest/api/ui/client/RestApiAdminClientTest.java, components/mediation-ui/org.wso2.carbon.rest.api.ui/src/test/resources/axis2/axis2.xml, pom.xml
Adds test case for https://github.com/wso2/product-ei/issues/4058 and https://github.com/wso2/product-ei/issues/4375
=> Add test for WSDLEPRPrefix in API

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/ConfigurationLoader.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/InternalAPI.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/InternalAPIDispatcher.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/InternalAPIHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpServerWorker.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/java/internal/http/api/SampleInternalAPI.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.prometheus.publisher/src/main/java/org/wso2/carbon/prometheus/publisher/service/MetricAPI.java
> This adds handlers to internal Api interface and these handlers will be invoked dispatching the requests
=>  Adds handlers to internalApi

pom.xml
> Upgrade synapse version to 2.1.7-wso2v115
=> Upgrade synapse version to 2.1.7-wso2v115

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQInjectHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQMessage.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQUtils.java
Add properties like RABBITMQ_REPLY_TO into Transport Headers
in RabbitMQ inbound endpoint message context.
Fixes: https://github.com/wso2/product-ei/issues/4432
=> Fix wso2/product-ei/issues/4432

.travis.yml
=> Update travis with openjdk8

components/mediation-admin/org.wso2.carbon.task.services/src/main/java/org/wso2/carbon/task/internal/TaskServiceRegistrarComponent.java, components/mediation-config-admin/org.wso2.carbon.mediation.configadmin/src/main/java/org/wso2/carbon/mediation/configadmin/ConfigAdminServiceComponent.java
change conflicted service component naming
=> change conflicted service component naming

components/carbon-mediation-startup/org.wso2.carbon.mediation.startup/src/main/java/org/wso2/carbon/mediation/startup/internal/StartupAdminServiceComponent.java, components/mediation-admin/org.wso2.carbon.localentry/src/main/java/org/wso2/carbon/localentry/LocalEntryAdminServiceComponent.java, components/mediation-admin/org.wso2.carbon.proxyadmin/src/main/java/org/wso2/carbon/proxyadmin/ProxyAdminServiceComponent.java, components/mediation-admin/org.wso2.carbon.task.services/pom.xml, components/mediation-admin/org.wso2.carbon.task.services/src/main/java/org/wso2/carbon/task/services/internal/TaskServiceRegistrarComponent.java, components/mediation-admin/org.wso2.carbon.task/pom.xml, components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/persistence/PersistenceManager.java
=> fix startup issues

features/application-mgt/org.wso2.carbon.application.mgt.synapse.feature/pom.xml, features/event-sink/org.wso2.carbon.event.sink.feature/pom.xml, features/inbound-endpoints/org.wso2.carbon.inbound.endpoints.feature/pom.xml, features/mediation-cg-features/org.wso2.carbon.cloud.gateway.agent.feature/pom.xml, features/mediation-cg-features/org.wso2.carbon.cloud.gateway.agent.ui.feature/pom.xml, features/mediation-cg-features/org.wso2.carbon.cloud.gateway.feature/pom.xml, features/mediation-cg-features/org.wso2.carbon.cloud.gateway.mediation.initializer.feature/pom.xml, features/mediation-initializer-features/org.wso2.carbon.mediation.initializer.feature/pom.xml, features/mediation-initializer-features/org.wso2.carbon.mediation.initializer.ui.feature/pom.xml, features/mediation-ui-features/org.wso2.carbon.mediation.ui.feature/pom.xml, features/mediator-features/bam-mediator/org.wso2.carbon.mediator.bam.feature/pom.xml, features/mediator-features/cache-mediator/org.wso2.carbon.mediator.cache.feature/pom.xml, features/mediator-features/datamapper-mediator/org.wso2.carbon.mediator.datamapper.feature/pom.xml, features/mediator-features/kerberos-mediator-feature/org.wso2.carbon.mediator.kerberos.feature/pom.xml, features/mediator-features/publishEvent-mediator/org.wso2.carbon.mediator.publishevent.feature/pom.xml, features/scheduled-tasks/org.wso2.carbon.task.feature/pom.xml, features/scheduled-tasks/org.wso2.carbon.task.ui.feature/pom.xml, pom.xml
Fix kernel version to 4.5.0 range
=> Fix kernel version range

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConstants.java
Correction of default WSS port when the port is not defined.
=> Correct default WSS port

.travis.yml
Fix travis log limit problem by removing unnecessary log messages.
=> Fix travis log limit issue

components/mediation-ui/org.wso2.carbon.mediation.templates.ui/src/main/resources/web/templates/list_templates.jsp, components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/resources/web/sequences/design_sequence.jsp
Fix JSP page loading issue due to tomcat upgrade.
=> Fix jsp page loading issue

components/business-adaptors/hl7/org.wso2.carbon.business.messaging.hl7.store.ui/pom.xml, components/business-adaptors/hl7/org.wso2.carbon.business.messaging.hl7.store/src/main/java/org/wso2/carbon/business/messaging/hl7/store/internal/HL7StoreAdminServiceComponent.java, components/mediation-admin/org.wso2.carbon.message.store/src/main/java/org/wso2/carbon/message/store/MessageStoreAdminServiceComponent.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.kerberos.ui/pom.xml, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.kerberos.ui/src/main/java/org/wso2/carbon/mediator/kerberos/ui/KerberosMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.kerberos.ui/src/main/java/org/wso2/carbon/mediator/kerberos/ui/KerberosMediatorService.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.kerberos.ui/src/main/java/org/wso2/carbon/mediator/kerberos/ui/internal/KerberosMediatorActivator.java
Remove duplicate definition of OSGi component.
Move OSGi loaders into internal packages
=> Fix duplicate class loader issues

components/business-adaptors/hl7/org.wso2.carbon.business.messaging.hl7.message/pom.xml, components/business-adaptors/hl7/org.wso2.carbon.business.messaging.hl7.transport/pom.xml, components/carbon-mediation-startup/org.wso2.carbon.mediation.startup/pom.xml, components/event-sink/org.wso2.carbon.event.sink/pom.xml, components/mediation-admin/org.wso2.carbon.mediation.security/pom.xml, components/mediation-admin/org.wso2.carbon.message.processor/pom.xml, components/mediation-cg/org.wso2.carbon.cloud.gateway.agent/pom.xml, components/mediation-cg/org.wso2.carbon.cloud.gateway/pom.xml, components/mediation-initializer/org.wso2.carbon.mediation.dependency.mgt/pom.xml, components/mediation-initializer/org.wso2.carbon.mediation.initializer/pom.xml, components/mediation-ntask/pom.xml, components/mediation-throttle/pom.xml, components/mediators/bam/org.wso2.carbon.mediator.bam.config/pom.xml, pom.xml
=> update osgi service package import

components/application-deployers/org.wso2.carbon.application.deployer.synapse/src/main/resources/required-features.xml
> Change synapse feature version range according to the mediation feature migration
=> Change synapse feature version range

components/mediation-initializer/org.wso2.carbon.mediation.initializer/src/main/java/org/wso2/carbon/mediation/initializer/ServiceBusUtils.java, pom.xml
Fix null pointer issue while deactivating synapse components
=> Fix null pointer issue for deactivate

components/mediation-ui/org.wso2.carbon.rest.api.ui/src/main/resources/web/api/index.jsp
Refactoring the API Overview view.
=> Refactor API Overview view

components/mediators/smooks/org.wso2.carbon.mediator.smooks/pom.xml, components/mediators/smooks/org.wso2.carbon.mediator.smooks/src/main/java/org/wso2/carbon/mediator/transform/SmooksMediator.java, pom.xml
> $subject to remove dependency org.wso2.carbon.mediator.service as it is not packed in MI.
=> Refactor smooks to throw synapse exception

components/mediation-commons/pom.xml
=> Fix mediation-common pom structure

components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/updatePages/sourceViewSubmit-ajaxprocessor.jsp
> Encode the values of the input
=> Encode the values

pom.xml
> Bump synapse version to wso2v123
=> Bump synapse version to wso2v123

components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/java/org/wso2/carbon/endpoint/ui/util/EndpointConfigurationHelper.java, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/js/endpoint-util.js
Testing endpoints now displays a general Error message in cases where a
general exception is caught.
Resolves Issue : https://github.com/wso2/product-ei/issues/4585
=> Changed how endpoint test displays Error Messages

components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/manageMessageSamplingProcessor.jsp
=> Add max.store.connection.attempts support in message sampling processor

pom.xml
=> Update synapse and carbon-commons versions

components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/manageMessageSamplingProcessor.jsp
Issue - https://github.com/wso2/micro-integrator/issues/1004
Reverts wso2/carbon-mediation#1328
=> Fix https://github.com/wso2/micro-integrator/issues/1004

features/mediation-ui-features/org.wso2.carbon.mediation.ui.feature/pom.xml
This PR will remove Priority Executor from EI management console(UI).
Fix issue: https://github.com/wso2/product-ei/issues/4745
=> Remove Priority Executor from management console

components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/SAPTransportSender.java, components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/bapi/util/RFCMetaDataParser.java
=> Improve BAPI message transformation

components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/bapi/util/RFCMetaDataParser.java
Remove duplicate method definition
=> Remove duplicate method definition

components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/updatePages/sourceViewSubmit-ajaxprocessor.jsp
Disable unauthenticated access when updating message processor configurations from the source view in the management console
=> Disable unauthenticated access to management console

pom.xml
Update synapse version for release
=> Update synapse version for release

components/mediation-connector/org.wso2.carbon.mediation.connectors/src/main/resources/archetype-resources/pom.xml, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.iterate.ui/src/main/java/org/wso2/carbon/mediator/iterate/IterateMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.iterate.ui/src/main/resources/web/iterate-mediator/update-mediator.jsp
Fixes https://github.com/wso2/product-ei/issues/4016
Bring jsonpath support for iterate mediator in management console
=> Add jsonpath support for iterate mediator in management console

components/mediation-admin/org.wso2.carbon.endpoint/src/main/java/org/wso2/carbon/endpoint/service/EndpointAdmin.java, components/mediation-admin/org.wso2.carbon.localentry/src/main/java/org/wso2/carbon/localentry/service/LocalEntryAdmin.java
Add Endpoint existence and Local Entry Existence check methods
=> Add Endpoint existence and Local Entry Existence check methods

components/mediation-admin/org.wso2.carbon.endpoint/src/main/java/org/wso2/carbon/endpoint/service/EndpointAdmin.java, components/mediation-admin/org.wso2.carbon.localentry/src/main/java/org/wso2/carbon/localentry/service/LocalEntryAdmin.java
Reverts wso2/carbon-mediation#1347
=> Revert "Add Endpoint existence and Local Entry Existence check methods"

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.fault.ui/src/main/java/org/wso2/carbon/mediator/fault/ui/util/FaultUtil.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.fault.ui/src/main/resources/web/makefault-mediator/edit-mediator.jsp
> Add expression support in the management console
to the details section of the Fault mediator.
Fixes https://github.com/wso2/product-ei/issues/3898
=> Fix wso2/product-ei/issues/3898

components/mediation-monitor/message-relay/org.wso2.carbon.relay.mediators.builder/src/main/java/org/wso2/carbon/relay/mediators/builder/xml/BuilderMediatorFactory.java, components/mediation-monitor/message-relay/org.wso2.carbon.relay.mediators.builder/src/main/java/org/wso2/carbon/relay/mediators/builder/xml/BuilderMediatorSerializer.java, components/mediators/bam/org.wso2.carbon.mediator.bam/src/main/java/org/wso2/carbon/mediator/bam/xml/BamMediatorFactory.java, components/mediators/bam/org.wso2.carbon.mediator.bam/src/main/java/org/wso2/carbon/mediator/bam/xml/BamMediatorSerializer.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediatorFactory.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediatorSerializer.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/config/xml/DataMapperMediatorFactory.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/config/xml/DataMapperMediatorSerializer.java, components/mediators/entitlement/org.wso2.carbon.identity.entitlement.mediator/src/main/java/org/wso2/carbon/identity/entitlement/mediator/config/xml/EntitlementMediatorFactory.java, components/mediators/entitlement/org.wso2.carbon.identity.entitlement.mediator/src/main/java/org/wso2/carbon/identity/entitlement/mediator/config/xml/EntitlementMediatorSerializer.java, components/mediators/event/org.wso2.carbon.mediator.event/src/main/java/org/wso2/carbon/mediator/event/xml/EventMediatorFactory.java, components/mediators/event/org.wso2.carbon.mediator.event/src/main/java/org/wso2/carbon/mediator/event/xml/EventMediatorSerializer.java, components/mediators/fastXSLT/org.wso2.carbon.mediator.fastXSLT/src/main/java/org/wso2/carbon/mediator/fastXSLT/config/xml/FastXSLTMediatorFactory.java, components/mediators/fastXSLT/org.wso2.carbon.mediator.fastXSLT/src/main/java/org/wso2/carbon/mediator/fastXSLT/config/xml/FastXSLTMediatorSerializer.java, components/mediators/oauth/org.wso2.carbon.identity.oauth.mediator/src/main/java/org/wso2/carbon/identity/oauth/mediator/config/xml/OAuthMediatorFactory.java, components/mediators/oauth/org.wso2.carbon.identity.oauth.mediator/src/main/java/org/wso2/carbon/identity/oauth/mediator/config/xml/OAuthMediatorSerializer.java, components/mediators/publishEvent/org.wso2.carbon.mediator.publishevent/src/main/java/org/wso2/carbon/mediator/publishevent/PublishEventMediatorFactory.java, components/mediators/publishEvent/org.wso2.carbon.mediator.publishevent/src/main/java/org/wso2/carbon/mediator/publishevent/PublishEventMediatorSerializer.java, components/mediators/router/org.wso2.carbon.mediator.router.impl/src/main/java/org/wso2/carbon/mediators/router/impl/config/xml/RouterMediatorFactory.java, components/mediators/router/org.wso2.carbon.mediator.router.impl/src/main/java/org/wso2/carbon/mediators/router/impl/config/xml/RouterMediatorSerializer.java, components/mediators/smooks/org.wso2.carbon.mediator.smooks/src/main/java/org/wso2/carbon/mediator/transform/xml/SmooksMediatorFactory.java, components/mediators/smooks/org.wso2.carbon.mediator.smooks/src/main/java/org/wso2/carbon/mediator/transform/xml/SmooksMediatorSerializer.java
> Remove unnecessary new lines
=> Refactor code

pom.xml
Update carbon commons related dependency versions
=> Update carbon commons related dependency versions

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.jsontransform.ui/pom.xml
Update snapshot version in JsonTransform UI pom
=> Update snapshot version in JsonTransform UI pom

pom.xml
> This PR will update the synapse dependency version.
=> Update synapse dependency version

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/file/FileInjectHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/hl7/core/HL7Processor.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpServerWorker.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSInjectHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/kafka/KAFKAInjectHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQInjectHandler.java
Added `artifact_name` property for inbound endpoints. 
To be merged after https://github.com/wso2/wso2-synapse/pull/1460
https://github.com/wso2/product-ei/issues/4828
=> Added artifact_name property for inbound endpoints

pom.xml
=> Bump kernel version range

components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/SecureVaultConstants.java
Fix regisrty init for mediation securevault (manage passwords)
Issue: https://github.com/wso2/product-ei/issues/4867
=> Fix regisrty init for mediation securevault

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.aggregate.ui/src/main/java/org/wso2/carbon/mediator/aggregate/AggregateMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.aggregate.ui/src/main/resources/web/aggregate-mediator/update-mediator.jsp, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.enrich.ui/src/main/java/org/wso2/carbon/mediator/enrich/ui/EnrichMediatorUtil.java, components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/java/org/wso2/carbon/sequences/ui/util/ns/SynapseJsonPathFactory.java
> Add json-path support for aggregate and enrich mediators
=> Add json-path support in management console.

components/mediation-ui/org.wso2.carbon.proxyadmin.ui/src/main/resources/web/proxyservices/index.jsp
> Fix encoding user inputs when rendering in the UI
=> Fix encoding user inputs when rendering in the UI

components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/forms/wsdlEndpoint-form.jsp
=> Fix minor UI issue

components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/newInbound1.jsp, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/saveInbound.jsp
=> Fix ui issue in inbound.jsp

components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/FileSecretRepository.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/SecretCipherHander.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/SecretSrcData.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/SecureVaultConstants.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/SecureVaultLookupHandler.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/SecureVaultLookupHandlerImpl.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/VaultType.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/xpath/VaultLookupFunction.java, pom.xml
Support to resolve secrets from flat files in wso2:vault-lookup
Issue: https://github.com/wso2/product-ei/issues/4883
=> Support to resolve secrets from flat files

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/services/MessageFlowReporterThread.java
Prevent publishing mediation flow statistics when only OpenTracing is active
=> Prevent publishing mediation flow statistics when only OpenTracing is active

.travis.yml, features/business-adaptors/org.wso2.carbon.sap.feature/pom.xml, pom.xml
> Removed build-helper maven plugin
Removed takiri maven plugin from travis
=> Replaced build-helper plugin with RELEASE keyward

components/mediation-ui/org.wso2.carbon.rest.api.ui/src/main/resources/web/api/sourceview_api.jsp
> This PR fixes the Cross-Site Scripting vulnerability found in sourceview_api.jsp page in Management Console.
=> Fix Cross-Site Scripting vulnerability in sourceview_api.jsp page

features/mediator-features/entitlement-mediator-feature/org.wso2.carbon.identity.entitlement.mediator.feature/pom.xml, pom.xml
> Add missing dependencies to xacml feature.
Fixes wso2/product-ei/issues/4935
=> Add missing dependencies to xacml feature.

components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/addressEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/defaultEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/failoverEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/httpEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/loadBalanceEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/recipientlistEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/templateEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/wsdlEndpoint.jsp
The purpose of this PR is to fix identified CSRF vulnerabilities.
=> Fix csrf vulnerability

components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/addressEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/defaultEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/failoverEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/httpEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/loadBalanceEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/recipientlistEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/templateEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/wsdlEndpoint.jsp
Fix management console form issue
=> Fix management console form issue

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConstants.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketTransportSender.java
> Fixed Fixed https://github.com/wso2/product-apim/issues/7318
=> Fixed https://github.com/wso2/product-apim/issues/7318

components/mediation-ui/org.wso2.carbon.proxyadmin.ui/src/main/resources/web/proxyservices/template_wsdl-based.jsp
> This PR fixes the Cross-Site Scripting vulnerability found in template_wsdl-based.jsp page by encoding request parameter.
=> Fix Cross-Site Scripting vulnerability in template_wsdl-based.jsp

components/mediation-ui/org.wso2.carbon.rest.api.ui/src/main/resources/web/api/index.jsp
> Remove unwanted check for CAPPs to enable swagger and swagger-tryit
URLs for APIs deployed from CAPPs.
Fixes wso2/product-ei/issues/4949
=> Enable swagger and swagger-tryit URLs for CAPP APIs.

components/application-deployers/org.wso2.carbon.application.deployer.synapse/src/main/java/org/wso2/carbon/application/deployer/synapse/SynapseAppDeployer.java
When a class mediator is deployed using a CAPP and an API that uses this class mediator is deployed using the same CAPP, when undeploying the CAPP it fails to undeploy the API which uses the class mediator. It properly removes the CAPP from the management console but the API is not getting removed from the management console and throws a class not found error when trying to undeploy the API. This happens only when deploying class mediator using CAPP. Fix this by adding necessary class loaders as a property.
Fixes: https://github.com/wso2/product-ei/issues/4995
=>  Fix wso2/product-ei/issues/4995

pom.xml
Update synapse.version and orbit.version.axis2
=> Update synapse and axis2 versions

components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/CarbonServerConfig.java, components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/ServerConfig.java, components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/pom.xml, components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/src/main/java/org/wso2/carbon/mediation/transport/handlers/requestprocessors/swagger/format/CarbonServerConfig.java, components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/src/main/java/org/wso2/carbon/mediation/transport/handlers/requestprocessors/swagger/format/SwaggerGenerator.java, components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/src/main/java/org/wso2/carbon/mediation/transport/handlers/requestprocessors/swagger/format/SwaggerJsonProcessor.java, components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/src/main/java/org/wso2/carbon/mediation/transport/handlers/requestprocessors/swagger/format/SwaggerYamlProcessor.java, components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/src/main/java/org/wso2/carbon/mediation/transport/handlers/requestprocessors/swagger/format/utils/SwaggerProcessorConstants.java, components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/src/main/java/org/wso2/carbon/mediation/transport/handlers/requestprocessors/swagger/format/utils/SwaggerUtils.java, features/mediation-initializer-features/org.wso2.carbon.mediation.initializer.server.feature/pom.xml, pom.xml
> Added new util to fetch from registry / generate swagger.
Add functionality to create swagger from AxisResourceMap of a data
service
Change swagger JSON / YAML processors to support data-services
Fixes wso2/product-ei/issues/4999
=> Change swagger processors to support data-services

pom.xml
> Upgrade synapse version to 2.1.7-wso2v151
=> Upgrade synapse version 2.1.7-wso2v151

pom.xml
> Upgrade synapse version to 2.1.7-wso2v153
=> Upgrade synapse version to 2.1.7-wso2v153

components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/service/RestApiAdmin.java, components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/APIGenerator.java, components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/GenericApiObjectDefinition.java, components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/SwaggerConstants.java
> Update carbon mediation for swagger generation from Integration Studio.
=> Swagger generation changes for Integration Studio

components/mediation-initializer/org.wso2.carbon.mediation.initializer/src/main/java/org/wso2/carbon/mediation/initializer/multitenancy/TenantServiceBusInitializer.java, pom.xml
fix wso2/product-apim#7986
front porting: https://github.com/wso2-support/carbon-mediation/pull/368
Fix overriding tenants synapse.xml when loading tenant
=> [Front Porting][APIM] Fix overriding tenants synapse.xml when loading tenant

pom.xml
> Upgrade axis2 and synapse versions
=> Upgrade axis2 and synapse versions

pom.xml
Upgrade synapse dependency version
=> Upgrade synapse dependency version

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpSourceHandler.java
Related to wso2/product-ei#4717
Implemented with wso2/wso2-synapse#1478
Please merge this PR after wso2/wso2-synapse#1478 is merged and the relevant synapse version is used.
=> Increment graceful shutdown metric in HTTP Inbound EP

components/org.wso2.carbon.integrator.core/src/main/java/org/wso2/carbon/integrator/core/handler/IntegratorSynapseHandler.java, pom.xml
Fixes https://github.com/wso2/micro-integrator/issues/1647
=> Format logs with service name

components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/APIGenerator.java
When generating a Synapse API from swagger definition, previously, for each path we create only one resource and if there to be multiple methods in a single path, all the methods are added to that resource.
Now we generate a resource of each method in a path (A resource for each path, method combination).
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/1009
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review …
=> Synapse API Generation: Creating a resource for each method

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/pom.xml, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/pom.xml, features/thirdpartylib-features/org.wso2.carbon.jackson.feature/pom.xml, pom.xml
This PR will upgrade jackson dependency from 2.9.8 to 2.10.3.
=> Upgrade jackson dependency

pom.xml
Upgrade jackson-dataformat-yaml dependency from 2.9.9 to 2.10.3
=> Upgrade jackson-dataformat-yaml dependency

pom.xml
=> Upgrade wss4j dependency

pom.xml
=> Upgrade netty dependency

pom.xml
Upgrade synapse and axis2 versions
=> Upgrade synapse and axis2 versions

components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/APIGenerator.java
>Fix: https://github.com/wso2/devstudio-tooling-ei/issues/1050
=> Fix issue while creating two or more API resources with no url mapping

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebSocketClientHandler.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketTransportSender.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/utils/LogUtil.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketResponseSender.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/WebsocketLogUtil.java
This includes the detailed logs for WebSocket including WebSocket headers and WebSocket frames.
It is required to add the following entries to the log4j.properties file in order to view these logs.
```
log4j.logger.org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketSourceHandler=DEBUG
log4j.logger.org.wso2.carbon.inbound.endpoint.protocol.websocket.InboundWebsocketResponseSender=DEBUG
log4j.logger.org.wso2.carbon.websocket.transport.WebSocketClientHandler=DEBUG
log4j.logger.org.wso2.carbon.websocket.transport.WebsocketTransportSender=DEBUG
```
Please note that the outbound HTTP requests from the gateway (both occasions; from gateway to client and gateway to backend) during the WebSocket connection establishment are not logged in this case as it is handled via a netty …
=> Provide debug logs for websocket frame/http message level communication

components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/GenericApiObjectDefinition.java
Fixes: https://github.com/wso2/micro-integrator/issues/1599
=> Fix: https://github.com/wso2/micro-integrator/issues/1599

pom.xml
Upgrade commons collection dependency
=> Upgrade commons collection dependency

components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/APIGenerator.java
When generating synapse API given the old synapse API and the swagger definition,
1. when there are multiple resources (for different methods) with the same path, the configuration of all such resources gets replaced by the first resource.
2. If there are resources in the old API with multiple methods, they get split into individual resources.
Fix:
1. Update the new API with the appropriate resource (matching both path and the methods) instead of the first resource matching the path.
2. Avoid splitting resources for each method by checking it from the old synapse API.
=> Fix sequence losing when generating synapse API from swagger

components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/connection/Connection.java, components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/connection/ConnectionHandler.java, components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/exception/ContentBuilderException.java, components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/pool/Configuration.java, components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/pool/ConnectionFactory.java, components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/pool/ConnectionPool.java, components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/util/PayloadUtils.java, components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/util/ResponseHandler.java
> Add connection handling for connectors and add connection pool implementation
> A map will be maintained against the <connector_name>:<connection_name> to uniquely identify each connection where the map may hold either a connection or a connection pool as per requirement.
=> Add connection handling for connectors

components/mediation-ui/org.wso2.carbon.proxyadmin.ui/src/main/resources/web/proxyservices/index.jsp
> Fixes: https://github.com/wso2/product-ei/issues/5159 …
=> Validate and encode rule property values

components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediator.java
> Fixes: https://github.com/wso2/product-ei/issues/5167 …
=> Check JsonInputStream for json payload

components/mediators/publishEvent/org.wso2.carbon.mediator.publishevent/src/main/java/org/wso2/carbon/mediator/publishevent/PublishEventMediator.java
Resolves wso2/product-ei#5146
When an event is published in the fault sequence, using the PublishEventMediator, 'Event sink not found' error was observed. This commit fixes this bug.
=> Fix wso2/product-ei#5146

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/factory/JMSConnectionFactory.java
=> Include exception object to the error log

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.kerberos.ui/pom.xml, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.kerberos.ui/src/main/resources/web/kerberos-mediator/edit-mediator.jsp, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.kerberos.ui/src/main/resources/web/kerberos-mediator/update-mediator.jsp
This PR fixes the issue in adding Kerberos mediator through the management console. The issue was of a regression for the fix wso2/carbon-mediation#1303
Fixes wso2/product-ei#5151
=> Fix issue in adding Kerberos mediator using Management Console

components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/util/ConnectorUtils.java, components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/util/Constants.java
> Abstract connection pool parameter reading to the connector core.
Once the generic connection pool is introduced to connectors, reading the connection pool configuration from template parameters is a common function for all the connectors. Hence, it is abstracted to connector utils.
=> Abstract connection pool parameter reading

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSInjectHandler.java
> Fixes: https://github.com/wso2/product-ei/issues/5182 …
=> Add JMS_TIMESTAMP into transport headers

components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/config/inbound.properties
=> Enable sftp parameters in management console

components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/manageMessageForwardingProcessor.jsp
> Fixes: https://github.com/wso2/product-ei/issues/2273 …
=> Fix the issue with fail messages store

components/business-adaptors/hl7/org.wso2.carbon.business.messaging.hl7.store/src/main/java/org/wso2/carbon/business/messaging/hl7/store/jpa/JPAConsumer.java
Related PR https://github.com/wso2/wso2-synapse/pull/1585/commits/24d5b39ffb697ef7f5d5dfcddd828d69ea9bef93
=> Implement setALive method

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.aggregate.ui/src/main/java/org/wso2/carbon/mediator/aggregate/AggregateMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.aggregate.ui/src/main/resources/org/wso2/carbon/mediator/aggregate/ui/i18n/Resources.properties, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.aggregate.ui/src/main/resources/web/aggregate-mediator/edit-mediator.jsp, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.aggregate.ui/src/main/resources/web/aggregate-mediator/update-mediator.jsp
Add aggregateElementType field for Aggregate mediator in the management
console.
- Unit tests 
> Code coverage information
> Details about the test cases and coverage
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
> Provide high-level details about the samples related to this feature
> List any other related PRs
> Describe migration steps and platforms on which migration has been tested
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
> Describe the research phase and any blog …
=> Add aggregateElementType to the management console

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.enrich.ui/src/main/resources/org/wso2/carbon/mediator/enrich/ui/i18n/Resources.properties, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.enrich.ui/src/main/resources/web/enrich-mediator/edit-mediator.jsp
> Introduce remove action to Enrich mediator in management console.
Fixes wso2/product-ei/issues/5199
=> Introduce remove action to Enrich mediator.

components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/RefreshAccessToken.java
$Subject in RefreshAccessToken.java to fix https://github.com/wso2/micro-integrator/issues/1904
=> Remove unnecessary log

features/inbound-endpoints/org.wso2.carbon.inbound.endpoints.server.feature/pom.xml, features/mediator-features/entitlement-mediator-feature/org.wso2.carbon.identity.entitlement.mediator.feature/pom.xml, pom.xml
Fix feature installation failure due to missing dependencies netty-resolver and javax.annotation-api
Respective pom files have been updated to fix the issue …
=> Fix feature installation faliure due to missing dependencies

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/AcknowledgementMode.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQConsumer.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQInjectHandler.java
A new property call `SET_REQUEUE_ON_ROLLBACK` will introduce to address the problem stated in the issue. Once it set in the fault sequence in the error cases, the RabbitMQ inbound will reject the message with the requeue flag to true. It leads to resend the message back to the consumer **without delay**. Also, **the loop will continue until the message is acknowledged successfully**. 
Resolves https://github.com/wso2/product-ei/issues/5207
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the …
=> Add support for basicReject with requeue flag true in the RabbitMQ inbound

components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/java/org/wso2/carbon/endpoint/ui/util/EndpointConfigurationHelper.java
> Fixes: https://github.com/wso2/product-ei/issues/5209 …
=> Remove '?wsdl' suffix from testing URL in the error message

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpSourceHandler.java
Fixes: https://github.com/wso2/product-ei/issues/5101
=> Fix: https://github.com/wso2/product-ei/issues/5101

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/common/InboundRequestProcessorImpl.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/file/FilePollingConsumer.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/file/VFSProcessor.java
The PR fixed the issue of continuous retrying after undeploying the inbound endpoint upon connection error.
Resolves https://github.com/wso2/product-ei/issues/5269
> Brief description of the new feature or bug fix as …
=> Fix file inbound undeploying issue while connection error

components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/MediationSecurityAdminService.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/external/hashicorp/HashiCorpVaultConstant.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/external/hashicorp/HashiCorpVaultLookupHandlerImpl.java, service-stubs/mediation-admin/org.wso2.carbon.mediation.security.stub/src/main/resources/MediationSecurityAdminService.wsdl
$subject
Fixes wso2/product-ei#5280
=> Add app-role pull authentication support for HashiCorp integration

components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/external/hashicorp/HashiCorpVaultLookupHandlerImpl.java
Fixes https://github.com/wso2/product-ei/issues/5298
=> Fix HashiCorp vault app role authentication namespace issue

components/org.wso2.carbon.integrator.core/pom.xml
=> Fix odata passthough issue due to felix version

components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/connection/Connection.java, components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/connection/ConnectionConfig.java, components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/connection/ConnectionHandler.java
Fix: https://github.com/wso2/micro-integrator/issues/2010
=> [Fix MI-2010] Update connector core to close connections gracefully

components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/GenerateAccessToken.java, components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/util/ConnectorUtils.java
> Fixes: https://github.com/wso2/product-ei/issues/5263 …
=> Add client_credentials flow and generalize the code

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/input/readers/JSONInputReader.java
> Resolves: https://github.com/wso2/product-ei/issues/5319 …
=> Ignore the exception message while throwing custom exception and log it

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/executors/ScriptExecutor.java
> Fix issue: wso2/product-ei#5290
=> Fix issue with hyphens replacing encoded char in datamapper

pom.xml
=> Change synapse version

pom.xml
Updating Smooks version to resolve build failures in MI
=> Update Smooks version to 1.5.1.wso2v4 

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/executors/ScriptExecutor.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/mapper/JSFunction.java
> This PR will compile the data mapper scripts before executing them in the mediation flow. Also, the input data is fed to the data mapper script using js bindings for the nashorn engine. The following graph describes the performance gain which is roughly 20x when mapping using data mapper.
=> Optimize Datamapper code to use pre-compiled scripts and bindings

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketTransportSender.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/WebsocketLogUtil.java
Fix https://github.com/wso2/product-apim/issues/9213
=> Websocket log improvement

pom.xml
=> Upgrade httpclient dependency version

pom.xml
Reverts wso2/carbon-mediation#1486
=> Revert "Upgrade httpclient dependency version"

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/executors/ScriptExecutor.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/mapper/JSFunction.java
Reverts wso2/carbon-mediation#1484
=> Revert "Optimize Datamapper code to use pre-compiled scripts and bindings"

components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/service/RestApiAdmin.java, components/mediation-admin/org.wso2.carbon.rest.api/src/test/java/org/wso2/carbon/rest/api/RestApiAdminUnitTest.java, components/mediation-admin/org.wso2.carbon.rest.api/src/test/resources/ChangeApiSwagger.json, components/mediation-admin/org.wso2.carbon.rest.api/src/test/resources/SwaggerWithContext.json, components/mediation-admin/org.wso2.carbon.rest.api/src/test/resources/SwaggerWithUrl.json, components/mediation-admin/org.wso2.carbon.rest.api/src/test/resources/TestAllApiChangedSwagger.json, components/mediation-admin/org.wso2.carbon.rest.api/src/test/resources/TestAllApiSwagger.yaml, components/mediation-admin/org.wso2.carbon.rest.api/src/test/resources/TestSwagger.yaml, components/mediation-admin/org.wso2.carbon.rest.api/src/test/resources/firstApi.xml, components/mediation-admin/org.wso2.carbon.rest.api/src/test/resources/firstApiChanged.xml, components/mediation-admin/org.wso2.carbon.rest.api/src/test/resources/secondApi.xml, components/mediation-admin/org.wso2.carbon.rest.api/src/test/resources/testAllApiChanged.xml, components/mediation-commons/pom.xml, components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/APIGenerator.java, components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/GenericApiObjectDefinition.java, components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/OpenAPIProcessor.java, components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/SwaggerConstants.java, components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/pom.xml, components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/src/main/java/org/wso2/carbon/mediation/transport/handlers/requestprocessors/swagger/format/SwaggerJsonProcessor.java, components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/src/main/java/org/wso2/carbon/mediation/transport/handlers/requestprocessors/swagger/format/SwaggerYamlProcessor.java, components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/src/main/java/org/wso2/carbon/mediation/transport/handlers/requestprocessors/swagger/format/utils/SwaggerUtils.java, features/mediation-initializer-features/org.wso2.carbon.mediation.initializer.server.feature/pom.xml, pom.xml
> Add API -> OpenApi 3.0 and Dataservice -> OpenApi 3.0 support
Fixes wso2/micro-integrator/issues/2043
=> Add OpenAPI 3.0 support to API and Dataservices

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/executors/ScriptExecutor.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/mapper/JSFunction.java
Reverts wso2/carbon-mediation#1500
=> Revert "Revert "Optimize Datamapper code to use pre-compiled scripts and bindings""

pom.xml
Upgrade httpcomponent versions
=> Upgrade httpcomponent dependencies

components/mediation-commons/pom.xml, components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/pom.xml, features/mediation-initializer-features/org.wso2.carbon.mediation.initializer.server.feature/pom.xml, pom.xml
> Use swagger-parser orbit bundle instead of using individual
dependencies.
=> Use swagger-parser orbit bundle.

components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/service/RestApiAdmin.java, components/mediation-admin/org.wso2.carbon.rest.api/src/test/java/org/wso2/carbon/rest/api/RestApiAdminUnitTest.java
> Add update name in swagger functionality.
Add related test cases.
=> Add update name in swagger functionality.

components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CachableResponse.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediator.java
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: 
Fixes wso2/product-apim#9865 …
=> Fix case sensitive header issue in cache mediator

components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/service/RestApiAdmin.java, components/mediation-admin/org.wso2.carbon.rest.api/src/test/java/org/wso2/carbon/rest/api/RestApiAdminUnitTest.java, components/mediation-admin/org.wso2.carbon.rest.api/src/test/resources/TestAllApiChangedSwaggerRelativePath.json, components/mediation-admin/org.wso2.carbon.rest.api/src/test/resources/TestAllApiSwaggerRelativeUrl.yaml, components/mediation-admin/org.wso2.carbon.rest.api/src/test/resources/TestSwaggerRelativeUrl.yaml, components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/APIGenerator.java, components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/OpenAPIProcessor.java
>Add relative URL support to OAS 3.0 feature.
Updated tests.
=> Add relative URL support to swagger.

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/internal/MediationStatisticsComponent.java
Fixing the memory leak in MediationStatisticsComponent and SynapseConfiguration.
Fixing: https://github.com/wso2/product-ei/issues/5349
=> Fix the memory leak in MediationStatisticsComponent

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpServerWorker.java
This is to initiate the tenant flow in HTTP inbound endpoint
=> Initiate tenant flow in HTTP inbound endpoint

components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/service/RestApiAdmin.java
=> add method to retrieve Synapase content

.github/workflows/coverage.yml
=> add continue-on-error true for coverage workflow

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/pom.xml
Fixes: https://github.com/wso2/product-ei/issues/5377 …
=> Fix noclassdef issue for inboundendpoints

components/mediators/fastXSLT/org.wso2.carbon.mediator.fastXSLT/src/main/java/org/wso2/carbon/mediator/fastXSLT/FastXSLTMediator.java
Fixes: https://github.com/wso2-support/carbon-mediation/pull/523
=> Fix FastXSLT with appending original message content to response

components/mediation-admin/org.wso2.carbon.rest.api/src/test/java/org/wso2/carbon/rest/api/RestApiAdminUnitTest.java, components/mediation-admin/org.wso2.carbon.rest.api/src/test/resources/TestSwagger2.yaml, components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/APIGenerator.java, components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/SwaggerConstants.java
> Add default and templated server string support for creating APIs from
OAS 3.0 definitions.
Fixes wso2/integration-studio/issues/656
=> Add templated server string support.

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/management/HTTPEndpointManager.java
This is to fix https://github.com/wso2/micro-integrator/issues/2163 : Adding HTTPS inbound endpoint in tenant mode with same port as in super tenant gives an error
=> Fix EI-2163

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/executors/ScriptExecutor.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/mapper/MappingResource.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/DataMapperMediator.java
> Limit DM JS pre-compile process to a single thread to eliminate race
conditions.
Fixes wso2/product-ei/issues/5384
=> Limit DM JS pre-compile process to a single thread

components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/APIGenerator.java
> Add default context support to swagger.
Related to wso2/integration-studio/issues/656
=> Add default context support.

components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/digest/HttpRequestHashGenerator.java
=> Fix null handling of http headers

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java
This PR fixes the websocket error log when a port offset is configured.
Fixes https://github.com/wso2/product-apim/issues/9220
=> Fix websocket port offset issue

components/mediation-admin/org.wso2.carbon.mediation.library/src/main/java/org/wso2/carbon/mediation/library/service/MediationLibraryAdminService.java, components/mediation-admin/org.wso2.carbon.mediation.templates/src/main/java/org/wso2/carbon/mediation/templates/services/TemplateEditorAdmin.java, components/mediation-admin/org.wso2.carbon.proxyadmin/src/main/java/org/wso2/carbon/proxyadmin/service/ProxyServiceAdmin.java, components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/service/RestApiAdmin.java, components/mediation-admin/org.wso2.carbon.sequences/src/main/java/org/wso2/carbon/sequences/services/SequenceAdmin.java
Resolves wso2/product-ei#5358
Merge this after https://github.com/wso2/wso2-synapse/pull/1737 is merged and relavant synapse version is upgraded
=> Fix connector deployment issue in Multitenant environments

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/management/WebsocketEndpointManager.java
Fixes https://github.com/wso2/product-apim/issues/10172
=> Fix APIM-10172: Exception in server shutdown

pom.xml
=> Upgrade synpase version

pom.xml
=> Upgrade Synapse Version

pom.xml
=> Upgrade synapse and kernel version

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketResponseSender.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/WebsocketLogUtil.java
This support is added by https://github.com/wso2/carbon-mediation/pull/1408 but this fix is not working in log4j2 due to class mismatch.
This PR is to fix https://github.com/wso2/product-apim/issues/9213
> Brief …
=> Fix APIM:9213 Adding debug logs for websocket inbound endpoint

pom.xml
- Upgrade synapse version to 2.1.7-wso2v227
- Downgrade axis2 version to 1.6.1-wso2v63
> Link(s) to product documentation that …
=> Changing dependency versions

components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/java/org/wso2/carbon/endpoint/ui/endpoints/http/HttpEndpoint.java, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/forms/httpEndpoint-form.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/updatePages/httpEndpoint-update.jsp
> Add OAuth support for HTTP endpoints in the management console.
Fixes wso2/product-ei/issues/5422
=> Add OAuth support in management console.

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/file/FilePollingConsumer.java
=> Escape meta characters in File Inbound URI

components/mediation-ntask/src/main/java/org/wso2/carbon/mediation/ntask/NTaskTaskManager.java
=> Fix always picking the super_tenant id when eager loading is enabled

components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/digest/REQUESTHASHGenerator.java
Fixes wso2/product-apim#11382
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …
=> Exclude activityid header from cache mediator hashing method in REQUESTHASHGenerator

components/mediation-ui/org.wso2.carbon.mediation.artifactuploader.ui/src/main/resources/web/artifactuploader/index.jsp, components/mediation-ui/org.wso2.carbon.mediation.artifactuploader.ui/src/main/resources/web/artifactuploader/remove-artifact-ajaxprocessor.jsp
=> Add minor UI fix

components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/WSO2Registry.java
Fixes https://github.com/wso2/product-apim/issues/11525  …
=> Add null check for resource properties

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/hl7/codec/HL7Codec.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/hl7/management/HL7EndpointManager.java
=> Fix HL7 buffer reader issue

components/mediation-admin/org.wso2.carbon.proxyadmin/src/main/java/org/wso2/carbon/proxyadmin/observer/ProxyObserver.java
Port https://github.com/wso2-support/carbon-mediation/pull/624
Fix wso2/product-ei#5497
=> Update proxy service status when deactivate/activate service from management console

pom.xml
=> Upgrade netty & json-smart components

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java
Fix: https://github.com/wso2/product-apim/issues/11157 …
=> Fixing issue in wss API call

components/mediation-initializer/org.wso2.carbon.mediation.initializer/src/main/java/org/wso2/carbon/mediation/initializer/ServiceBusConstants.java, components/mediation-initializer/org.wso2.carbon.mediation.initializer/src/main/java/org/wso2/carbon/mediation/initializer/multitenancy/TenantServiceBusInitializer.java
improve fault,main,registry initial xml retriaval for tenantcy
=> improve fault,main,registry initial xml retriaval for tenantcy

components/mediators/smooks/org.wso2.carbon.mediator.smooks/src/main/java/org/wso2/carbon/mediator/transform/Input.java
Fixes: https://github.com/wso2/product-ei/issues/5529
=> Issue when converting EDI file to XML using Smooks

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint.ext.wsrm/pom.xml, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundCorrelationEnabledHttpServerWorker.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketResponseSender.java, components/inbound-endpoints/pom.xml, components/mediation-admin/org.wso2.carbon.inbound/pom.xml, components/mediation-admin/org.wso2.carbon.task.services/pom.xml, components/mediation-admin/org.wso2.carbon.task/pom.xml, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.publishevent.ui/pom.xml, components/mediators/publishEvent/org.wso2.carbon.mediator.publishevent/pom.xml, pom.xml
resolve #https://github.com/wso2/product-apim/issues/12205
=> remove log4j1 usage

pom.xml
=> Update netty to 4.1.73.Final

pom.xml
Fix: https://github.com/wso2/micro-integrator/issues/2478
=> Upgrade synapse and jayway versions.

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/pom.xml, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/inboundfactory/InboundRequestProcessorFactoryImpl.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/httpssecurewebsocket/InboundHttpsSecureWebsocketListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/httpwebsocket/InboundHttpWebSocketConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/httpwebsocket/InboundHttpWebsocketListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/httpwebsocket/management/HttpWebsocketEndpointManager.java, components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/pom.xml, components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/src/main/java/org/wso2/carbon/mediation/transport/handlers/AbstractHttpGetRequestProcessor.java, components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/src/main/java/org/wso2/carbon/mediation/transport/handlers/Axis2HttpGetRequestProcessor.java, components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/src/main/java/org/wso2/carbon/mediation/transport/handlers/PassThroughNHttpGetProcessor.java, features/carbon-transports/org.wso2.carbon.websocket.feature/pom.xml, pom.xml
This PR will add the following features to the product.
- Add a new Inbound Endpoint that will start the Netty based HTTP transport
- Add new HttpGetRequestProcessor for Netty based Http transport - `org.wso2.carbon.mediation.transport.handlers.Axis2HttpGetRequestProcessor`
A sample of the newly introduced Inbound endpoint will be like follows.
```
<inboundEndpoint xmlns="http://ws.apache.org/ns/synapse"
name="httpWebsocketInboundEndpoint"
protocol="httpws">
<parameters>
<parameter name="port">9000</parameter>
...
...
</parameters>
<handlers/>
</inboundEndpoint>
```
Secured inbound endpoint
```
<inboundEndpoint xmlns="http://ws.apache.org/ns/synapse" 
name="httpsWssInboundEndpoint"
protocol="httpswss">
<p:parameters xmlns:p="http://ws.apache.org/ns/synapse">
<p:parameter …
```
=> Add Inbound Endpoint and HttpGetRequestProcessor support for the Netty based HTTP Transport

features/mediation-admin-features/org.wso2.carbon.mediation.admin.feature/pom.xml, features/message-processors/org.wso2.carbon.message.processor.feature/pom.xml, features/message-processors/pom.xml, features/org.wso2.carbon.proxy.admin.feature/pom.xml, pom.xml
=> bring proxy admin and message store into different feature

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java
Fixes https://github.com/wso2/product-apim/issues/11961
=> Add health check for ports 8099 and 9099

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java
Fixes: https://github.com/wso2/product-apim/issues/12043
Adding the support for graphql-ws protocol in GraphQL subscriptions
Porting the missing fixes in [1].
[1] https://github.com/wso2-support/carbon-mediation/pull/700
=> Adding the support for graphql-ws protocol in GraphQL subscriptions

pom.xml
> saml.common.util version needs to be upgraded for XACML use cases.
=> Upgrade openSAML and saml.common.util versions.

components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/java/org/wso2/carbon/endpoint/ui/endpoints/http/HttpEndpoint.java, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/forms/httpEndpoint-form.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/updatePages/httpEndpoint-update.jsp
With https://github.com/wso2/wso2-synapse/pull/1844 Password grant type was added to OAuth HTTP endpoints. This PR adds the changes to the management console to view/edit Password grant type OAuth configs.
=> Add Password grant OAuth support for HTTP EPs in the management console

features/mediator-features/org.wso2.carbon.mediators.server.feature/pom.xml, pom.xml
=> Upgrade dependencies

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java
Reverts wso2/carbon-mediation#1599
=> Revert "Adding the support for graphql-ws protocol in GraphQL subscriptions"

features/mediator-features/org.wso2.carbon.mediators.server.feature/pom.xml, pom.xml
=> Downgrade velocity core dependency

features/mediator-features/org.wso2.carbon.mediators.server.feature/pom.xml, pom.xml
=> Fix compilation failure

pom.xml
=> Remove quickfixj dependencies

components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/java/org/wso2/carbon/endpoint/ui/endpoints/http/HttpEndpoint.java, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/forms/httpEndpoint-form.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/updatePages/httpEndpoint-update.jsp
This to fix wso2/product-ei#5512
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
=> Introduce authMode parameter to auth mediator

components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/java/org/wso2/carbon/endpoint/ui/endpoints/http/HttpEndpoint.java, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/forms/httpEndpoint-form.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/updatePages/httpEndpoint-update.jsp, pom.xml
$subject
Fixes: https://github.com/wso2/product-ei/issues/5511
**Do not merge this PR until https://github.com/wso2/wso2-synapse/pull/1870 PR got merged and bump Synapse version. This PR contains a change in package naming.**
=> Adding basic auth support for HTTP endpoints in management UI

pom.xml
=> Upgrade synapse and vfs dependencies

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebSocketClientHandler.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConnectionFactory.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/ConfigurationLoader.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/Constants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java
> Fixes - https://github.com/wso2/product-apim/issues/12703
=> Fixing product-apim/issues/12703

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java
=> Fixing compilation error

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebSocketClientHandler.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConnectionFactory.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketTransportSender.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketResponseSender.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/management/WebsocketSubscriberPathManager.java
> Fix https://github.com/wso2/api-manager/issues/257
> Fix https://github.com/wso2/api-manager/issues/311
> Fix https://github.com/wso2/api-manager/issues/312
=> Fix inconsistence behaviour in GraphQL websocket APIs

pom.xml
> Bump version to  2.1.7-wso2v301
=> bump version to 2.1.7-wso2v301

components/mediation-admin/org.wso2.carbon.rest.api/src/test/resources/TestAllApiChangedSwagger.json, components/mediation-admin/org.wso2.carbon.rest.api/src/test/resources/TestAllApiChangedSwaggerRelativePath.json
> Accommodate the changes introduced with https://github.com/wso2/carbon-mediation/pull/1624
=> Fix swagger related test cases

pom.xml
> Bump synapse version to 2.1.7-wso2v303
=> Bump synapse version to 2.1.7-wso2v303

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketResponseSender.java
> Terminate web socket connections for unauthorized requests.
> Send a proper error message on connection termination.
> Fix https://github.com/wso2/api-manager/issues/562
=> Handle unauthorized web socket APIs

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/pom.xml, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebSocketClientHandler.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/test/java/org/wso2/carbon/websocket/transport/WebSocketClientHandlerTest.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketResponseSender.java, pom.xml
Fixes: https://github.com/wso2/api-manager/issues/661
Fixing WS close code missing issue
=> Fixing WS close code missing issue

pom.xml
relates to: https://github.com/wso2/api-manager/issues/545
=> Bump org.milyn.wso2 Version

components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediator.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CachingConstants.java
=> Fix for - "Enabling response caching cause a 500 error when using content type header when the status code is 204"

pom.xml
>This PR includes change to sysnapse version to 4.0.0-wso2v1 from 2.1.7-wso2v310 change.
=> Bump sysnapse version to 4.0.0-wso2v1 from 2.1.7-wso2v310.

features/carbon-transports/org.wso2.carbon.websocket.feature/pom.xml, pom.xml
=> Added the unix netty-transport-native-unix-common wo websocket-api feature.

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConnectionFactory.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketTransportSender.java
- Resolves https://github.com/wso2/product-apim/issues/12785
=> Fix NPE which occurs if the initial ws frame is received before the post handshake logic completes

pom.xml
$subject
Related issue: https://github.com/wso2/api-manager/issues/992
=> Bump synapse version to 4.0.0-wso2v4

pom.xml
Upgrades carbon.identity.entitlement.proxy version …
=> Upgrade identity entitlement version

pom.xml
Upgrades saml.common.util version
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …
=> upgrade saml.common.util version

pom.xml
=> Upgrade snakeyaml version

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebSocketClientHandler.java
Fixes: https://github.com/wso2/product-apim/issues/12265
=> Setting true for WebSocket response

components/mediation-initializer/org.wso2.carbon.mediation.initializer/src/main/java/org/wso2/carbon/mediation/initializer/multitenancy/TenantServiceBusInitializer.java
Porting the missing PR done on 4.7.61 support branch to public master branch.
Fixes https://github.com/wso2/product-apim/issues/12653
=> Fix tenant unloading issue when tenant loading is unsuccessfull

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketTransportSender.java
Fix https://github.com/wso2/product-apim/issues/12861
=> Generalize the error message

pom.xml
$subject
Related issue: https://github.com/wso2/api-manager/issues/1251
=> Update synapse version for commons-net upgrade

pom.xml
Fix https://github.com/wso2/api-manager/issues/1252
=> Upgrade libthrift

pom.xml
=> Upgrade Jackson version

pom.xml
=> upgrade kernel version.

pom.xml
Fix https://github.com/wso2/api-manager/issues/1229
=> Upgrade carbon.identity.entitlement.proxy.version

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/ssl/SSLHandlerFactory.java
The SSL context protocol should be upgraded to a more secure protocol to fix "Selection of Less-Secure Algorithm During Negotiation" security vulnerabilities.
Upgraded SSL context protocol to TLSv1.2
=> Upgrade the Algorithm in SSLHandlerFactory.java Class to TLSv1.2

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java
Fixes https://github.com/wso2/api-manager/issues/1494
=> Fix sub-protocol error when server closes the connection

components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/APIGenerator.java
FIxes https://github.com/wso2-enterprise/wso2-apim-internal/issues/3594
=> Fix for issue creating rest API using swagger definition

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/management/WebsocketSubscriberPathManager.java
Issue : https://github.com/wso2/api-manager/issues/2059
Fix 1 : https://github.com/wso2-support/carbon-mediation/commit/7bd40bccd1cdfe1355db44b773c2ddda6e59356e
Fix 2: https://github.com/wso2-support/carbon-mediation/pull/861
=> Fix web socket load testing issues

components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/OpenAPIProcessor.java
Related issue: https://github.com/wso2/integration-studio/issues/1255
=> Add a sample request body for default API resource

components/mediation-admin/org.wso2.carbon.rest.api/src/test/resources/SwaggerWithContext.json
Fix test failures introduced by https://github.com/wso2/carbon-mediation/pull/1687
=> Fix test failures

pom.xml
> Upgrade guava and synapse versions
=> Upgrade guava and synapse versions

pom.xml
>  Upgrade commons-codec version to 1.16.0
=> Upgrade commons-codec version to 1.16.0

pom.xml
Upgrade synapse version to 4.0.0-wso2v77
=> Upgrade synapse version to 4.0.0-wso2v77

pom.xml
Upgrade synapse to 4.0.0-wso2v87
=> Upgrade synapse verion to 4.0.0-wso2v87

components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/service/RestApiAdmin.java
Fixes https://github.com/wso2/api-manager/issues/2818
=> Improve Error Handling and Logging

components/mediation-diagnostics/pom.xml, components/mediation-diagnostics/src/main/java/org/wso2/carbon/diagnostics/action/executor/MetricsSnapshot.java, components/mediation-diagnostics/src/main/java/org/wso2/carbon/diagnostics/trafficanalyzer/SimpleMovingAverage.java, components/mediation-diagnostics/src/main/java/org/wso2/carbon/diagnostics/trafficanalyzer/TrafficAnalyzer.java, components/mediation-diagnostics/src/main/java/org/wso2/carbon/diagnostics/trafficanalyzer/TrafficAnalyzerRunnable.java, pom.xml
$subject 
Related to https://github.com/wso2/micro-integrator/issues/2985
This PR moves custom implementation related to MI from the generic runtime tool to MI related repos.
[1] - https://github.com/wso2/runtime-diagnostic-tool/tree/v.1.0.x/src/main/java/org/wso2/diagnostics/watchers/trafficanalyzer
=> Add custom executor and watcher for runtime diagnostic tool

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/pom.xml, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/executors/ScriptExecutor.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/executors/ScriptExecutorFactory.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/executors/ScriptExecutorType.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/utils/DataMapperEngineConstants.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/pom.xml, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/DataMapperMediator.java, pom.xml
$subject
Related to https://github.com/wso2/micro-integrator/issues/3359
This PR adds the initial implementation needed for Graalvm Javascript integration with Datamapper engine. Further performance improvements needs to be added.
=> Integrate graaljs for datamapper engine

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/executors/ScriptExecutor.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/output/formatters/MapOutputFormatter.java, pom.xml
=> Preserve backward compatibility and avoid warnings in datamapper

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebSocketClientHandler.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConstants.java
- Resolves https://github.com/wso2/api-manager/issues/2944
- Add error code and error message to synapse message context in the fault sequence.
=> Add error code and error message

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/DataMapperMediator.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/config/xml/DataMapperMediatorFactory.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/config/xml/DataMapperMediatorSerializer.java
=> Improve datamapper to read input/output type from json schema

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/utils/SSLUtil.java
Fixes https://github.com/wso2/api-manager/issues/2884
=> Use system property to get SSL algorithm

pom.xml
=> Upgrade synapse and axis2 dependencies

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/mapper/MappingResource.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/utils/DataMapperEngineConstants.java
=> Fix mapFunction constant with correct syntax

pom.xml
$subject
Related issue: https://github.com/wso2/api-manager/issues/3105
=> Bump synapse and jackson versions

pom.xml
=> Bump synapse verion

components/business-adaptors/hl7/org.wso2.carbon.business.messaging.hl7.store/src/main/java/org/wso2/carbon/business/messaging/hl7/store/JDBCConsumer.java, components/business-adaptors/hl7/org.wso2.carbon.business.messaging.hl7.store/src/main/java/org/wso2/carbon/business/messaging/hl7/store/jpa/JPAConsumer.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint.ext.wsrm/src/main/java/org/wso2/carbon/inbound/endpoint/ext/wsrm/InboundRMHttpListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/common/InboundOneTimeTriggerRequestProcessor.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/common/InboundRequestProcessorImpl.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/generic/GenericEventBasedListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/generic/GenericInboundListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/generic/GenericProcessor.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/hl7/core/InboundHL7Listener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/https/InboundHttpsListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/httpssecurewebsocket/InboundHttpsSecureWebsocketListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/httpwebsocket/InboundHttpWebsocketListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSProcessor.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/kafka/KAFKAProcessor.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/mqtt/MqttListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/nats/InboundNatsListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/securewebsocket/InboundSecureWebsocketListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketListener.java, pom.xml
This PR introduces the framework for managing Inbound Endpoints.
Key features include:
- Method to Activate File Inbound Endpoint.
- Method to Deactivate File Inbound Endpoint.
- Method for Optional State Validation.
Related Synapse PR: https://github.com/wso2/wso2-synapse/pull/2261
=> Add Framework to Support Activating and Deactivating File Inbound Endpoints

pom.xml
=> Upgrade wso2 transport netty version

pom.xml
=> Update synapse dependency

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/mapper/MappingResource.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/utils/DataMapperEngineConstants.java, pom.xml
=> Improve json output array mapping in Datamapper

components/mediators/fastXSLT/org.wso2.carbon.mediator.fastXSLT/src/main/java/org/wso2/carbon/mediator/fastXSLT/FastXSLTMediator.java
Fixes: https://github.com/wso2-enterprise/wso2-mi-internal/issues/1479
=> Fix FastXSLT with Respond mediator prepending transformed message content

pom.xml
=> Upgrade org.json.wso2:json version

pom.xml
=> Update gson dependency

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/generic/GenericPollingConsumer.java
Add resume method to avoid build failure of SF inbound
=> Add resume method to avoid build failure of SF inbound

components/mediators/smooks/org.wso2.carbon.mediator.smooks/src/main/java/org/wso2/carbon/mediator/transform/SmooksMediator.java, components/mediators/smooks/org.wso2.carbon.mediator.smooks/src/main/java/org/wso2/carbon/mediator/transform/xml/SmooksMediatorFactory.java, components/mediators/smooks/org.wso2.carbon.mediator.smooks/src/main/java/org/wso2/carbon/mediator/transform/xml/SmooksMediatorSerializer.java
Add Dynamic Config-Key support for the Smooks mediator. 
Fixes:https://github.com/wso2/product-micro-integrator/issues/4063
=> Add Dynamic Config-Key support for the Smooks mediator

components/mediation-admin/org.wso2.carbon.localentry/src/main/java/org/wso2/carbon/localentry/service/LocalEntryAdmin.java
- Improve the stax parser by setting necessary properties
=> Improve Stax Parser

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/config/xml/DataMapperMediatorFactory.java
Add versioning support for CApps
https://github.com/wso2/product-micro-integrator/issues/4298
=> Add versioning support for DataMapper

components/mediation-initializer/org.wso2.carbon.mediation.initializer/src/main/java/org/wso2/carbon/mediation/initializer/multitenancy/StratosEntryFactory.java
=> Implement getObjectFromOMNode for StratosEntryFactory

components/mediation-admin/org.wso2.carbon.mediation.library/src/main/java/org/wso2/carbon/mediation/library/service/upload/LibraryUploader.java
- This PR Enhanced the file validation logic in the LibraryUploader service to ensure proper handling of uploaded library files
=> Improve file path validation in LibraryUploader
