wso2/carbon-mediation

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSPollingConsumer.java
Some MBs like WSO2 MB cannot read within a millisecond.
this is to fix that issue by removing timeout : http://docs.oracle.com/javaee/1.4/api/javax/jms/MessageConsumer.html#receive(long)
Credit goes to @sandamal for figuring out this.
=> Changing JMS Inbound timeouts

components/mediation-admin/org.wso2.carbon.mediation.library/src/main/java/org/wso2/carbon/mediation/library/service/MediationLibraryAdminService.java, components/mediation-admin/org.wso2.carbon.task/src/main/java/org/wso2/carbon/task/CarbonTaskManagementService.java, service-stubs/mediation-admin/org.wso2.carbon.task.stub/src/main/resources/TaskAdmin.wsdl
Many important operations in ```MediationLibraryAdminService``` and ```CarbonTaskManagementService``` had returned void as the final result. That caused problems with external applications with exceptions such as 'Input Stream null'. 
This changes some of those to return boolean values instead void.
(Credit goes to @bsenduran for original implementation.)
=> Changing task admin services to return boolean value

components/mediation-admin/org.wso2.carbon.mediation.library/src/main/java/org/wso2/carbon/mediation/library/service/MediationLibraryAdminService.java, components/mediation-admin/org.wso2.carbon.task/src/main/java/org/wso2/carbon/task/CarbonTaskManagementService.java
Many important operations in ```MediationLibraryAdminService``` and ```CarbonTaskManagementService``` had returned void as the final result. That caused problems with external applications with exceptions such as 'Input Stream null'. 
This changes some of those to return boolean values instead void.
=> Backend changes to return boolean instead of void

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.validate.ui/src/main/resources/web/validate-mediator/edit-mediator.jsp
SynaspsePath cast to SynapseXPath since schemaKey.getExpression() method changed.
=> ESBJAVA-3761 - SynapseXPath error

components/mediation-ui/org.wso2.carbon.rest.api.ui/src/main/resources/web/api/manageAPI.jsp
When an API is added through master/API source view, all APIs become uneditable. APIData.getName() returns null when manageAPI.jsp is invoked from index.jsp.
=> ESBJAVA-3717 - API source view issue fixed

components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/WSO2Registry.java
(Need Review)
In this fix all the non XML content are returned as OMText object containing the content as plain text.
=> Esbjava 3225

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.enqueue.ui/pom.xml
Imported the servlet api related packages explicitly. The issue occurred due to implicit import of non existing version.
=> Fixing https://wso2.org/jira/browse/ESBJAVA-3950

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/kafka/KAFKAMessageListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/kafka/KAFKAPollingConsumer.java
Between every time interval,the zookeeper exception is printed in the ESB. The PR is for removing that.
Before this fix
------------------
[2015-07-28 15:40:07,298] ERROR - KAFKAMessageListener  Error in Creating Kafka Consumer Connector | ZkTimeoutUnable to connect to zookeeper server within timeout: 6000
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 6000
at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:880)
at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:98)
at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:84)
at kafka.consumer.ZookeeperConsumerConnector.connectZk(ZookeeperConsumerConnector.scala:156)
at kafka.consumer.ZookeeperConsumerConnector.<init>(ZookeeperConsumerConnector.scala:114)
at …
=> Removed the full zookeeper exception log

components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/docs/userguide.html
This causes build failure in AppM. It might cause build failure in other products too.
=> Fixing inalid XHTML due to missing LI closing tag

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/pom.xml, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/internal/MediationStatisticsComponent.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/publish/ConfigurationPublisher.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/publish/StatisticsPublisher.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/services/MessageFlowReporterThread.java, features/synapse-features/org.apache.synapse.wso2.feature/pom.xml
This is to make it more convenient to debug messages publishing to Analytic Server.
Need to add following entry to log4j.properties to enable : 
```
log4j.logger.org.wso2.carbon.das.messageflow.data.publisher=DEBUG
```
Using Jackson library for JSON processing
Use async. method for publishing statistics
=> Adding debug logs when publishing data to analytic server, Using Jackson for JSON, Async. publishing

features/synapse-features/org.apache.synapse.wso2.feature/pom.xml
Adding back "json-smart" since "json-path" needs that
=> fixing_json_test_failure

components/event-sink/org.wso2.carbon.event.sink/src/main/java/org/wso2/carbon/event/sink/EventSink.java
With migration to analytics-common, if there's no value for authenticationUrlSet, data bridge expects a null value.
=> Adding null for empty authenticationUrlSet

components/mediation-ntask/src/main/java/org/wso2/carbon/mediation/ntask/Constants.java, components/mediation-ntask/src/main/java/org/wso2/carbon/mediation/ntask/NTaskAdapter.java, components/mediators/publishEvent/org.wso2.carbon.mediator.publishevent/src/main/java/org/wso2/carbon/mediator/publishevent/ActivityIDSetter.java, components/mediators/publishEvent/org.wso2.carbon.mediator.publishevent/src/main/java/org/wso2/carbon/mediator/publishevent/PublishEventMediator.java
This will enables event publish mediator to work with scheduled tasks. Since schedule tasks uses separate threads, event publish mediator failed to find a tenant id.
This fix is only applicable for synapse Message Injector type tasks.
Ref: https://github.com/wso2/wso2-synapse/pull/552
=> Fix task issue with PublishEvent mediator

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.data.publisher.util/src/main/java/org/wso2/carbon/das/data/publisher/util/DASDataPublisherConstants.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/internal/MediationStatisticsComponent.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/observer/jmx/JMXMediationFlowObserver.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/observer/jmx/data/StatisticCollectionViewMXBean.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/observer/jmx/data/StatisticsCompositeObject.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/observer/jmx/data/SummeryStatisticObject.java
JMX functionality and statistic reporting collection thread default values can be configured in carbon.xml by using the following configuration.
` <MediationFlowStatisticConfig>
<AnalyticsServerPublishingInterval>2000</AnalyticsServerPublishingInterval>
<JmxPublishingDisable>true</JmxPublishingDisable>
</MediationFlowStatisticConfig>`
=> JMX publishing capability for statistics implementation

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.data.publisher.util/src/main/java/org/wso2/carbon/das/data/publisher/util/DASDataPublisherConstants.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/internal/MediationStatisticsComponent.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/observer/DASMediationFlowObserver.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/observer/TenantInformation.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.das.messageflow.data.publisher/src/main/java/org/wso2/carbon/das/messageflow/data/publisher/observer/jmx/JMXMediationFlowObserver.java
You can register custom observers by copying jar file which contains observer implementation.
- It should implement org.wso2.carbon.das.messageflow.data.publisher.observer.MessageFlowObserver Interface 
- If observer is tenant aware, it should implement org.wso2.carbon.das.messageflow.data.publisher.observer.TenantInformation
_**Steps to follow**_
- [Copy jar file to repository/components/lib directory of the ESB
- Add all the custom observers separated with commas in carbon.xml like follows 
`<MediationFlowStatisticConfig> <Observers>org.wso2.custom.Observer1,org.wso2.custom.Observer1r</Observers> </MediationFlowStatisticConfig>`
=> Adding functionality to register custom statistic observers

components/mediators/oauth/org.wso2.carbon.identity.oauth.mediator/src/main/java/org/wso2/carbon/identity/oauth/mediator/OAuthConstants.java, components/mediators/oauth/org.wso2.carbon.identity.oauth.mediator/src/main/java/org/wso2/carbon/identity/oauth/mediator/OAuthMediator.java
Initially client needs to obtain an access_token with providing the scope. (valid for OAuth2 only)
This improvement verifies the scope getting from the OAuth mediator is exactly the same as what it should be.
Start WSO2 IS (port offset=0) and WSO2 ESB (port offset=1) 
Generate a token by passing scope:
```
curl --user  {client_id} :{client_secret} -k -d "grant_type=password&username={username}&password={password}&scope=API_A" -H  "Content-Type: application/x-www-form-urlencoded" https://localhost:9443/oauth2/token
```
will get a response as follows
```
{"scope":"API_A","token_type":"bearer","expires_in":3299,"refresh_token":"9d8b7ae18693554afd99bd5be6","access_token":"1ce493a9bec3da0349145bb44"}
```
thereafter in token verification process, WSO2 ESB gets scope for this access_token.
Add …
=> OAuth 2 scope check

components/mediation-initializer/org.wso2.carbon.mediation.dependency.mgt/src/main/java/org/wso2/carbon/mediation/dependency/mgt/DependencyTracker.java
Changing dependency tracker to print logs which can be tracked by Log Analyzer
=> Allow printing logs from dependancy-tracker overriden methods

components/mediation-ui/org.wso2.carbon.proxyadmin.ui/src/main/resources/web/proxyservices/index.jsp
This fix is to resolve the https://wso2.org/jira/browse/ESBJAVA-4842. In the fix we are removing the xml namespace since it is not mandatory for the ui rendering
=> Fixing ESBJAVA-4842

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConnectionFactory.java
Fixed updating handlerMap (cause of redundant open ports when sending via WebSocket).
Fix for #753 and [JIRA issue](https://wso2.org/jira/browse/ESBJAVA-4915).
=> ESBJAVA-4915

components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/src/main/java/org/wso2/carbon/mediation/transport/handlers/PassThroughNHttpGetProcessor.java
A regression issue has been occured due to the fix for https://wso2.org/jira/browse/CIDENTITY-25. The way that getting tenant domain in the isTenantActive menthod in the JDBCTenantManager is changed to retrieve it from the tenant flow.
Therefore, the tenat domain has to be set whatever the flow that calls the isTenantActive method. This fix is to set the tenant domain when accessing the swagger.json of an API
https://wso2.org/jira/browse/ESBJAVA-5069
=> Set tenant domain when access swagger.json of API

components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/config/inbound.properties
This adds the missing parameter 'ws.pipeline.handler.class' for WS inbound protocol in CarbonUI
Public Jira - https://wso2.org/jira/browse/ESBJAVA-5068
=> Add missing parameter for WS inbound protocol

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/common/InboundRunner.java
This is to fix wso2/product-ei#532
When the "clusteringPattern" is set to "nonWorkerManager", Inbound endpoint with coordination=false doesn't work. It gives an INFO log with "Inbound EP will not run in manager node. Same will run on worker(s)", when adding the inbound EP. As, the clustering pattern is nonWorkerManager, considering the node as manager is wrong.
Therefore the fix is to check for the clusterin pattern and if it is workerManager, and the node is not a worker node (in other words, the node is a manager node), then prints that INFO log to communicate that the EP will not run on the manager node.
=> Check clustering pattern before adding inbond EP

components/mediation-initializer/org.wso2.carbon.mediation.initializer/src/main/java/org/wso2/carbon/mediation/initializer/multitenancy/TenantServiceBusInitializer.java
Fix OOM issue when tenant loading/unloading multiple times when a particular tenant has large number of APIs by unregistering registered services when tenant get unloaded
[APIMANAGER-5755]
=> Fix: OOM issue when tenant loading/unloading

components/mediation-initializer/org.wso2.carbon.mediation.initializer/src/main/java/org/wso2/carbon/mediation/initializer/CarbonSynapseController.java
- Set "keepServiceHistory" parameter to "true" for all the proxy services on server shutdown to preserve parameters saved in the registry.
- Retrieved service can be inactive. Hence we can't use AxisConfiguration to retrieve AxisService. It only returns active Axis Services.
Fix: https://wso2.org/jira/browse/ESBJAVA-5105
=> Retrieve AxisService from ProxyService to update service params

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.dblookup.ui/src/main/java/org/wso2/carbon/mediator/dblookup/DBLookupMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.dbreport.ui/src/main/java/org/wso2/carbon/mediator/dbreport/DBReportMediator.java
This enables providing registry resource as the key attribute for db
pool config in external datasource config for DBLookup and DBReport
mediators. Fix for https://wso2.org/jira/browse/ESBJAVA-5056.
=> [ESBJAVA-5056] Add the ability to provide db pool info through registry in DB mediators

components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/SAPTransportSender.java
The trasnaction id used for the communication between SAP and the
SAPTransaportSender to send IDOCs can be of intereset when it comes to
responding to the client back in a Proxy. It could be used to track
what transactions were successful and what failed. The improvement was
to set it as a transport header to the synapse context so that it can
be refererded to, in the synapse sequence.
Addresses the issue at: https://wso2.org/jira/browse/ESBJAVA-5138
=> Fix ESBJAVA-5138

components/application-deployers/org.wso2.carbon.application.deployer.synapse/src/main/java/org/wso2/carbon/application/deployer/synapse/SynapseAppDeployer.java
This includes the fix for handling CApp artifact undeployment order where it reverses the order of the artifacts in the artifacts.xml file before undeploying
public jira - https://wso2.org/jira/browse/ESBJAVA-5201
=> Fix CApp artifact undeployment order

components/mediation-ui/org.wso2.carbon.event.sink.config.ui/src/main/resources/web/event-sink-config/add_event_sink.jsp
This PR contains the fix for the event sink URL validation issue.
This fix allows adding multiple URLs separated by commas in the Receiver URL field.
Related git issue: https://github.com/wso2/product-ei/issues/835
=> Fix event sink receiver url validation

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.log.ui/src/main/java/org/wso2/carbon/mediator/log/LogMediator.java
Fixed the issue of not converting log separator characters '\t' and '\n' into
relevant encoded characters in the source view, when adding it from the design view.
Related Issue : https://wso2.org/jira/browse/ESBJAVA-4484
=> Fix for Log Separator in Log mediator

components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/java/org/wso2/carbon/endpoint/ui/endpoints/failover/FailoverEndpoint.java, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/java/org/wso2/carbon/endpoint/ui/endpoints/loadbalance/LoadBalanceEndpoint.java, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/org/wso2/carbon/endpoint/ui/i18n/Resources.properties, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/failoverEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/loadBalanceEndpoint.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/updatePages/failoverEndpoint-update.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/updatePages/loadBalanceEndpoint-update.jsp
Fix the issue of not supporting "buildMessage" attribute of failover and loadbalance endpoint in the management console.
Related issue : https://github.com/wso2/product-ei/issues/909
=> [EI-909] Add "buildMessage" attribute to management console

pom.xml
This PR updates the synapse version to the latest released version: 2.1.7-wso2v19.
=> Update synapse version to the released version

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSPollingConsumer.java
This is to add the inbound endpoint support for message type javax.jms.Message types
Currently, inbound endpoints support only for javax.jms.TextMessage type.
Related JIRA : https://wso2.org/jira/browse/ESBJAVA-5085
=> [ESBJAVA-5085]Inbound endpoint support for javax.jms.Message types

components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/manageFailoverMessageForwardingProcessor.jsp, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/manageMessageForwardingProcessor.jsp
Maximum redelivery attempts value is not reflected correctly in Message Processor UI when updated through UI. This fix is to correctly display the updated value.
Related JIRA : https://wso2.org/jira/browse/ESBJAVA-5090
=> Message processor max.delivery.attempts UI fix

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSPollingConsumer.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/factory/CachedJMSConnectionFactory.java
- Cached connections, sessions, and consumers don't get refreshed after a service interruption. This commit fixes that issue by reestablishing connections, sessions, and consumers.
Issue: https://github.com/wso2/product-ei/issues/999
=> Fix JMS inbound endpoint cached resource refresh issue

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSUtils.java
This PR introduces MapMessage as a valid JMS message type, to be used when inferring the type of a JMS message.
Resolves wso2/carbon-mediation/issues/884
=> Introduce MapMessage as a valid JMS message type

components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/service/RestApiAdmin.java
RestAPIAdminService when statistics/tracing is enabled/disabled, APIData type setters/getters are updated only when the API is retrieved through getAPIListing method. If a user only wants to retrieve a specific API by calling 'getAPIByName()' method even though statistics/tracing is updated , those values will not be set/removed. 
Therefore updated 'convertApiToApiData()' method (which is used in getAPIByName method) to check the availability of statistics/tracing and update APIData type object accordingly. 
Tests are updated accordingly in https://github.com/wso2/product-ei/pull/1169.
=> Fix statistic/tracing setting in RestAPIAdminService.

components/application-mgt/org.wso2.carbon.application.mgt.synapse/src/main/resources/META-INF/services.xml, components/mediation-ui/org.wso2.carbon.mediation.library.ui/src/main/resources/META-INF/component.xml
Currently, the list/add actions for connectors and carbon apps are assigned to "permission/admin/manage" root level permission. In a scenario where a user needs to give only specific permissions (e.g. identity/user/add) under "permission/admin/manage", the current approach will not work. Therefore adding more granular permissions.
Git Issue       : https://github.com/wso2/product-ei/issues/932
=> Add granular permissions for capps and connectors

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/pom.xml, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/common/InboundRequestProcessorImpl.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSTask.java, components/mediation-ntask/src/main/java/org/wso2/carbon/mediation/ntask/NTaskTaskManager.java, pom.xml
Resolves: https://github.com/wso2/product-ei/issues/1135
The underlying JMS consumer used to communicate when a JMS inbound is used, should be disconnected when the inbound task is deleted.
Adds a JMS task as a listener for task deletion. Whenever the task is
deleted locally, the underlying consumer is removed.
N/A
This fix adds a JMS task as a listener for task deletion. Whenever the task is deleted locally, the underlying consumer is removed.
N/A. This is an internal implementation which is not useful to an end user.
N/A. The implementation is done as a resolution to an issue which is an edge case in CAR deployment with a JMS inbound endpoint.
N/A. The implementation is done as a resolution to an issue which is an edge case in CAR deployment with a JMS inbound endpoint.
N/A
N/A. The …
=> Fix wso2/product-ei/#1135

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.cache.ui/src/main/java/org/wso2/carbon/mediator/cache/ui/CacheMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.cache.ui/src/main/resources/web/cache-mediator/update-mediator.jsp, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediator.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediatorSerializer.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CachingConstants.java
>When a field is set to empty after an edit to the cache mediator in the management console, this value >is simply ignored and the previous value is taken by the cache mediator.
>Fix the issue in the management console so that the default value is set if the field is empty
>The fix was that when an empty string appears the default value is set and displayed accordingly
>N/A
>https://github.com/wso2/product-ei/issues/971 Can not remove the initial value assigned to the >Maximum message size property in cache mediator
>N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> Will be added
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR …
=> Resolve wso2/product-ei#971

components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CachableResponse.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediator.java
Resolve wso2/product-ei#1010
Avoid NullPointerException in cache mediator when generating a response from EI if there are no call to the backend before the collector.
The fix was to check for null in relevant places and ensure no NullPointerException is thrown.
N/A
wso2/product-ei#1010 NullPointerException in cache mediator when generating a response from EI 
N/A
N/A
N/A
N/A
- Unit tests 
N/A
Needs to be added to product-ei
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
N/A
https://github.com/wso2/carbon-mediation/pull/843
N/A
JDK 1.8.0 Ubuntu 16.04 …
=> Resolve wso2/product-ei#1010

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/file/VFSProcessor.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSProcessor.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/kafka/KAFKAProcessor.java
Fix the issue of deleting registry task at cluster node shutdown with hazelcast.shutdownhook.enabled=false.
Fixed: https://github.com/wso2/product-ei/issues/1206
As the approach, we introduced a new parameter to differentiate shutdown and delete scenarios, and delete the registry task only at inbound endpoint delete. Inbound task at registry will remain at the shutdown scenario.
will be released with 6.2.0
https://docs.wso2.com/display/EI611/Clustered+Deployment
https://github.com/wso2/wso2-synapse/pull/958
=> Fix for scheduling inbound task at delete and shutdown

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/factory/CachedJMSConnectionFactory.java
Refer - https://wso2.org/jira/browse/ESBJAVA-5247
> To resolves the issue of getting a jms error (JMS Exception while starting connection for factory 'QueueConnectionFactory') when shutting down one node in a cluster environment.
>After closing connections they are assigned null values.  
> Two node nonWorkerManager cluster
=> Resolves ESBJAVA-5247

pom.xml
Upgrades the synapse dependancy version to 2.1.7-wso2v30 which is the latest released version of synapse.
=> Upgrade synapse version to 2.1.7-wso2v30

components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/java/org/wso2/carbon/endpoint/ui/util/EndpointConfigurationHelper.java, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/index.jsp
When a description is added to an endpoint, in list view of management console, endpoint name is displayed with a span tag. This is due to a missing '<' tag. Please refer [1] 
[1] https://wso2.org/jira/browse/ESBJAVA-4397
=> [ESBJAVA-4397] Fix Endpoint list view issue when description is added

components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/org/wso2/carbon/inbound/ui/i18n/Resources.properties, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/editInbound.jsp, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/inboundcommon.js, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/web/inbound/newInbound1.jsp
transport.jms.DurableSubscriberName is required if transport.jms.SubscriptionDurable set to true. But this is not validated in the form and after it throws and exception as in [1]
[1] https://github.com/wso2/product-ei/issues/1479
The form checks if transport.jms.SubscriptionDurable set to true and if so, it checks whether transport.jms.DurableSubscriberName is defined. If not, an error messages is getting pop-up.
=> Validate required fields in JMS Inbound Endpoint

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/pom.xml, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/java/endpoint/protocol/jms/JMSBrokerController.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/java/endpoint/protocol/jms/JMSTestsUtils.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/java/endpoint/protocol/jms/tests/JMSConnectionFactoryTestCase.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/java/endpoint/protocol/jms/tests/JMSPollingConsumerQueueTest.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/java/endpoint/protocol/jms/tests/JMSPollingConsumerTopicTest.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/java/endpoint/protocol/jms/tests/JMSReplySenderTest.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/java/endpoint/protocol/jms/tests/JMSUtilsTest.java, pom.xml
This is to add unit tests for JMS Inbound EPs. 
Following testcases are added
JMSPollingConsumerQueueTest - start ActiveMQ embeded server. Add a JMS Inbound Task. Check whether the queue is added in the broker
JMSPollingConsumerTopicTest - start ActiveMQ embeded server. Add a JMS Inbound Task. Check whether the topic is added in the broker
ActiveMQ embedded server is used as the broker.
Further jacoco maven plug-in is added to get the coverage report.
- Unit tests 
> Code coverage information
org.wso2.carbon.inbound.endpoint.protocol.jms.factory - coverage increased from 0% to 68%
org.wso2.carbon.inbound.endpoint.protocol.jms -  coverage increased from 0% to 28%
=> Add Unit tests for JMS Inbound EPs

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSUtils.java
When evaluating the headers which are set in the massage context, the NumberFormatException can be occured when parsing the value for following headers in the JMS inbound endpoint
JMS_EXPIRATION
JMS_PRIORITY
JMS_TIMESTAMP
The fix is to warn, as the flow should be continued.
=> Catch NumberFormatException when parsing headers

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/factory/JMSConnectionFactory.java
A NPE is thrown when creating a connection if the connectionFactory is null. This fix is to handle that scenario, when the connection is created by using the credentials. The connectionFactory can be null if it fails to create a connection factory for a given connection factory string
https://wso2.org/jira/browse/ESBJAVA-4950
=> Fix ESBJAVA-4950 NPE if the connectionFactory null

components/business-adaptors/hl7/org.wso2.carbon.business.messaging.hl7.common/pom.xml, components/business-adaptors/hl7/org.wso2.carbon.business.messaging.hl7.common/src/main/java/org/wso2/carbon/business/messaging/hl7/common/data/conf/HL7MessagePublisherConfig.java, pom.xml
HL7MessagePublisherConfig was using PublisherUtil from an old(org.wso2.carbon.bam.data.publisher.util)dependency.
This need to be fixed with the correct dependency : org.wso2.carbon.das.data.publisher.util
https://wso2.org/jira/browse/ESBJAVA-4889
Prevent class not found exception during runtime
Added the correct dependency 
N/A
N/A
For the older version of ESB 5.0.0 or EI. the HL7 common jar should be corrected with building pointing to the correct dependency
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
JDK 1.8, Linux environment
N/A
=> Fix data publisher dependency in HL7

components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/SAPConstants.java, components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/SAPTransportSender.java
The current implementation doesn't support transaction for the BAPIs. 
Resolves https://github.com/wso2/product-ei/issues/1601.  
Improve SAP adaptor implementation to support BAPI transaction.
A user has to explicitly define the following property in the mediation flow before invoking the SAP endpoint to run it as BAPI transaction.
`<property name="transport.sap.transactionCommit" scope="axis2" type="STRING" value="true"/>`
A user wants to invoke BAPI as a transaction.
https://docs.wso2.com/display/ESB481/SAP+Integration#SAPIntegration-AdditionalConfigurationParameter
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
“N/A”
“N/A”
- Unit tests …
=> Add transaction support for BAPI in SAP adaptor

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSPollingConsumer.java, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/config/inbound.properties
Add the functionality to JMS inbound endpoints to suspend and do reactivate polling when a certain number of mediation failures occurs.
> Add the functionality to JMS inbound endpoints to suspend and do reactivate polling when a certain number of mediation failures occurs.
> Fix https://github.com/wso2/product-ei/issues/1622
> Introduced two optional parameters, "transport.jms.RetriesBeforeSuspension" & "transport.jms.PollingSuspensionPeriod" to configure the Polling Suspension Limit and Polling Suspension Period.
Based on Polling Suspension Limit, polling will be suspended for Polling Suspension Period when the limit is attained.
> N/A
> This fix has introduced two new optional parameters, "transport.jms.RetriesBeforeSuspension" & "transport.jms.PollingSuspensionPeriod" to configure the …
=> Fix EI-1622.

components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/SAPConstants.java, components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/SAPTransportSender.java
Add login support for BAPI SAP calls.
Resolves https://github.com/wso2/product-ei/issues/1693
EI-1693: Add login support for BAPI calls
=> Add SapTransportSender to have login support for BAPI calls

components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/java/org/wso2/carbon/endpoint/ui/endpoints/address/AddressEndpoint.java, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/forms/addressEndpoint-form.jsp, components/mediation-ui/org.wso2.carbon.endpoint.ui/src/main/resources/web/endpoints/updatePages/addressEndpoint-update.jsp
> Fix for ESBJAVA-4015
> Add encoding attribute to the AddressEndpoint and make it visible in source view
> Introduce new property in AddressEndpoint class to hold encoding.
Add a new hidden field to hold encoding details in address endpoint edit web form.
So, when submitted (going to source view) it will bring encoding details to the source view.
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> JDK 8, Ubuntu 16.04
=> Fix for ESBJAVA-4015

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQUtils.java
Creating RabbitMQ exchange with auto delete property if it is defined.
> Create Rabbit MQ endpoint with the "rabbitmq.exchange.auto.delete" property if its declared.
Previously even if the property is read there were no implementations of it in code.
> Fix https://wso2.org/jira/browse/ESBJAVA-4932 , 
auto-deletion parameter ignored from a Rabbitmq Inbound Endpoint.
> Create the exchange with auto-delete paramter.
> N/A
>  N/A
>  This property description is documented incorrectly.
https://github.com/wso2/product-ei/issues/1772 
> N/A
> N/A
> N/A
-N/A
- N/A
> N/A
> None
> N/A
>  JDK 1.8
> https://www.rabbitmq.com/releases/rabbitmq-java-client/v2.2.0/rabbitmq-java-client-javadoc-2.2.0/com/rabbitmq/client/Channel.html
https://www.cloudamqp.com/blog/2015-09-03-part4-rabbitmq-for-beginners-exch …
=> Fix ESBJAVA-4932

pom.xml
> Update carbon commons and synapse versions to the latest for EI update 19 release
=> Update carbon commons and synapse versions

components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CachableResponse.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediator.java
> Resolve wso2/product-ei#943 
> Fix the incorrect handling of SOAP responses
> The issue doingRest parameter of the Axis2 MessageContext of the response was not included in the response from the cache mediator. Also the PR removes unused parameter.
> https://github.com/wso2/carbon-mediation/pull/843
>https://github.com/wso2/carbon-mediation/pull/887
>https://github.com/wso2/carbon-mediation/pull/889
>https://github.com/wso2/carbon-mediation/pull/949
=> Resolve wso2/product-ei#943

components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheManager.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediator.java
Make CacheManager class and CacheMediator methods (getDigestGenerator, setDigestGenerator) publicly accessible for developer studio usages.
Fixed https://github.com/wso2/product-ei/issues/1801
https://github.com/wso2/devstudio-tooling-esb/pull/312
https://github.com/wso2/carbon-mediation/pull/949
=> Fix wso2/product-ei#1801

components/mediation-ui/org.wso2.carbon.mediation.templates.ui/src/main/resources/web/templates/list_templates.jsp
Assigning the correct variable names and query parameters
>  Fix https://github.com/wso2/product-ei/issues/1806
> This fix assigns the correct variable names and query params for the request.
> N/A
> N/A
> N/A
>N/A
>N/A
> N/A
>N/A
N//A
> https://github.com/wso2-support/carbon-mediation/pull/125
> N/A
> JDK 1.8 , Ubuntu 16.04
>
=> Fix https://github.com/wso2/product-ei/issues/1806

components/application-mgt/org.wso2.carbon.application.mgt.synapse.ui/src/main/resources/web/synapse-apps/index.jsp
Add warning popup before editing the CApp artifacts including endpoints, APIs and sequences.
Fix https://wso2.org/jira/browse/ESBJAVA-4110
This was introduced for the consistency of editing CApp artifacts. With the normal flow (after listing each artifact type and edit), we get a warning popup before directing to the edit page. Same warning was added before editing APIs, sequences and endpoints using the flow List CApps -> Click on CApp -> Click on artifact.
=> Fix ESBJAVA-4110

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/management/WebsocketEndpointManager.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/ssl/InboundWebsocketSSLConfiguration.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/ssl/SSLHandlerFactory.java, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/config/inbound.properties
Here we are intoducing two parameters to configure preferred ciphers and SSL enabled protocols for WSS inbound endpoints
>  Enable configuring preferred Ciphers and SSL enabled protocols for WSS inbound endpoints.
> Fix https://github.com/wso2/product-ei/issues/1835
> Two new parameters,  "wss.ssl.protocols" and "wss.ssl.cipher.suites"  are introduced to configure the preferred Ciphers and SSL enabled protocols for WSS inbound endpoints.
> Docs need to incorporate these two newly added parameters.
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
> 
> 
> Describe …
=> Fix https://github.com/wso2/product-ei/issues/1835

components/application-mgt/org.wso2.carbon.application.mgt.synapse.ui/src/main/resources/web/synapse-apps/index.jsp
Direct to the message store content page when going through the CApp listing page. Without the fix it was directed an incorrect message store listing page.
Fix https://wso2.org/jira/browse/ESBJAVA-4163
=> Fix ESBJAVA-4163

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpServerWorker.java, pom.xml
When configuration has FORCE_SC_ACCEPTED and respond in a different path(like fault sequence)
two requests are comming on a same conntion receives swapped/incorrect response
Fix related to requests coming via http inbound endpoint
wso2/product-ei#1829
Fix response swapping when 202 accepted is added
Make sure correct response is sent to all requests
Fixed by validating the response state
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
https://github.com/wso2/wso2-synapse/pull/1043
N/A
JDK 1.8
N/A
=> Fix response swap when FORCE_SC_ACCEPTED present

components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CachableResponse.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediator.java
Fix ConcurrentModificationException error while sending a load using the cache mediator with a binary content.
Fixed https://github.com/wso2/product-ei/issues/1853
Replace hashmap with ConcurrentHashMap
https://github.com/wso2/carbon-mediation/commit/dbfb25b01c915319d034801709465ac8a6679140#diff-27b6b1e0d16b94fd7174706f75b33a7e
=> Fix product-ei#1853

components/business-adaptors/hl7/org.wso2.carbon.business.messaging.hl7.common/src/main/java/org/wso2/carbon/business/messaging/hl7/common/HL7ProcessingContext.java
> When a HL7 proxy receive parallel requests, the response ACKs are delivered  back in casual order without check the match of the **Message Control Id**.  This bug makes dangerous to use the WSO2' HL7 module in healthcare production environments (surgical operating rooms, laboratories, ecc.)
Resolves [issue928](https://github.com/wso2/carbon-mediation/issues/928), [issue1421](https://github.com/wso2/product-ei/issues/1421)
> The fix no longer takes the first message from the applicationResponses  BlockingQueue, but try to get the correct message with matching  control id. If no response match it retry every 1 until the timeout is triggered.
> I have implemented a new private method `pollMyResponse` that uses an `HL7Consumer` class (that implements java.util.function.Consumer<Message>) …
=> Fix EI-1421 for wrong HL7 ACK responses on multithreading requests

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSPollingConsumer.java, components/mediation-ui/org.wso2.carbon.inbound.ui/src/main/resources/config/inbound.properties
This introduces a new property to JMS inbound endpoint making enabling the reset connection after polling suspension possible
>  Enabling the JMS inbound to reset connection to the broker on polling suspension.
> Introduced a new property "transport.jms.ResetConnectionOnPollingSuspension" to JMS Inbound endpoint which will fascilitate this functionality.
> N/A
> 
>  Adding the newly added property to documentation. Created a doc JIRA internally.
> https://github.com/wso2-support/carbon-mediation/pull/133
=> Fix https://github.com/wso2/product-ei/issues/1877

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQConnectionConsumer.java
Remove duplicate QoS setting code and handle NumberFormatException when parsing QoS value.
Resolves #1040
Handle the NumberFormatException when parsing the QoS value.
Remove duplication QoS setting code.
When the parameter "rabbitmq.channel.consumer.qos" is not an integer value then log a warn message and create the InboundEndpoint (RabbitMQ) without QoS.
N/A
Previously when the QoS value is not an integer, then an exception is thrown and CApp file/ inbound endpoint is not deployed. In this fix, it will log a warning and deploy the artifact without QoS.
N/A
N/A
N/A
N/A
- Unit tests 
> Code coverage information
> Details about the test cases and coverage
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? 
yes
- …
=> Handle exception when Invalid value for RabbitMQ QoS

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/output/writers/XMLWriter.java
> Fix wso2/product-ei/issues/2391
> allow nested elements with same name in datamapper mediator
> Remove logic related to not writing start element tag if that element is
already written.
> JDK 8
=> Fix wso2/product-ei/issues/2391

components/mediators/publishEvent/org.wso2.carbon.mediator.publishevent/src/main/java/org/wso2/carbon/mediator/publishevent/PublishEventMediator.java
> isAsync() and getAsyncTimeout() methods are needed to use in dev-stuidio
=> change access access modifiers of async methods

pom.xml
Fixes the release build being failed due to the following:
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project command-mediator: Failed to deploy artifacts: Could not transfer artifact org.wso2.carbon.mediation:command-mediator:pom:4.6.98 from/to nexus-releases (http://maven.wso2.org/nexus/service/local/staging/deploy/maven2/): Connection to http://maven.wso2.org refused: Connection timed out
=> Fix release build failure

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/common/InboundRunner.java
> Resolves: wso2/product-ei/issues/2614
> Undeploy CAPPs with inbound endpoints without hanging the server
> The issue is faced due to the variable 'init' being not set to true in
clustered mode even after initialization of the inbound endpoint. This
causes the InboundRunner thread to run endlessly thus being unable to
stop it at undeployment.
=> Fix EI-2614

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQConnectionConsumer.java
When injecting sequence is defined as a registry sequence, when a temporary DB outage happened and recovered, inbound EP no longer works. This PR fixes the issue. 
Fix: https://github.com/wso2/product-ei/issues/2777
When Registry DB is disconnected, after cache timeout, the injecting sequence is not found, hence an exception is thrown. Upon the exception, inbound endpoint will handle the exception and delay the next re-try by 2 seconds. It will never give up retrying as there is no way to enable inbound endpoint again in production setup. 
Automatically recover inbound EP when registry DB outage (or any mediation exception) happened. 
N/A
N/A
N/A
N/A - there is no outside visible feature
Tolerate to DB outages 
- Unit tests 
N/A
N/A
- Followed secure coding standards …
=> Fix RabbitMQ IEP recovery upon mediation exceptions

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/pom.xml, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/mapper/XSLTMappingHandler.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/mapper/XSLTMappingResource.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/utils/DataMapperEngineConstants.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/DataMapperMediator.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/config/xml/DataMapperMediatorConstants.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/config/xml/DataMapperMediatorFactory.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/config/xml/DataMapperMediatorSerializer.java
Adding capability for the data mapper mediator to transform input XML messages to output XML messages using an XSLT engine to increase the performance. Previously all the message transformations were done using a JavaScript engine. Under the modification, only the xml to xml mapping will be handled using the xslt engine.
Related Issue: https://github.com/wso2/product-ei/issues/2745
Increase the performance of XML to XML message transformaion in datamapper mediator.
Related Issue : https://github.com/wso2/product-ei/issues/2745
https://github.com/wso2/product-ei/issues/2746
> Describe migration steps and platforms on which migration has been tested
All the datamapper mediators created up …
=> performance enhancement of datamapper

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/common/InboundRequestProcessorImpl.java
> If the JMS inbound configuration property coordination is set to false in a CApp, a delay is observed when undeploying it. Interrupt runner thread at undeployment on CApp.
=> Fix wso2/product-ei/issues/3048

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/file/FilePollingConsumer.java, pom.xml
Use url parameters processing logic in synapse code base.
Fixes wso2/product-ei#2779
Add capability to specify url parameters for MoveAfterProcess and MoveAfterFailure parameters in inbound endpoint.
Fixes wso2/product-ei#3088
Update synapse version to 2.1.7-wso2v85
Update commons vfs version to 2.2-wso2v5
=> Update FTP and FTPS configuration logic in inbound endpoint

components/mediation-ui/org.wso2.carbon.mediation.security.ui/src/main/resources/web/mediation_secure_vault/js/properties.js
Previuous PR
[wso2/carbon-mediation#851](https://github.com/wso2/carbon-mediation/pull/851) changed the secure vault filtering to filter !@#$%^&*()/+=:;<>'"?[]{}|\s, charachters from the key string. But, XML only need to filter & < > " ' characters. ESB versions had validation for key name starts with standard english character or number with any character in middle.
Fix https://github.com/wso2/product-ei/issues/3177
=> Allow valid characters for secure vault key

components/mediation-connector/org.wso2.carbon.mediation.connector.as4/pom.xml
This fix is needed for AS4 connector tests to work. Now the surefire pluging version is inherited from the parent pom.
=> Fix surefire plugin version in AS4 connector

components/mediation-admin/org.wso2.carbon.message.processor/src/main/java/org/wso2/carbon/message/processor/service/MessageProcessorAdminService.java, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/java/org/wso2/carbon/message/processor/ui/MessageProcessorAdminServiceClient.java, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/index.jsp, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/js/customModal.js, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/manageMessage.jsp, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/popMessageFromQueue.jsp, components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/redirectMessage.jsp, service-stubs/mediation-admin/org.wso2.carbon.message.processor.stub/src/main/resources/MessageProcessorAdminService.wsdl
To add extra functionality to the Message Processor to manage messages. The Message Processor in the current build doesn't manage messages, which can be difficult incase of a poison message scenario. The functionality to view, pop or enqueue the message will be a useful addition to managing messages from the processor
Add functionality to View, Pop and Enqueue the message to a different queue
Managing the message will only work while the message processor is inactive. Clicking the view message button brings up a new page which will display the exact message sent to the end-point. Pop message will send an acknowledgment to the associated queue. Enqueue will pop and redirect the message to a different queue
=> Fix for Issue #2740 Message Processor PoisonMessage handling

components/application-deployers/org.wso2.carbon.application.deployer.synapse/src/main/java/org/wso2/carbon/application/deployer/synapse/SynapseAppDeployer.java
Fixes the issue of APIs with a versioning strategy relying inside a Capp being not undeployed when undeploying the Capp.
Resolves: https://github.com/wso2/product-ei/issues/3340
Related to: https://github.com/wso2/carbon-mediation/pull/1125
=> Fix undeployment of versioned APIs

components/mediators/entitlement/org.wso2.carbon.identity.entitlement.mediator/pom.xml, features/mediator-features/entitlement-mediator-feature/org.wso2.carbon.identity.entitlement.mediator.feature/pom.xml, pom.xml
This is done to remove duplicate jars :- https://github.com/wso2/product-ei/issues/2061
Related PR https://github.com/wso2/carbon-commons/pull/345
=> Move identity entitlement stub dependency to carbon commons

features/synapse-features/org.apache.synapse.wso2.feature/pom.xml, pom.xml
```
<dependency>
<groupId>net.minidev</groupId>
<artifactId>accessors-smart</artifactId>
</dependency>
<dependency>
<groupId>org.ow2.asm</groupId>
<artifactId>asm</artifactId>
</dependency>
```
Is added and packed since json-smart has a transitive dependency on it.
=> Upgrade json smart version to 2.3

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/pom.xml, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/EndpointListenerLoader.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/APIResource.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/ConfigurationLoader.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/Constants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/InternalAPI.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/InternalAPIDispatcher.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpServerWorker.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/management/HTTPEndpointManager.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/java/internal/http/api/ConfigurationLoaderTestCase.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/java/internal/http/api/DispatcherTestCase.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/java/internal/http/api/SampleInternalAPI.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/java/internal/http/api/SampleResource.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/resources/internal/http/api/internal-apis.xml
We often find various components and extensions in EI, expose their functionality as HTTP APIs.
To build an API at the moment we are using MSF4J. But we already have a built-in HTTP transport that is used to serve HTTP traffic to the ESB server. 
Purpose of this PR is to introduce a framework to leverage that built-in HTTP transport to expose APIs needed by other components. 
Implementation was done using the HTTP Inbound concept. A default internal inbound called EI_INTERNAL_INBOUND_ENDPOINT is used to serve the traffic for these internal APIs. 
EI_INTERNAL_INBOUND_ENDPOINT is a hidden inbound endpoint that will not appear in the synapse configuration.
To enable this inbound endpoint we need to put the following to the synapse.properties file.
`internal.http.api.enabled=true`
Inbound …
=> Add Internal HTTP API framework 

components/mediation-ui/org.wso2.carbon.priority.executors.ui/src/main/resources/web/executors/design_executors.jsp, components/mediation-ui/org.wso2.carbon.priority.executors.ui/src/main/resources/web/executors/save_design.jsp
Validate values passed to `fowardTo` parameter to prevent open redirects,
and change form submission method of save_executor to `POST`.
=> validate `forwardTo` values in executors

components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.prometheus.publisher/pom.xml, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.prometheus.publisher/src/main/java/org/wso2/carbon/prometheus/publisher/model/PrometheusMetric.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.prometheus.publisher/src/main/java/org/wso2/carbon/prometheus/publisher/publisher/MetricCollector.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.prometheus.publisher/src/main/java/org/wso2/carbon/prometheus/publisher/publisher/MetricPublisher.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.prometheus.publisher/src/main/java/org/wso2/carbon/prometheus/publisher/service/MetricAPI.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.prometheus.publisher/src/main/java/org/wso2/carbon/prometheus/publisher/service/MetricResource.java, components/mediation-monitor/mediation-data-publisher/org.wso2.carbon.prometheus.publisher/src/main/java/org/wso2/carbon/prometheus/publisher/util/PrometheusPublisherConstants.java, components/mediation-monitor/mediation-data-publisher/pom.xml, features/mediation-monitor-features/mediation-data-publisher-features/pom.xml, features/mediation-monitor-features/mediation-data-publisher-features/prometheus-publisher-feature/pom.xml, pom.xml
> Enable ESB to expose statistical data to Prometheus.
> [#3399](https://github.com/wso2/product-ei/pull/3399)
> [#3229](https://github.com/wso2/product-ei/issues/3229)
=> Add feature to expose statistical data from ESB to Prometheus

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/DataMapperMediator.java
> Enable to add mapping resource from outside
> This setter is used in EI-Tooling to inject a pre-built mappingResourse to datamapper.
> Add new setter
=> Add new setter to mappingResource in datamapper

components/mediation-initializer/org.wso2.carbon.mediation.light.initializer/src/main/java/org/wso2/carbon/mediation/initializer/ServiceBusInitializer.java
> This will reduce unnecessary logs for ESB mediation related console logs.
> https://github.com/wso2/product-ei/issues/3653
> https://github.com/wso2/micro-integrator/issues/52
=> Change info logs to debug logs to reduce logs at server startup

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/ConfigurationLoader.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/Constants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpServerWorker.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/java/internal/http/api/ConfigurationLoaderTestCase.java
The relevant internal API is enabled only if the system property is set.
System Property Name :- enable + <API_NAME>
Also this PR enable to send 404 if the Internal API is not found.
=> Enable the internal API if only the relevant system property is set & Return 404 if not found

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint.persistence/src/main/java/org/wso2/carbon/inbound/endpoint/persistence/PersistenceUtils.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/EndpointListenerLoader.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/management/HTTPEndpointManager.java
This PR is added to check the port offset and start the internal APIs with port offset if it is specified.
Also starts the Internal Endpoint Listener only if at least one API is enabled.
=> Honour port offset in internal APIs if it is specified & Start Endpoint Listener if at least one API is enabled.

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/EndpointListenerLoader.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/ConfigurationLoader.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/Constants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpServerWorker.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/management/HTTPEndpointManager.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/java/internal/http/api/ConfigurationLoaderTestCase.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/java/internal/http/api/DispatcherTestCase.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/test/resources/internal/http/api/internal-apis.xml
>  Facilitate HTTPS Listener for Internal APIs.
> Facilitate HTTPS Listener for Internal APIs.
>  Strart the HTTPS Listner also if the API has protocol https.
**Updated Internal API Config**
```
<internalApis>
<apis>
<api name="PrometheusApi" protocol="http" class="org.wso2.carbon.prometheus.publisher.service.MetricAPI"/>
<api name="ManagementApi" protocol="https"
class="org.wso2.carbon.micro.integrator.management.apis.ManagementInternalAPI"/>
</apis>
<sslConfig>
<parameter name="keystore">
<KeyStore>
<Location>repository/resources/security/wso2carbon.jks</Location>
<Type>JKS</Type>
<Password>wso2carbon</Password>
<KeyPassword>wso2carbon</KeyPassword>
</KeyStore>
</parameter>
<parameter name="truststore">
<TrustStore>
<Location>repository/resources/security/client-truststore.jks</Location> …
```
=> Add HTTPS Listner for Internal Apis

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.target.ui/src/main/resources/web/target-mediator/js/mediator-util.js
> Fixes https://github.com/wso2/product-ei/issues/3812
>When trying to add an endpoint as a clone target, it rejects the input data and shows empty tags. 
It happens because the radio button gets deselected after refreshing the page. 
> Add an endpoint as a clone target and able to successfully switch between design view and source view.
> Not letting the radio button to get deselected when refreshing the page
=> Fix endpoint radio button getting deselected when adding endpoint as the clone target 

features/synapse-features/org.apache.synapse.wso2.feature/pom.xml, pom.xml
commons-text is packed with kernel itself.
Reverting https://github.com/wso2/carbon-mediation/pull/1137/commits/c7daa7100e56e2f961db1b42d5adb26a640a990d
=> Remove packing commons-text from carbon-mediation.

components/org.wso2.carbon.integrator.core/src/main/java/org/wso2/carbon/integrator/core/handler/RESTBasicAuthHandler.java
> $subject. Fixes https://github.com/wso2/product-ei/issues/4063
> Get the RESTBasicAuthHandler work with APIs.
> In the code we are taking the credentials from **Authorization** header and decoding it and validating it against user name and password obtained from user store.
After reading the header value, we are doing a substring function which is unnecessary and causing this issue.  We don't need to substring as the **processSecurity** method expects the value of the header itself.
This PR removed the redundant substring function which is causing the issue.
=> Fix default RESTBasicAuthHandler

features/synapse-features/org.apache.synapse.wso2.feature/pom.xml, pom.xml
Reverting wso2/carbon-mediation#1248 since these changes should be merged when releasing the mediation and after upgrading kernel to 4.4.41.
=> Revert "Remove packing commons-text from carbon-mediation."

components/application-deployers/org.wso2.carbon.application.deployer.synapse/src/main/java/org/wso2/carbon/application/deployer/synapse/FileRegistryResourceDeployer.java, components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/MicroIntegratorRegistry.java, components/mediation-registry/org.wso2.carbon.mediation.registry/src/test/java/org/wso2/carbon/mediation/registry/TestMicroIntegratorRegistry.java, pom.xml
The metadata related to registry resource is stored in a separate file named <resource_file_name>.meta inside the ".metadata" dir which is located where the registry resource is.
At the moment media type is the only metadata stored.
Example:
```
|registry/
| ---- | governance/
| -------- | custom1/
| ------------ | checkJsScript.js
| ------------ | .metadata/
| ---------------- | checkJsScript.js.meta
```
Fixes wso2/micro-integrator#180
=> Store media type of registry resources in file and retrieve

components/business-adaptors/sap/src/main/java/org/wso2/carbon/transports/sap/bapi/Axis2RFCHandler.java
When the XML transformation is happening inside the workerpool execution run method, we can observe XML values being mixed up without any patterns. To avoid this behavior we perform all the XML transformation related operations before calling the execute method of worker pool.
fixes #wso2/product-ei/4086
=> Fix BAPI message XML transformation

components/org.wso2.carbon.integrator.core/src/main/java/org/wso2/carbon/integrator/core/handler/RESTBasicAuthHandler.java
Sometimes we can have an authorization header starting with "Basic ". Without this "if" condition, WSO2 returns an ArrrayIndexOutOfBoundsException because "decodedCredentials" returns a String without ":" inside. It can't split with ":" so username and password are null.
Purpose : 
Do a correction to the REST Basic Auth Handler
=> Correction credentials starting with "Basic "

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSPollingConsumer.java
Related to wso2/product-ei#4735
A deadlock possibility is there in the JMSPollingConsumer destroy method when two thread concurrently call that particular method on the same JMSPollingConsumer object. This PR will synchronise the method to avoid deadlocks.
=> Synchronize JMSPollingConsumer destroy to avoid deadlocks

components/mediation-admin/org.wso2.carbon.endpoint/src/main/java/org/wso2/carbon/endpoint/EndpointServiceComponent.java, components/mediation-admin/org.wso2.carbon.localentry/src/main/java/org/wso2/carbon/localentry/LocalEntryAdminServiceComponent.java, components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/APIServiceComponent.java, components/mediation-admin/org.wso2.carbon.sequences/src/main/java/org/wso2/carbon/sequences/internal/SequenceEditorServiceComponent.java
In order to do in-memory call, we do not need to do an HTTP call within JVM 
Reduce no of HTTP calls on API creation
=> Osgifying Admin services

components/mediation-ui/org.wso2.carbon.mediation.security.ui/src/main/java/org/wso2/carbon/mediation/security/vault/ui/PropertiesServiceClient.java
> Fix: https://github.com/wso2/product-ei/issues/4774
Secure vault keys are listed according to the alphabetical order. When trying to add an entry to the end of the list on page 2 and onwards, the entry is getting successfully added, but not getting displayed in the Management Console. This PR resolves this issue since there is no need to subtract 1 (- 1) when calculating the length of the property list to be shown on the page.
=> Fix last entry added to the Secure Vault is not shown in the Management Console

components/mediation-ui/org.wso2.carbon.rest.api.ui/src/main/resources/web/api/delete_api_ajaxprocessor.jsp, components/mediation-ui/org.wso2.carbon.rest.api.ui/src/main/resources/web/api/index.jsp
> Change the delimiter which is used to seperate API names.
Since : is already used in API names with versions.
Fixes wso2/product-ei/issues/4126
=> Fix wso2/product-ei/issues/4126

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/input/readers/CSVInputReader.java
When comma separated values are enclosed in double quotes it needs to be treated as single field in CSV. But currently as we are just splitting by regex "," it is treated as new field.
This PR is to fix that issue by parsing the CSV using CSV Reader.
Fixes wso2/product-ei#4788
=> Fix comma separated values being treated as new fields in CSV.

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSInjectHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSPollingConsumer.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSUtils.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/factory/CachedJMSConnectionFactory.java
Fixes : https://github.com/wso2/product-ei/issues/4796
Issue JMS session.recover() upon mediation failures 
Need to add description on the issue to the documentation 
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
=> Fix [EI-4796] JMS session.recover() upon mediation failure

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.foreach.ui/pom.xml, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.foreach.ui/src/main/java/org/wso2/carbon/mediator/foreach/ForEachMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.foreach.ui/src/main/resources/web/foreach-mediator/update-mediator.jsp, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.header.ui/pom.xml, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.header.ui/src/main/java/org/wso2/carbon/mediator/header/HeaderMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.header.ui/src/main/resources/web/header-mediator/update-mediator.jsp
Native JSONpath support was introduced for Header mediator (https://github.com/wso2/wso2-synapse/pull/1364) and Foreach mediator(https://github.com/wso2/wso2-synapse/pull/1377). 
This PR adds the jsonpath support in the management console for the above mediators.
Resolves https://github.com/wso2/product-ei/issues/4797
Related to https://github.com/wso2/product-ei/issues/4121
=> Add jsonpath support for Header and Foreach mediators in Management console

components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/SecureVaultLookupHandlerImpl.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/SecurityServiceHolder.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/SynapseSecurityerviceComponent.java
> Fixes: https://github.com/wso2/product-ei/issues/4798
When we define the message store password as shown below,
`<parameter name="store.rabbitmq.password">{wso2:vault-lookup('user.password')}</parameter>` the password should be resolved from secure vault. 
According to our implementation, we resolve the password value while initializing the message store [[1]](https://github.com/wso2/wso2-synapse/blob/1f67e293d4947fd87a70e2b13c70a7d73f9992d8/modules/core/src/main/java/org/apache/synapse/message/store/impl/rabbitmq/RabbitMQStore.java#L175) during server startup. The resolve method [[2]]( https://github.com/wso2/wso2-synapse/blob/1f67e293d4947fd87a70e2b13c70a7d73f9992d8/modules/core/src/main/java/org/apache/synapse/util/resolver/SecureVaultResolver.java#L65) takes the configuration value …
=> Fix secure vault support for rabbitMQ message store

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSPollingConsumer.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSUtils.java
Fixes: https://github.com/wso2/product-ei/issues/4852
According to JMS specification 1.0.2, If a session is transacted, message acknowledgement is handled automatically by commit and recovery is handled automatically by the rollback. Session recover can not be used in a transacted session.
When CLIENT_ACKNOWLEDGE mode is used, A session’s recover method is used to stop a session and restart it with its first unacknowledged message.
More details on this can be found in [1].
The test case is failing because it is configured with SessionTransacted parameter true.`<parameter name="transport.jms.SessionTransacted">true</parameter>`
After the above fix, the flow goes and executes recoverSession() method. As we cannot execute session.recover() in a transacted session, the test case is failing. …
=> Add check for transacted session before invoking recoverSession method

.travis.yml
Enforce travis maven version to 3.6 since not building in 3.6.2
=> Enforce travis maven version

components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/manageMessageSamplingProcessor.jsp
> Reverts: https://github.com/wso2/carbon-mediation/pull/1331
> Fixes: wso2/product-ei#4884, https://github.com/wso2/product-ei/issues/4690
=> Fix max.store.connection.attempts config is missing for sampling processor

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/generic/GenericConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/generic/GenericPollingConsumer.java
…
> When we are using SF Salesforce StreamData inbound connector with the analytics, It will publish null information to the analytics server. Since the connector haven't populated the inbound name and other information while initializing the connector inbound endpoint. 
> This fix will set the inbound name to the message context while initializing the inbound. 
> We can log the analytics event in the analytics worker node by adding the below log to the <EI_HOME>/wso2/analytics/wso2/worker/deployment/siddhi-files$ EI_Analytics_StatApp.siddhi file.
> @sink(type='log')
Ex:
> @sink(type='log')
> define stream PreProcessedESBStatStream (componentId string, componentName string, componentType string, duration long, faultCount int, startTime long, entryPoint string, metaTenantId int);
without …
=> fix Null values were being published to the analytics when using Salesforce StreamData inbond connector

components/mediation-initializer/org.wso2.carbon.mediation.initializer/src/main/java/org/wso2/carbon/mediation/initializer/multitenancy/TenantServiceBusInitializer.java
The registry.xml file is not copied for newly added tenants intermittently.
The reason for this behaviour is that the TenantServiceCreator class of the gateway executes before the TenantServiceBusInitializer class of carbon-mediation. When this happens the TenantServiceCreator creates the synapse-configs directory, and the createTenantSynapseConfigHierarchy method of TenantServiceBusInitializer which is responsible for copying the registry.xml is not executed because the synapse-configs directory has already been created.
Fixes wso2/product-apim#7500
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email …
=> fix not adding registry.xml for tenants intermittently

components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.property.ui/src/main/resources/web/property-mediator/edit-mediator.jsp
Property mediator does not allow dynamic names at the moment. It is supported for other mediators - e.g. sequence mediator. This is a useful feature to have.
```
<property name="{get-property('propertyName')}" expression="$ctx:propertyValue" />
<property name="{$ctx:propertyName}" expression="$ctx:propertyValue" />
<property name="{json-eval({$ctx:propertyName})}" expression="$ctx:propertyValue" />
```
Related issue- https://github.com/wso2/product-ei/issues/3300
=> Add support for dynamic names of property mediator in management console

components/mediators/entitlement/org.wso2.carbon.identity.entitlement.mediator/src/main/java/org/wso2/carbon/identity/entitlement/mediator/EntitlementMediator.java
XACML advice information is not available for the mediation sequences. Therefore this PR will add advice information into the message context as a property
issue: wso2/product-apim#8093
=> Add xacml advice to msg context

components/mediation-admin/org.wso2.carbon.endpoint/src/main/java/org/wso2/carbon/endpoint/service/EndpointAdmin.java, components/mediation-admin/org.wso2.carbon.localentry/src/main/java/org/wso2/carbon/localentry/service/LocalEntryAdmin.java, components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/service/RestApiAdmin.java, components/mediation-admin/org.wso2.carbon.sequences/src/main/java/org/wso2/carbon/sequences/services/SequenceAdmin.java, pom.xml
Introduced a new synapse property ```synapse.runtime_artifacts.save.local.file``` to skip saving runtime artifacts of API manager gateway to the local directory.
Used with the new feature: https://github.com/wso2/product-apim/issues/8246
=> Introduced a new Synapse property to skip saving runtime artifacts to local

components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/RefreshAccessToken.java, components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/RefreshAccessTokenWithExpiry.java
Add class mediator to be used by connectors to refresh access tokens
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
=> Add RefreshAccessToken Class Mediator

components/mediation-admin/org.wso2.carbon.mediation.security/pom.xml, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/SynapseSecurityerviceComponent.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/external/ExternalVaultConfigLoader.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/external/ExternalVaultException.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/external/ExternalVaultLookupHandler.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/external/hashicorp/HashiCorpVaultConstant.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/external/hashicorp/HashiCorpVaultLookupFunction.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/external/hashicorp/HashiCorpVaultLookupHandlerImpl.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/external/hashicorp/HashiCorpVaultLookupXPathFunctionProvider.java, pom.xml
$subject.
This PR introduces feature integrating HashiCorp secure vault to the WSO2 EI. From this feature, we can fetch secrets from the HashiCorp vault by extending the existing vault-lookup function in the runtime as follows.
```
<property name="HashiCorpSecret" expression="hashicorp:vault-lookup('path-to-secret', 'secret-key')" />
```
Also, If HashiCorp secrets are saved under a specific namespace, we can extend the above expression as follows,
```
<property name="HashiCorpSecret" expression="hashicorp:vault-lookup('namespace', 'path-to-secret', 'secret-key')" />
```
Here, the namespace is an optional parameter.
Related issue: https://github.com/wso2/product-ei/issues/5214
=> Add extension for HashiCorp external vault resolver

components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/external/hashicorp/HashiCorpVaultLookupXPathFunctionProvider.java, components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/xpath/SecureVaultLookupXPathFunctionProvider.java, pom.xml
This issue happens since function providers are registered with Qnames
and since Qnames do not consider prefix in equals or hashcode functions
the HashiCorp and SecVault function provides were registered under the
same Qname. So change function provider registration to avoid this.
Fixes: https://github.com/wso2/product-ei/issues/5256
=> Fix https://github.com/wso2/product-ei/issues/5256

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSInjectHandler.java
This PR adds the following JMS properties into transport headers of Inbound Endpoints
- JMS_MESSAGE_ID
- JMS_PRIORITY
- JMS_EXPIRATION
- JMS_DELIVERY_MODE
- JMS_DELIVERY_TIME
- JMS_REDELIVERED
- JMS_DESTINATION
- JMS_REPLY_TO_DESTINATION
- JMS_MESSAGE_TYPE
- JMS_COORELATION_ID
Fixes https://github.com/wso2/product-ei/issues/5304
=> Set missing JMS properties into transport headers of Inbound Endpoints

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSInjectHandler.java
getJMSDeliveryTime() method is not implemented in ActiveMQMessage class. Hence, NoSuchMethodError may occur for javax.jms.Message.getJMSDeliveryTime().
=> Fix NoSuchMethodError for javax.jms.Message.getJMSDeliveryTime()

components/mediators/fastXSLT/org.wso2.carbon.mediator.fastXSLT/src/main/java/org/wso2/carbon/mediator/fastXSLT/FastXSLTMediator.java
When the fastXSLT mediator is used, there can be a situation where the below thread is stuck in an infinite loop because the flush content method returns immediately when the rawSerializationComplete is true [1].
```
"PassThroughMessageProcessor-71" #538 prio=5 os_prio=0 tid=0x00007f9d0c166000 nid=0x49e1 runnable [0x00007f9cf5099000]
java.lang.Thread.State: RUNNABLE
at org.apache.synapse.transport.passthru.Pipe$ByteBufferOutputStream.write(Pipe.java:572)
at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
- locked <0x0000000089212918> (a java.io.OutputStreamWriter)
at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:135)
at …
```
=> Fix passthrough threads being stuck in an infinite while loop

components/mediation-initializer/org.wso2.carbon.mediation.initializer/src/main/java/org/wso2/carbon/mediation/initializer/multitenancy/TenantServiceBusInitializer.java, components/mediation-initializer/org.wso2.carbon.mediation.initializer/src/main/java/org/wso2/carbon/mediation/initializer/utils/ConfigurationHolder.java
Whenever the lazy loading happens for a tenant, a new SynapseConfiguration object will be created. But, the older SynapseConfiguration reference that was created for a particular tenant is not getting cleaned. Hence, there can be an OOM issue after sometimes when there are multiple accumulated SynapseConfiguration instances in the memory.
To overcome the OOM issue, here, the localRegistry map in the older instance, which can bear the biggest object in the SynapseConfiguration instance is cleaned upon a new SynapseConfiguration is created. But, the original issue of cleaning out the older SynapseConfiguration instances is not addressed in this PR.
Fixes wso2/product-ei#5312
=> Fix OOM issue due to multiple SynapseConfiguration instances created for a single tenant

.gitignore, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.cache.ui/src/main/java/org/wso2/carbon/mediator/cache/ui/CacheMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.cache.ui/src/main/resources/org/wso2/carbon/mediator/cache/ui/i18n/Resources.properties, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.cache.ui/src/main/resources/web/cache-mediator/edit-mediator.jsp, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.cache.ui/src/main/resources/web/cache-mediator/update-mediator.jsp, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediator.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediatorFactory.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CacheMediatorSerializer.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/CachingConstants.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/main/java/org/wso2/carbon/mediator/cache/digest/HttpRequestHashGenerator.java, components/mediators/cache/org.wso2.carbon.mediator.cache/src/test/java/org.wso2.carbon.mediator.cache/CacheMediatorTest.java
- Introduce **headersToIncludeInHash** attribute to the cache mediator so the users can define specifically which headers need to be considered for creating the request hash.
- This attribute is executed along with the headersToExcludeInHash thus maintaining backward compatibility.
- Priority will be assigned to the newly introduced headersToIncludeInHash property. If proper values have been defined for the headersToIncludeInHash property, the cache finder will operate in header inclusion mode.
- If no values have been defined for both headersToIncludeInHash and headersToExcludeInHash attributes, finder will operate in the header exclusion mode (nothing will be excluded).
```
<cache collector="false" timeout="3600" maxMessageSize="2000">
<onCacheHit sequence="cache-hit-seq"/>
<protocol …
```
=> Add headersToIncludeInHash attribute to cache mediator.

pom.xml
Upgrading the FreeMarker lib version in the smooks library to 2.3.30 to make it compatible with the FreeMarker implementation in the PayloadFactory mediator
https://github.com/wso2/orbit/pull/442
=> Upgrading FreeMarker version of the Smooks library

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebSocketClientHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java
This pr add supports for web socket inbound endpoint to add custom properties from channel context
to the synapse message context. These can be set in one of the previous pipeline handler
Related issue : https://github.com/wso2/product-apim/issues/9768
=> Update web socket endpoint to accommodate custom properties from channel context

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/SubprotocolBuilderUtil.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConnectionFactory.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConstants.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketTransportSender.java
**Description**
If the sequence file has the property set as following, graphql subscriptions can work via websockets with this change in this pull request.
`<property name="websocket.subprotocol" value="graphql-ws" scope="axis2"/>`
=> Handle graphql-ws content type

components/mediation-ui/org.wso2.carbon.proxyadmin.ui/src/main/resources/web/proxyservices/index.jsp
Changing the XSS for inline Wsdl from HTML to JavaScript encoding. Since the WSDL is an XML document, using the HTML encoding makes the document unreadable. The malicious part that could be inside of that document is a JavaScript code. Therefore changing the encoding to JavaScript.
Fixes: wso2/product-ei#5357
=> Fixing source view accessing issue in EI management console

components/mediation-admin/org.wso2.carbon.mediator.service/src/main/java/org/wso2/carbon/mediator/service/ui/AbstractMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.clazz.ui/src/main/java/org/wso2/carbon/mediator/clazz/ClassMediator.java, components/mediation-ui/mediators-ui/org.wso2.carbon.mediator.clazz.ui/src/main/resources/web/class-mediator/edit-mediator.jsp
> Allow class mediator to have empty properties in the management console.
Fixes wso2/product-ei/issues/5306
=> Add empty property support for class mediator in UI

.github/workflows/coverage.yml, codecov.yml
> $subject
Codecov merges unit and integration test coverages.
Coverage information will be shown at https://app.codecov.io/gh/wso2/carbon-mediation
=> Enable Codecov coverage reports for unit tests

components/mediation-connector/org.wso2.carbon.connector.core/pom.xml, pom.xml
Add the javax.activation package under import packages to fix the NoClassDefFoundError thrown when a user tries to send an email with the Email Connector.
Fixes wso2/micro-integrator#1990
=> Add the javax.activation package to fix the NoClassDefFoundError

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint.persistence/src/main/java/org/wso2/carbon/inbound/endpoint/persistence/InboundEndpointsDataStore.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/https/InboundHttpsListener.java
When You start two APIM packs with port offset we couldn't offset the inbound http,https ports due to portoffset config didn't apply to those ports
resolves #https://github.com/wso2/product-apim/issues/10412
resolves #https://github.com/wso2/product-apim/issues/10461
=> disable registry update on inbound endpoints

components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/external/ExternalVaultConfigLoader.java
This is to fix https://github.com/wso2/product-apim/issues/10198
external-vaults.xml file is not shipped with the product by default and hence it shows warn message in the server startup. The fix is to make it debug logs.
=> Change log level to fix APIM:10198

components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/service/RestApiAdmin.java, components/mediation-admin/org.wso2.carbon.rest.api/src/test/java/org/wso2/carbon/rest/api/RestApiAdminUnitTest.java
This is to fix https://github.com/wso2/product-apim/issues/10198
When there are overloading methods in admin services axis2 doesn't add method to the map and prints a warn message. This is to eliminate that error
=> Change overloading methods

components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/src/main/java/org/wso2/carbon/mediation/transport/handlers/PassThroughNHttpGetProcessor.java
**Description**
commitResponseHideExceptions method was called before closing the outputStream. Because of that 200 OK responses with empty bodies were sent to the client. With this fix, the outputStream is closed before calling commitResponseHideExceptions.
Fixes wso2/product-ei#5385
=> Fixes wso2/product-ei#5385

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpListener.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/https/InboundHttpsListener.java
This PR introduces a synapse property **inbound.port.offset.enable**  to set whether to add the server port offset value for Inbound Endpoints or not.
Related issue https://github.com/wso2/micro-integrator/issues/2223
=> Introduce a synapse property to manage port offset for Inbound Endpoints

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundCorrelationEnabledHttpServerWorker.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpServerWorker.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/http/InboundHttpSourceHandler.java
$subject.
Currently Inbound Endpoints in Carbon mediation does not have Correlation logs support. This PR will add support for Inbound Endpoints
=> Enable correlation log support for inbound endpoints

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSInjectHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/jms/JMSUtils.java
> Add hyphen replace support for inbound endpoints.
Inject inbound endpoint properties to the message context.
Fixes wso2/product-ei/issues/5409
Fixes wso2/product-ei/issues/5402
=> Add hyphen replace / inbound properties support

components/mediation-admin/org.wso2.carbon.mediation.library/src/main/java/org/wso2/carbon/mediation/library/RegistryCachingHandler.java
Fixes: https://github.com/wso2/product-ei/issues/5415
For renaming, moving and copying of registry resources, resourcePath is not set in the RequestContext in the kernel.
Hence we have to use the sourcePath to resolve and clear cache.
=> Fix NPE when resource path is unavailable.

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/file/FilePollingConsumer.java, pom.xml
For cases where the last modified time stamp needs to be ignored, use the property as follows. Default value of this parameter is true, hence timestamp will be set by default
```
<parameter name="transport.vfs.UpdateLastModified">false</parameter>
```
Fixes: wso2/micro-integrator#2318
=> Add transport.vfs.UpdateLastModified property to VFS

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConstants.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketTransportSender.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java
Fix the following issues occurring when disconnecting websocket clients.
1. Creation of a new connection when disconnecting a websocket client
2. Empty soap message being sent to the server when disconnecting a websocket client
Related Issue: https://github.com/wso2/product-apim/issues/11325
[WUM] 4.7.61 branch - https://github.com/wso2-support/carbon-mediation/pull/590
[U2] 4.7.61 branch - https://github.com/wso2-support/carbon-mediation/pull/591
=> Fix Issues Occurring When Disconnecting Websocket Clients

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebSocketClientHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java
As per the current implementation, the WSO2 server is not responding to the PING message of the backend (WebSocket) server and hence the server gets disconnected from the client(WSO2 server). In this case, the WSO2 server has to create a new connection for each and every message that is sent from the client (WSO2 server) to the backend server. This PR fixes that issue by sending a PONG from the WSO2 server as a response to the backend server's PING message.
Fixes: wso2/product-apim#11160
=> Send PONG as a response to the backend server's PING

features/inbound-endpoints/org.wso2.carbon.inbound.endpoints.server.feature/pom.xml, pom.xml
This PR adds the missing `netty-tcnative-classes` runtime dependency.
=> Add missing runtime dependency for netty

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketChannelInitializer.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketConfiguration.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/management/WebsocketEndpointManager.java
Fixes: https://github.com/wso2/product-apim/issues/12444
Refer https://netty.io/4.0/api/io/netty/handler/timeout/IdleStateHandler.html for more information regarding these params.
Considering the event time in seconds,
* For inbound WS calls, override `apim.ws.dispatch.idleTime` in deployment.toml
* For inbound WSS calls, override `apim.wss.dispatch.idleTime` in deployment.toml
* For outbound WS calls, override `apim.ws.outflow.dispatch.idleTime` in deployment.toml
* For outbound WSS calls, override `apim.wss.outflow.dispatch.idleTime` in deployment.toml
You may have to override the "userEventTriggered" of "WebsocketHandler" class after extending from it.
Example:
An example that terminates when there is no outbound traffic and inbound traffic based on the param values set above
```java …
```
=> Adding the support for the WS to handle inbound and outbound idle connection timeout

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/pom.xml, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConstants.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketTransportSender.java
> When the web-socket backend becomes unavailable, the corresponding WS client connection needs to be terminated.
> Fixes: https://github.com/wso2/micro-integrator/issues/2657
=> Close WS client connection upon target connection failure.

components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/rest/api/swagger/OpenAPIProcessor.java
> Only path parameters need to be deleted upon update. Query parameters cannot be deleted as they do not exist in the URL.
=> Stop query parameter deletion from swagger upon update.

components/mediation-commons/pom.xml, components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/correlation/SynapseConfigurableCorrelationLogService.java, pom.xml
> Fix: wso2/api-manager#275
> Fix: wso2/api-manager#340
> A correlation log service component is added to bridge between the carbon kernel layer and the synapse layer. 
This will enable the correlation log manager in the carbon kernel to manipulate the correlation config dataholder for synapse pass through transport in the synapse layer
=> Add a correlation log service to bridge carbon kernel and synapse

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebSocketClientHandler.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConnectionFactory.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketResponseSender.java
$subject. Fixes https://github.com/wso2/api-manager/issues/675
This is achieved via half-closure in Netty [0] [1].
> allowHalfClosure: 
Sets whether the channel should not close itself when its remote peer shuts down output to make the connection half-closed. If true the connection is not closed when the remote peer shuts down output. Instead, [ChannelInboundHandler.userEventTriggered(ChannelHandlerContext, Object)](https://netty.io/4.1/api/io/netty/channel/ChannelInboundHandler.html#userEventTriggered-io.netty.channel.ChannelHandlerContext-java.lang.Object-) is invoked with a [ChannelInputShutdownEvent](https://netty.io/4.1/api/io/netty/channel/socket/ChannelInputShutdownEvent.html) object. If false, the connection is closed automatically.
Users **must** set the following property in the …
=> Websocket abrupt server closure to client

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebSocketClientHandler.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConstants.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketTransportSender.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/test/java/org/wso2/carbon/websocket/transport/WebSocketClientHandlerTest.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/pom.xml, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketChannelInitializer.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketConfiguration.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketResponseSender.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/management/WebsocketEndpointManager.java
Adds support for pass through control frames.
Adding the below config to the inbound endpoint definition for websockets will make sure that control frames such as Close frames, Ping frames and Pong frames will be passed through between the backend and the client. The default behavior will be to block these frames.
<parameter name="ws.pass.through.control.frames">true</parameter>
> Fix https://github.com/wso2/api-manager/issues/590
> Related PRs: https://github.com/wso2/carbon-apimgt/pull/11625
=> Add pass through control frames support

components/mediation-commons/pom.xml, components/mediation-commons/src/main/java/org/wso2/carbon/mediation/commons/correlation/SynapseConfigurableCorrelationLogService.java
> Fix: wso2/api-manager#275
> Fix: wso2/api-manager#340
> A correlation log service component is added to bridge between the carbon kernel layer and the synapse layer. 
This will enable the correlation log manager in the carbon kernel to manipulate the correlation config dataholder for synapse pass through transport in the synapse layer
=> Add log service for synapse to bridge synpase and kernel

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebSocketClientHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketResponseSender.java
Previously in [PR](https://github.com/wso2/carbon-mediation/pull/1644) we introduced closing the websocket client by calling the fault sequence, when the server is shutdown without sending a closeFrame, using `userEventTriggered` method.
This PR introduces the following changes.
When a websocket connection is established, if we kill the server that is behind the connection using `tcpkill`, it will call the `exceptionCaught` method, and we have to call the fault sequence in that case as well. This PR introduces this particular change.
> **Note:** `exceptionCaught` captures not only server terminations like this, but also cases like `ERROR_CODE = 1009, ERROR_MESSAGE = Message too big` (See PR [2]). 
In any case, at the end of `exceptionCaught` method, we call the fault sequence.
The …
=> Add implementation to close the websocket client upon exceptionCaught

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebSocketClientHandler.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConnectionFactory.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConstants.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketTransportSender.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/utils/LogUtil.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketChannelContext.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/WebsocketLogUtil.java
To add more information in the response path in WebSocket API invocations and add more debug logs to print in WebSocket API invocation flows.
Fixes: https://github.com/wso2/api-manager/issues/567
Fixes: https://github.com/wso2/api-manager/issues/540
- Added channel Id for the entire channel (one per each WebSocket connection). We will expose this channelId as a synapse property and from the customer's WebSocket log handler. This ID can be logged with every frame. All the Websocket frames that are passing through this channel will bear this ID.
Please note that this ID is not unique to each frame that we send in a channel, but is common to all the frames **but unique for a channel.**
- Besides that API_PROPRTIES map is also added as a synapse property
Logged information via log mediator: …
=> Add more API information WebSocket API invocation flows

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebSocketClientHandler.java
fix https://github.com/wso2/api-manager/issues/1122
With the changes of https://github.com/wso2/carbon-mediation/pull/1648/files, we are releasing the reference counter when a ping websocket frame is received to WebsocketClientHandler. However WebsocketClientHandler extends the SimpleChannelInboundHandler.
If `SimpleChannelInboundHandler` is used no need to anything special to release of resources. It releases resources automatically. Should not store references to any message for later use, those become invalid.
=> Remove additional reference count release during ping websocket frame read

components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/connection/ConnectionHandler.java, components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/pool/Configuration.java, components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/pool/ConnectionPool.java
Fixes: https://github.com/wso2-extensions/esb-connector-file/issues/190
With this what we changed in the design is that we have used a connection pool for each destination rather than the previously used single cached connection.
So when there is more concurrency the number of connections will increase and improve the performance.
Also, the main feature was to support "Aged Connection Timeout " for pools
where you can configure "sftpPoolConnectionAgedTimeout" property in init section and define a life span for each pool.
The difference here is with this timeout unlike other timeouts we could gracefully clear existing connections while handing over the new operations to another pool once the time out reached.
=> Add aged connection timeout mechanism to connector core

components/mediation-admin/org.wso2.carbon.mediation.security/src/main/java/org/wso2/carbon/mediation/security/vault/RegistrySecretRepository.java
When we enabled the debug log to the class "**RegistrySecretRepository**". We have observed the **INFO** log in the wso2carbon  logs.
Therefore, I have changed the log level from INFO to DEBUG level.
=> Change faulty log level to DEBUG from INFO

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/management/WebsocketSubscriberPathManager.java
To fix NPE when the server shuts down after invoking WebSocket API
Handled identified places that should handle possible null values.
*Tested with WS and WSS connections*
=> Fix NPE when server shutdown after invoking WebSocket API

components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/service/RestApiAdmin.java
$subject
API should be initialized before adding to the SynapseConfiguration registry. Else, the API would be allowed to serve traffic and it causes ConcurrentModification exception if Handler initialization and API invocation occurs parallely.
Resolves https://github.com/wso2/api-manager/issues/1538
=> Initialize API before adding it to Registry

components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/pool/Configuration.java
Previously we were not considering FSO params when setting the values (only considering the query params) of FileConnectors
Fixes: https://github.com/wso2/api-manager/issues/1969
=> Considering FSO params when setting the values

components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/connection/ConnectionHandler.java, components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/connection/LocalEntryUndeployCallBack.java, components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/connection/LocalEntryUndeployObserver.java, components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/util/Constants.java
I introduced an enhancement to the way we handle connections in relation to local entries.
A mechanism was established where the key associated with a localEntry is passed from the InvokeMediator
to the TemplateMediator then further propagated to the TemplateContext, ensuring that the specific localEntry is accessible from the connection handling code.
With the availability of the localEntry key, each active connection(dynamic/static) has been bound to its respective localEntry in a map.
So when a localEntry is undeployed or removed, this change is detected by the Synapse Observer, and the connections associated with that specific localEntry are invalidated.
Fixes: https://github.com/wso2/micro-integrator/issues/3002
=> Support invalidating connections when related local entry changed

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConnectionFactory.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConstants.java
Allow enabling hostname verification
The following configuration is required in the `deployment.toml` to enable hostname verification if it is disabled.
```toml
[transport.wss.sender.parameters]
"ws.client.enable.hostname.verification" = true
```
=> [Master] Add web socket transport sender hostname verification

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConstants.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketTransportSender.java
$Subject.
- This is achieved via the `ws.headers.preserve` property. (This property name is kept on par with the HTTP property - `http.headers.preserve` which appears in `passthru-http.properties`).
Websocket headers that should be preserved from the original request should be added as follows, in the `deployment.toml`:
```toml
[transport.ws] # or [transport.wss]
sender.parameters."ws.headers.preserve" = "Origin,host"
```
The above example would preserve the `Origin` and `host` headers.
- In order to address the NPE when providing the following configurations in `deployment.toml` and sending request with either `origin` or `host` header missing.
```toml
[transport.ws] # or [transport.wss]
sender.parameters."ws.headers.preserve" = "Origin,host"
```
**Request:**
```
wscat -c …
```
=> Add implementation to preserve websocket headers with null check for preserved header value

components/mediation-initializer/org.wso2.carbon.mediation.transport.handlers/pom.xml, features/mediation-initializer-features/org.wso2.carbon.mediation.initializer.server.feature/pom.xml, features/mediation-initializer-features/org.wso2.carbon.mediation.light.initializer.server.feature/pom.xml, pom.xml
Upgrade the following dependencies to their latest:
- Netty dependency version to 4.1.104.Final,
- Fasterxml Jackson-databind, and Jackson Dataformat Yaml versions to 2.16.1,
- Google Guava version to 33.0.0-jre,
- Carbon Analytics Common version to 5.3.7,
- Snakeyaml version to 2.0,
- Swagger Parser Orbit version to 2.1.18.wso2v1.
=> Upgrade Netty, Fasterxml, Guava, Snakeyaml, Analytics Common, and Swagger Parser dependencies

components/mediation-admin/org.wso2.carbon.endpoint/src/main/java/org/wso2/carbon/endpoint/service/EndpointAdmin.java
Fix https://github.com/wso2/api-manager/issues/2484
During high traffic scenarios, issues arose with the deployment of APIs due to the limited functionality of the isEndpointExist function. This function solely checked for the existence of keys in the localregistry <String, Object> map, leading to complications when other objects, such as 'Entry', were present. Specifically highlighted in the https://github.com/wso2/api-manager/issues/2484 scenario, the function inaccurately returned true even in the presence of non-Endpoint type objects, disrupting both the API deployment and invocation flows because after checking this, we try to delete an Endpoint which is not there. This pull request addresses these challenges by refining the behavior of isEndpointExist, ensuring it accurately …
=> Fix issues while deploying APIs during high traffic

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConnectionFactory.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConstants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/Constants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketChannelInitializer.java
This PR fixes the issue in web-socket transport when the invoking URL length exceeds 4096 bytes. This is because 4096 is set as the default HTTP server codec initial length size.
The above issue is fixed by introducing new configurations to set maximum values for below parameters in both inbound and outbound Netty websocket transport. These are typically used during the websocket handshake process, which involves upgrading an HTTP connection to a websocket connection.
- http server/client codec initial line length : Related to HTTPServerCodec and HTTPClientCodec which handles conversion between bytes and HTTP messages. Increasing this value allows for longer URLs.
- http server/client codec header size : Defined the maximum size allowed for HTTP headers. By increasing this value, you can …
=> Fix netty limitation for length URIs exceeding 4096 bytes

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/executors/ScriptExecutor.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/mapper/MappingResource.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/utils/DataMapperEngineConstants.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/DataMapperMediator.java
$subject
With the new MI VSCode extension, the DMC file is generated during build time. Hence, to simplify the process, the map function name is fixed as a constant.
=> Simplify datamapper map function name

components/mediation-admin/org.wso2.carbon.mediation.artifactuploader/src/main/java/org/wso2/carbon/mediation/artifactuploader/SynapseArtifactUploaderAdmin.java, components/mediation-admin/org.wso2.carbon.mediation.artifactuploader/src/main/java/org/wso2/carbon/mediation/artifactuploader/util/SynapseArtifactUploaderUtil.java
This PR,
- Adds a filetype restriction to uploadArtifacts operation to allow only xml files.
- Adds a check in uploadArtifacts operation to allow file uploads only inside the extensions folder.
- Adds a check in removeArtifacts operation to allow removal of file inside the extensions folder only.
=> Fix issues in SynapseArtifactUploaderAdmin service

pom.xml
This PR Upgrades the swagger-parser version to 2.1.22.
Orbit bundles: https://github.com/wso2/orbit/pull/1133
carbon-apimgt PR: https://github.com/wso2/carbon-apimgt/pull/12586
product-apim PR: https://github.com/wso2/product-apim/pull/13540
=> [APIM-4.4.0] Upgrade swagger-parser version

pom.xml
Upgrades commons-text version from 1.6.0.wso2v1 to 1.10.0.wso2v2.
=> Upgrade commons-text version

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/executors/ScriptExecutor.java
$subject
NashornJS produces a Map when evaluating json arrays. With graaljs integration, an abstract list is produced instead of Map. Hence to preserve backward compatibility, this change is needed.
=> Preserve backward compatibility with json arrays in Datamapper

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketChannelInitializer.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/WebSocketAccessLoggingHandler.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/WebsocketAccessLogger.java
Feature to add websocket access logs
=> Websocket access logging feature 

components/mediators/datamapper/org.wso2.carbon.mediator.datamapper.engine/src/main/java/org/wso2/carbon/mediator/datamapper/engine/core/executors/ScriptRunner.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/DataMapperMediator.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/config/xml/DataMapperMediatorConstants.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/config/xml/DataMapperMediatorFactory.java, components/mediators/datamapper/org.wso2.carbon.mediator.datamapper/src/main/java/org/wso2/carbon/mediator/datamapper/config/xml/DataMapperMediatorSerializer.java
$subject
Eg DM script:
```
export function mapFunction(input: Root, vars: Record<string, any>): OutputRoot {
return {
test: input.hello + " " + vars.inputKey + " " + vars.inputKey2.name
}
}
```
Synapse API:
```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/dmapi" name="DMAPI" xmlns="http://ws.apache.org/ns/synapse">
<resource methods="POST" uri-template="/">
<inSequence>
<variable name="inputKey" type="STRING" value="Nauran" />
<variable name="inputKey2" type="JSON" value="{&quot;name&quot; : &quot;doe&quot;}" />
<datamapper
config="resources:datamapper/dm1/dm1.dmc"
inputSchema="resources:datamapper/dm1/dm1_inputSchema.json" …
```
=> Avoid schema validation and implement minimal datamapper

components/mediation-connector/org.wso2.carbon.connector.core/src/main/java/org/wso2/carbon/connector/core/connection/ConnectionHandler.java
Fixes: https://github.com/wso2/product-micro-integrator/issues/3963
=> Fix sftp connection shuffle

components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/Constants.java, components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/websocket/InboundWebsocketSourceHandler.java
Fixes https://github.com/wso2/api-manager/issues/3871
When below configuration is set to false, Gateway will not negotiate subprotocols sent in the `Sec-Websocket-Protocol` header. Instead it will simply pass all the protocols mentioned in the header to netty which will internally pick a protocol.
```
[synapse_properties]
'ws.transport.subprotocol.negotiate' = false
```
**Known Limitations**
- In this approach, when multiple protocols are sent in the request header netty will always pick the first protocol [1] (Since GW is unware of the protocols supported by the actual BE at this point). This will be addressed with https://github.com/wso2/api-manager/issues/3871
[1]. …
=> Introduce a config to turn off websocket subprotocol negotiation

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConnectionFactory.java, components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConstants.java
This update refactors `WebsocketConnectionFactory` to use a shared, configurable `EventLoopGroup` for managing WebSocket client connections. It improves resource efficiency by eliminating the need to create a new thread pool for each connection.
The shared event loop group size can be configured using the following configurations. For example, in `deployment.toml`:
```toml
[transport.ws.sender.parameters]
'wsSharedEventLoopPoolSize' = 5
```
```toml
[transport.wss.sender.parameters]
'wsSharedEventLoopPoolSize' = 5
```
Fix: https://github.com/wso2/api-manager/issues/3889
=> Share the event loop group from WebsocketConnectionFactory

pom.xml
This PR adds the following dependency upgrades:
- carbon identity entitlement proxy version: 5.4.4 to 5.4.6
- axis2 version: 1.6.1-wso2v102 to 1.6.1-wso2v105
- axiom version: 1.2.11-wso2v22 to 1.2.11-wso2v29
=> Upgrade axis2 and axiom versions

components/carbon-transports/websocket/org.wso2.carbon.websocket.transport/src/main/java/org/wso2/carbon/websocket/transport/WebsocketConnectionFactory.java
Fix password verification failure issue for WebSocket APIs when the truststore password is encrypted with Secure Vault.
Resolve the encrypted truststore password using MiscellaneousUtil.resolve with SecretResolverFactory before loading the keystore.
Fixes: https://github.com/wso2/api-manager/issues/4151
=> Add truststore password resolution using secure vault for websokcet apis
